### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by tomsing1** [xia-lab/MetaboAnalystR#1]
Thanks a lot for making Metaboanalyst and this package available. Awesome resources for the community! :thumbsup::thumbsup:

I noticed that the installation instructions in the README.md file suggest to use `install.packages` for CRAN packages and `biocLite` for Bioconductor packages. Actually, the latter will pull CRAN packages automatically as well. So you can simplify the procedure using only `biocLite`.

Cheers,
Thomas

**Comment by jsychong** [comment]
Awesome, thank you for the input! Will be making a change to the installation instructions.

Cheers,
Jasmine
