### ISSUE TITLE
Error in .read.metaboanalyst.lib("compound_db.rds") :    object 'my.lib' not found

### ISSUE THREAD

**Issue by YasinEl** [xia-lab/MetaboAnalystR#100]
Hello, I am coming across an error when going through your vignette:

```
library(MetaboAnalystR)
# Create vector consisting of compounds for enrichment analysis 
tmp.vec <- c("Acetoacetic acid", "Beta-Alanine", "Creatine", "Dimethylglycine", "Fumaric acid", "Glycine", "Homocysteine", "L-Cysteine", "L-Isolucine", "L-Phenylalanine", "L-Serine", "L-Threonine", "L-Tyrosine", "L-Valine", "Phenylpyruvic acid", "Propionic acid", "Pyruvic acid", "Sarcosine")
# Create mSetObj for storing objects created during your analysis
mSet<-InitDataObjects("conc", "pathora", FALSE)
# Set up mSetObj with the list of compounds
mSet<-Setup.MapData(mSet, tmp.vec);
# Cross reference list of compounds against libraries (hmdb, pubchem, chebi, kegg, metlin)
mSet<-CrossReferencing(mSet, "name");
```
I get the output:

> 
> [1] "Loading files from server unsuccessful. Ensure curl is downloaded on your computer."
> Error in .read.metaboanalyst.lib("compound_db.rds") : 
>   object 'my.lib' not found
> 

I did install curl and it seems to work using the windows cmd. I also tried to download "compound_db.rds" manually and putting it into my current working directory but I still got the same error.

I am using a computer with Windows 7 with 64 bit and` sessionInfo()` returns: 

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] MetaboAnalystR_2.0.4 data.table_1.12.8    pls_2.7-2            lattice_0.20-41     
> 
> loaded via a namespace (and not attached):
>   [1] backports_1.1.6        Hmisc_4.4-0            fastmatch_1.1-0        sn_1.6-1              
>   [5] plyr_1.8.6             igraph_1.2.5           lazyeval_0.2.2         CAMERA_1.40.0         
>   [9] splines_3.6.3          BiocParallel_1.18.1    ggplot2_3.3.0          TH.data_1.0-10        
>  [13] digest_0.6.25          foreach_1.5.0          htmltools_0.4.0        gdata_2.18.0          
>  [17] fansi_0.4.1            magrittr_1.5           checkmate_2.0.0        memoise_1.1.0         
>  [21] cluster_2.1.0          doParallel_1.0.15      limma_3.40.6           recipes_0.1.10        
>  [25] gower_0.2.1            sandwich_2.5-1         siggenes_1.58.0        jpeg_0.1-8.1          
>  [29] colorspace_1.4-1       blob_1.2.1             xfun_0.12              dplyr_0.8.5           
>  [33] jsonlite_1.6.1         crayon_1.3.4           graph_1.62.0           impute_1.58.0         
>  [37] survival_3.1-11        zoo_1.8-7              iterators_1.0.12       glue_1.4.0            
>  [41] gtable_0.3.0           ipred_0.9-9            zlibbioc_1.30.0        BiocGenerics_0.30.0   
>  [45] DEoptimR_1.0-8         scales_1.1.0           vsn_3.52.0             mvtnorm_1.1-0         
>  [49] DBI_1.1.0              bibtex_0.4.2.2         Rcpp_1.0.4             metap_1.3             
>  [53] plotrix_3.7-7          mzR_2.18.1             viridisLite_0.3.0      htmlTable_1.13.3      
>  [57] foreign_0.8-76         bit_1.1-15.2           preprocessCore_1.46.0  Formula_1.2-3         
>  [61] stats4_3.6.3           lava_1.6.7             prodlim_2019.11.13     httr_1.4.1            
>  [65] htmlwidgets_1.5.1      fgsea_1.10.1           gplots_3.0.3           RColorBrewer_1.1-2    
>  [69] acepack_1.4.1          TFisher_0.2.0          ellipsis_0.3.0         pkgconfig_2.0.3       
>  [73] reshape_0.8.8          XML_3.99-0.3           nnet_7.3-13            caret_6.0-86          
>  [77] tidyselect_1.0.0       rlang_0.4.5            reshape2_1.4.3         munsell_0.5.0         
>  [81] tools_3.6.3            cli_2.0.2              generics_0.0.2         RSQLite_2.2.0         
>  [85] stringr_1.4.0          mzID_1.22.0            ModelMetrics_1.2.2.2   knitr_1.28            
>  [89] bit64_0.9-7            robustbase_0.93-6      scrime_1.3.5           caTools_1.18.0        
>  [93] purrr_0.3.3            RANN_2.6.1             ncdf4_1.17             RBGL_1.60.0           
>  [97] nlme_3.1-145           compiler_3.6.3         rstudioapi_0.11        plotly_4.9.2.1        
> [101] png_0.1-7              affyio_1.54.0          MassSpecWavelet_1.50.0 tibble_3.0.0          
> [105] stringi_1.4.6          MSnbase_2.10.1         ProtGenerics_1.16.0    Matrix_1.2-18         
> [109] multtest_2.40.0        vctrs_0.2.4            mutoss_0.1-12          pillar_1.4.3          
> [113] lifecycle_0.2.0        BiocManager_1.30.10    Rdpack_0.11-1          MALDIquant_1.19.3     
> [117] bitops_1.0-6           gbRd_0.4-11            xcms_3.6.2             R6_2.4.1              
> [121] latticeExtra_0.6-29    pcaMethods_1.76.0      affy_1.62.0            KernSmooth_2.23-16    
> [125] gridExtra_2.3          IRanges_2.18.3         codetools_0.2-16       MASS_7.3-51.5         
> [129] gtools_3.8.2           assertthat_0.2.1       withr_2.1.2            mnormt_1.5-6          
> [133] multcomp_1.4-12        S4Vectors_0.22.1       parallel_3.6.3         grid_3.6.3            
> [137] rpart_4.1-15           timeDate_3043.102      tidyr_1.0.2            class_7.3-16          
> [141] Cairo_1.5-11           pROC_1.16.2            numDeriv_2016.8-1.1    Biobase_2.44.0        
> [145] lubridate_1.7.8        base64enc_0.1-3   

Thank you a lot for your time and effort

**Comment by xiaodfeng** [comment]
I came across the same problem.

**Comment by gparfitt2** [comment]
Hi Everyone,
I have the same problem here!
Thank you!

**Comment by junli-song** [comment]
you can see the recent issue,which is edited by songjunjun.

> The error is caused by: print(), this function needs an argument, such as print("")
MetaboAnalystR/R/general_data_utils.R: line 936, 952, 962.

**Comment by NickFiore-1** [comment]
Also having the same issue!

**Comment by junli-song** [comment]
you can comment out two contents :warning = function(w) { print(" ") }

>  metaboanalystR//R //general_data_utils.rds

`# Deal w. corrupt downloaded files
  tryCatch({
    my.lib <- readRDS(lib.path); # this is a returned value, my.lib never called outside this function, should not be in global env.
    print("Loaded files from MetaboAnalyst web-server.")
  },
  # warning = function(w) { print(" ") },
  error = function(err) {
    print("Reading data unsuccessful, attempting to re-download file...")
    tryCatch(
      {
        lib.url <- paste("https://www.metaboanalyst.ca/resources/libs/", filenm, sep="");
        download.file(lib.url, destfile=filenm, method="curl")
        my.lib <- readRDS(lib.path);
        print("Loaded necessary files.")
      },
      # warning = function(w) { print(" ") },
      error = function(err) {
        print("Loading files from server unsuccessful. Ensure curl is downloaded on your computer.")
      }
    )`

**Comment by xiaodfeng** [comment]
Hi, I am wondering is this issue solved already in the latest version? I am now using MetaboAnalystR_3.0.2. I still have the problem.

**Comment by MahrWe** [comment]
I encountered the same problem on Windows [mingw32]. For me it was solved by building the RCurl package with a more recent version of curl.
before (issue persists):
```
> RCurl::curlVersion()
$age
[1] 3

$version
[1] "7.40.0"

$vesion_num
[1] 468992

$host
[1] "x86_64-pc-win32"

$features
      ssl      libz      ntlm asynchdns    spnego largefile       idn      sspi 
        4         8        16       128       256       512      1024      2048 

$ssl_version
[1] "OpenSSL/1.0.0o"

$ssl_version_num
[1] 0

$libz_version
[1] "1.2.8"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "pop3"   "pop3s"  "rtmp"   "rtsp"   "scp"   
[16] "sftp"   "smtp"   "smtps"  "telnet" "tftp"  

$ares
[1] ""

$ares_num
[1] 0

$libidn
[1] ""
```
after (solved, download of db files is successful):
```
> RCurl::curlVersion()
$age
[1] 4

$version
[1] "7.64.1"

$vesion_num
[1] 475137

$host
[1] "x86_64-w64-mingw32"

$features
       ipv6         ssl        libz        ntlm   asynchdns      spnego   largefile         idn        sspi tlsauth_srp 
          1           4           8          16         128         256         512        1024        2048       16384 

$ssl_version
[1] "OpenSSL/1.1.1g (Schannel)"

$ssl_version_num
[1] 0

$libz_version
[1] "1.2.11"

$protocols
 [1] "dict"   "file"   "ftp"    "ftps"   "gopher" "http"   "https"  "imap"   "imaps"  "ldap"   "ldaps"  "pop3"   "pop3s"  "rtsp"   "scp"   
[16] "sftp"   "smtp"   "smtps"  "telnet" "tftp"  

$ares
[1] ""

$ares_num
[1] 0

$libidn
[1] ""
```

**Comment by jessica-ewald** [comment]
For many people, this issue is solved by downloading most recent version of 'curl'. We have also merged changes suggested here https://github.com/xia-lab/MetaboAnalystR/pull/105 in version 4.0 that will be released soon.
