### ISSUE TITLE
Error in: MSpeaks to pathway module(currency/ adducts cuatomization)

### ISSUE THREAD

**Issue by junli-song** [xia-lab/MetaboAnalystR#103]
> mSet<-PerformPSEA(mSet, "hsa_mfn", "current", 100)
[1] "v1"
Error in currency <<- user.curr : 无法改变被锁定的联编'currency'的值
> mSet<-PlotPeaks2Paths(mSet, "peaks_to_paths_1_", "png", 72, width=NA)
错误: 无法打开文件'E:/R-3.6.3/library/MetaboAnalystR/R/MetaboAnalystR.rdb': No such file or directory
此外: Warning message:
重新评估被中断的许诺

**Comment by Zhiqiang-PANG** [comment]
Hi, junli. The latest version for mummichog v2 have been provided. Please try to re-install the latest version and use the new version 2 for pathway analysis. V1 is provided only for validation and is phasing out. If you have any issue, please let us know. Cheers.

**Comment by junli-song** [comment]
But there is  the same problem :
`> mSet<-PerformPSEA(mSet, "hsa_mfn", "current", 100)
[1] "v2"
Error in currency <<- user.curr : 无法改变被锁定的联编'currency'的值
> mSet<-PlotPeaks2Paths(mSet, "peaks_to_paths_1_", "png", 72, width=NA)
Error in log10(mummi.mat[, 5]) : 数学函数中用了非数值参数`
![image](https://user-images.githubusercontent.com/60053445/80165795-de921080-860e-11ea-8530-a2b8786418a1.png)

**Comment by Zhiqiang-PANG** [comment]
Hi, junli. Could you please send me your mSet.rda and sessionInfo.rda file so that I can check what is going on? Thanks.
