### ISSUE TITLE
download, MetaboAnalyst web-based

### ISSUE THREAD

**Issue by ZunpengLiu** [xia-lab/MetaboAnalystR#104]
Hi,

I am using the fantastic web-based tool MetaboAnalyst to ananlysis my metabolize data.

It's so convenient. However, I noticed that the download files are not included the metabolites in the corresponding enriched pathway when I conducted the enrichment SPMDB analysis through MetaboAnalyst. Yes, I can click the bottom of “Hits” in the MetaboAnalyst  web, it shows the enriched metabolite in each term. How can I obtain this information in csv file?

Many many thanks!

Zunpeng

**Comment by Zhiqiang-PANG** [comment]
You can download it from the download page. I am closing this. If you still have question, please post it here: https://omicsforum.ca/c/metaboanalyst/5
