### ISSUE TITLE
MetaboAnalystR on Mac

### ISSUE THREAD

**Issue by wanchichang04** [xia-lab/MetaboAnalystR#107]
Hi, I was trying to install MetaboAnalystR on my Mac following the tutorial on the website: https://www.metaboanalyst.ca/docs/RTutorial.xhtml#1.2%20Installation
I tried 1) download the tar. file and manually install it in R, and 2) use devtool to install the package. However, none of them seems to work. I was wondering is it because I'm using the OS system (mac) instead of Linux or Windows? I've been trying all day, it's really frustrating.

Here are my error messages: 
> install.packages("~/Downloads/MetaboAnalystR_3.0.0.tar", repos = NULL, type = "source")
* installing *source* package ‘MetaboAnalystR’ ...
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c Internal_utils_batch.c -o Internal_utils_batch.o
gfortran  -fPIC  -Wall -g -O2  -c decorana.f -o decorana.o
make: gfortran: No such file or directory
make: *** [decorana.o] Error 1
ERROR: compilation failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/MetaboAnalystR’
Warning in install.packages :
  installation of package ‘/Users/wanchichang/Downloads/MetaboAnalystR_3.0.0.tar’ had non-zero exit status
> devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 15 packages not available: impute, pcaMethods, globaltest, GlobalAncova, Rgraphviz, preprocessCore, genefilter, SSPA, sva, limma, KEGGgraph, siggenes, BiocParallel, MSnbase, multtest
✓  checking for file ‘/private/var/folders/s0/t24bm1h94bndxq7t1kc1gk_h0000gn/T/Rtmp1CMX4R/remotes14675303dc50/xia-lab-MetaboAnalystR-e78123d/DESCRIPTION’ ...
─  preparing ‘MetaboAnalystR’: (838ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (1.8s)
─  checking for empty or unneeded directories
─  building ‘MetaboAnalystR_3.0.2.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘MetaboAnalystR/vignettes/MetaboAnalystR_3_workflow_Towards_Optimized_Workflow_for_Global_Metabolomics.Rmd’
   
* installing *source* package ‘MetaboAnalystR’ ...
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c Internal_utils_batch.c -o Internal_utils_batch.o
gfortran  -fPIC  -Wall -g -O2  -c decorana.f -o decorana.o
make: gfortran: No such file or directory
make: *** [decorana.o] Error 1
ERROR: compilation failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/MetaboAnalystR’
Error: Failed to install 'MetaboAnalystR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/s0/t24bm1h94bndxq7t1kc1gk_h0000gn/T//Rtmp1CMX4R/file14673c57f388/MetaboAnalystR_3.0.2.tar.gz’ had non-zero exit status
>

**Comment by Zhiqiang-PANG** [comment]
Hi, It seems that your computer's compiler for fortran code doesn't work normally. Please check that thing. Thanks.

**Comment by the8thday** [comment]
i hava the same problem, and i also download the newest gfortran, but ERROR still there

**Comment by izu0421** [comment]
sophie888834 and the8thday, what is the version of your GDAL? Do `gdalinfo --version` on the terminal

**Comment by the8thday** [comment]
> sophie888834 and the8thday, what is the version of your GDAL? Do `gdalinfo --version` on the terminal

when run gdalinfo --version,  `zsh: command not found: gdalinfo` happened,  it seems i dont have gdal, then i brew install gdal.  it takes a long time and i will try to install MetaboAnalystR after gdal installed and pull an issue here

**Comment by wyu** [comment]
I had the same problem on my Mac, even after the installation of gFortran pkg. It turns out that I need to explicitly export the path to the compiler:

export PATH=$PATH:/usr/local/gfortran/bin

**Comment by yandingbo** [comment]
In Win10, you can try to add the bin file of rtool to the computer environment variable
Like this  E:\R\rtools40\mingw64\bin

**Comment by holmes0527** [comment]
Hello ~ @wanchichang04 and @wyu, In my case, no matter what about ur gcc version now. You have to install both 'x.code' and 'gfortran8.2' (only verion gfortran8.2). I had been installed the newest version but still got "ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0" error during install MetaboAnalystR.
Therefore, open the terminal and type 'xcode-select --install' first , then download and install the gfortran8.2. 'https://github.com/fxcoudert/gfortran-for-macOS/releases/download/8.2/gfortran-8.2-Mojave.dmg'
Finally, install MetaboAnalystR again!
'devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)'
I solved by this way, hope useful for yours! by the way, my OS is macOS Big Sur 11.2.3 now.
Attach my reference link 'https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/'

**Comment by boomath** [comment]
RROR: lazy loading failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/MetaboAnalystR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/3s/ppr3_x0d5296tjpwngyvz4fw0000gr/T//Rtmp2tdAXd/file11d8f5da3d9ec/MetaboAnalystR_3.2.0.tar.gz’ had non-zero exit status


Can you give me the solution for this?

**Comment by boomath** [comment]
ERROR: lazy loading failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/MetaboAnalystR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/3s/ppr3_x0d5296tjpwngyvz4fw0000gr/T//Rtmp2tdAXd/file11d8f5da3d9ec/MetaboAnalystR_3.2.0.tar.gz’ had non-zero exit status

Can you give suggestion to solve this?

**Comment by Zhiqiang-PANG** [comment]
A solution provided. closed.
