### ISSUE TITLE
MetaboanalystR- Enrichment Error in if (nchar(nm) <= max.len) { : argument has length 0 

### ISSUE THREAD

**Issue by emarinmi** [xia-lab/MetaboAnalystR#109]
Hi,

I just find this error using the same script than in https://www.metaboanalyst.ca/ using the function PlotQEA.Overview

I think that function CalculateGlobalTestScore is not working. There is not the msea_network.json and msea_qea_results files after running this function

mSet<-InitDataObjects("conc", "msetqea", FALSE)
mSet<-Read.TextData(mSet, "http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv", "rowu", "disc");
mSet<-CrossReferencing(mSet, "name");
mSet<-CreateMappingResultTable(mSet)
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "NULL", "NULL", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-SetCurrentMsetLib(mSet, "smpdb_pathway", 2);
mSet<-CalculateGlobalTestScore(mSet)
mSet<-PlotQEA.Overview(mSet, "qea_0_", "net", "png", 72, width=NA)

Thanks

**Comment by emarinmi** [comment]
I think that function CalculateGlobalTestScore is not working. The is not .json and msea_qea_results files after running this function

**Comment by xia-lab** [comment]
Closed due to inactivity.
