### ISSUE TITLE
could not find function "GetMapTable"

### ISSUE THREAD

**Issue by doctorcgb** [xia-lab/MetaboAnalystR#11]
CreatePDFReport(mSet, "h")
Writing to file Analysis_Report.tex
Processing code chunks with options ...
 1 : keep.source term verbatim (Analysis_Report.Rnw:4)
 2 : keep.source term tex (Analysis_Report.Rnw:50)

Error:  chunk 2 
Error in eval(expr, envir, enclos) : 
  could not find function "GetMapTable"

I installed the package by downloading the MetaboAnalystR_0.0.0.9000.tar.gz.

**Comment by jsychong** [comment]
Thanks for letting us know! The function is now exported and you should be able to generate the PDF report after re-installing the MetaboAnalystR package.
