### ISSUE TITLE
How to customize legend position in PCA, PLSDA, SPLSDA?

### ISSUE THREAD

**Issue by ozanfaw** [xia-lab/MetaboAnalystR#111]
I did multivariative analysis by PCA, PLSDA, SPLSDA, its work well, however, the result of the figure was covered up by the legend position inside the figure. Is there any way to modify the position of legend. 

I use metaboanalystR package. 

Thank you so much for developing this package. it is very helpful.

Regards,

**Comment by xia-lab** [comment]
Closed due to inactivity
