### ISSUE TITLE
Will not Install

### ISSUE THREAD

**Issue by episkounova** [xia-lab/MetaboAnalystR#112]
This is the error that I get. Please help with how to deal with this?

> devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 15 packages not available: impute, pcaMethods, globaltest, GlobalAncova, Rgraphviz, preprocessCore, genefilter, SSPA, sva, limma, KEGGgraph, siggenes, BiocParallel, MSnbase, multtest
✓  checking for file ‘/private/var/folders/_j/rgnmw1s94bggfgz5xd43nrx00000gp/T/RtmpvSxiFu/remotesb867142a3e6d/xia-lab-MetaboAnalystR-e78123d/DESCRIPTION’ (340ms)
─  preparing ‘MetaboAnalystR’: (355ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (673ms)
─  checking for empty or unneeded directories
─  building ‘MetaboAnalystR_3.0.2.tar.gz’
   Warning in utils::tar(filepath, pkgname, compression = compression, compression_level = 9L,  :
     storing paths of more than 100 bytes is not portable:
     ‘MetaboAnalystR/vignettes/MetaboAnalystR_3_workflow_Towards_Optimized_Workflow_for_Global_Metabolomics.Rmd’
   
* installing *source* package ‘MetaboAnalystR’ ...
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c Internal_utils_batch.c -o Internal_utils_batch.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c decorana.f -o decorana.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c mzROI.c -o mzROI.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c util.c -o util.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c xcms_binners.c -o xcms_binners.o
xcms_binners.c:11:1: warning: '/*' within block comment [-Wcomment]
/*
^
xcms_binners.c:361:7: warning: unused variable 'idx' [-Wunused-variable]
  int idx = 0;
      ^
2 warnings generated.
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o MetaboAnalystR.so Internal_utils_batch.o decorana.o init.o mzROI.o util.o xcms_binners.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-MetaboAnalystR/00new/MetaboAnalystR/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘MSnbase::normalize’ by ‘igraph::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘data.table::melt’ by ‘reshape::melt’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::decompose’ by ‘stats::decompose’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘pls::loadings’ by ‘stats::loadings’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘gplots::lowess’ by ‘stats::lowess’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘MSnbase::smooth’ by ‘stats::smooth’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::spectrum’ by ‘stats::spectrum’ when loading ‘MetaboAnalystR’
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘crmn’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/MetaboAnalystR’
Error: Failed to install 'MetaboAnalystR' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_j/rgnmw1s94bggfgz5xd43nrx00000gp/T//RtmpvSxiFu/fileb867fae7e54/MetaboAnalystR_3.0.2.tar.gz’ had non-zero exit status
>

**Comment by Zhiqiang-PANG** [comment]
no compatiable gfortran available for your Mac OX. I am closing it.
