### ISSUE TITLE
mSet<-Normalization(mSet1, "NULL", "LogNorm", "MeanCenter", ref=NULL, ratio=FALSE, ratioNum=20) Error in abs(data[data != 0]) :    non-numeric argument to mathematical function

### ISSUE THREAD

**Issue by uqvirg** [xia-lab/MetaboAnalystR#113]
Hi,
I've just try to install and test MetaboAnalyst.

My code was as described in tutorial:
metanr_packages <- function(){
  metr_pkgs <- c("impute", "pcaMethods", "globaltest", "GlobalAncova", "Rgraphviz", "preprocessCore", "genefilter", "SSPA", "sva", "limma", "KEGGgraph", "siggenes","BiocParallel", "MSnbase", "multtest","RBGL","edgeR","fgsea","devtools","crmn")
  list_installed <- installed.packages()
  new_pkgs <- subset(metr_pkgs, !(metr_pkgs %in% list_installed[, "Package"]))
  if(length(new_pkgs)!=0){if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
    BiocManager::install(new_pkgs)
    print(c(new_pkgs, " packages added..."))
  }
  
  if((length(new_pkgs)<1)){
    print("No new packages added...")
  }
}
metanr_packages()

# Step 1: Install devtools
install.packages("devtools")
library(devtools)

# Step 2: Install MetaboAnalystR without documentation
devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)
library("MetaboAnalystR")
mSet<-InitDataObjects("conc", "stat", FALSE)
**Error: $ operator is invalid for atomic vectors**
mSet<-Read.TextData(mSet, "http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv", "rowu", "disc");
**Error: $ operator is invalid for atomic vectors**

And I had the error Error: $ operator is invalid for atomic vectors.

Could you tell me what's wrong.

Thank you,
Virgg

**Comment by uqvirg** [comment]
ok

**Comment by uqvirg** [comment]
Hi,
I'm wandering where I can find an easy example to use MetaboAnalyst with R
I currently have this error:
mSet<-Normalization(mSet1, "NULL", "LogNorm", "MeanCenter", ref=NULL, ratio=FALSE, ratioNum=20)
Error in abs(data[data != 0]) : 
  non-numeric argument to mathematical function

**Comment by zhssakura** [comment]
> Hi,
> I'm wandering where I can find an easy example to use MetaboAnalyst with R
> I currently have this error:
> mSet<-Normalization(mSet1, "NULL", "LogNorm", "MeanCenter", ref=NULL, ratio=FALSE, ratioNum=20)
> Error in abs(data[data != 0]) :
> non-numeric argument to mathematical function

Hi, 
I am also new to Metaboanalyst. I started with its online tool, based on what's your hypothesis and targets, you can select different analysis workflow to proceed. 

the online version is as below:
https://www.metaboanalyst.ca/MetaboAnalyst/ModuleView.xhtml

Hope this works for you.

Best,

Shan

**Comment by xia-lab** [comment]
Closed due to inactivity. Please use OmicsForum (omicsforum.ca) for further discussions.
