### ISSUE TITLE
Error! Unable to connect to api.metaboanalyst.ca!

### ISSUE THREAD

**Issue by izu0421** [xia-lab/MetaboAnalystR#114]
Hi, 

When I run the exact code for Pathway Analysis at MetaboAnalystR/doc/Pathway_Analysis.html, I receive the issue "Error! Unable to connect to api.metaboanalyst.ca!". This issue is related to the function PlotKEGGPath(). 

When I checked the results of the function, I saw that the query results were null: 
query_results_text: "{\"guestName\":\"guest11067251318988492391tmp\",\"analType\":\"pathora\",\"pathName\":\"Glycine, serine and threonine metabolism\",\"format\":\"png\",\"width\":528,\"height\":480,\"dpi\":0,\"plotName\":null,\"pathintegImpMatName\":null,\"pathintegImpMatFC\":null}"

Can you please help? 

Thanks!

**Comment by billy-s-lab** [comment]
Also experiencing the exact same error.

After running the PlotKeggPath function, the mSet object is changed to a numeric vector with value = 0:
> mSet
[1] 0
> class(mSet)
[1] "numeric"

Also an err.vec is created with the following output: 
[1] ""                                                  "Error! Unable to connect to api.metaboanalyst.ca!"

Please help, thank you!

**Comment by Zhiqiang-PANG** [comment]
this issue has been fixed.
