### ISSUE TITLE
Question of installing MetaboanalystR

### ISSUE THREAD

**Issue by Daisyiscool** [xia-lab/MetaboAnalystR#115]
Hello, 

I'm new to metabolomics. I tried to install Metaboanalyst 3.0 following the installation info in your website. 
All system requirements are met, Linux with libcairo2-dev, libnetcdf-dev, libxml2, libxt-dev and libssl-dev installed. I have issues with proceeding 
devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)

Here is the returned error:
> devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 17 packages not available: impute, pcaMethods, globaltest, GlobalAncova, Rgraphviz, preprocessCore, genefilter, SSPA, sva, limma, KEGGgraph, siggenes, BiocParallel, MSnbase, mnormt, multtest, foreign
Installing 46 packages: pls, Rserve, ellipse, scatterplot3d, Cairo, caTools, e1071, som, RJSONIO, ROCR, pheatmap, fitdistrplus, lars, Hmisc, igraph, gplots, reshape, spls, metap, entropy, rsm, gtools, gdata, png, jpeg, checkmate, bibtex, gbRd, sn, mvtnorm, mnormt, quantreg, SparseM, MatrixModels, plotrix, multcomp, TH.data, sandwich, Formula, latticeExtra, acepack, htmlTable, Rdpack, TFisher, mutoss, estimability
Error: Failed to install 'MetaboAnalystR' from GitHub:
  (converted from warning) package ‘mnormt’ is not available (for R version 3.6.3)

Can anyone help me with this? I have tried R version 4.0, 3.6.1, neither of them worked. Thank you.

Daisy

**Comment by Zhiqiang-PANG** [comment]
Please install "mnormt" firstly.
