### ISSUE TITLE
package {crmn} is missing from pacman installation option

### ISSUE THREAD

**Issue by wmoldham** [xia-lab/MetaboAnalystR#117]
Copy-pasted the list of packages under Step 1 Option 2 from the README. Installation failed with an error with no package called 'crmn'. It appears this package is not contained in the list of packages to be installed by pacman while it is in Step 1 Option 1. When I installed this package, MetaboAnalystR installed successfully. Thank you for the wonderful and amazing resource.

**Comment by Zhiqiang-PANG** [comment]
thanks for advice.
