### ISSUE TITLE
Generating heatmap pdf and table

### ISSUE THREAD

**Issue by SynBioTek** [xia-lab/MetaboAnalystR#12]
Most of the figures from MetaboAnalyst can be found in the zip file in both png and pdf format, however the heatmap and correlation plot figures show up as empty pdf files.  I tried to obtain the pdf files directly from the GUI but the figure does not load.

**Comment by jsychong** [comment]
Hi,

The issue with the pdf generation is related to the current R version for the server and at the moment is beyond our control. We are upgrading the web-server, along with an updated R version, which will be publicly available very shortly, and hopefully this issue will be solved.
