### ISSUE TITLE
Request to add the Faecalibacterium prausnitzii organism in the MS peaks to pathways module

### ISSUE THREAD

**Issue by xiaodfeng** [xia-lab/MetaboAnalystR#123]
I am using the MS peaks to pathways module in MetaboAnalystR 3.0.2 to perform the pathway enrichment for our project on Faecalibacterium prausnitzii. However, I found there is no organism in the option, as shown in the attachment. 
![image](https://user-images.githubusercontent.com/25877500/90949877-f35fa300-e44c-11ea-8b82-1345c2fcb18d.png)
I have checked the kegg website, I found they do offer the pathway about this organism, https://www.kegg.jp/kegg/docs/upd_kegg.html

Can we add the Faecalibacterium prausnitzii organism in the MS peaks to pathways module?
Or can I customize the pathway databases by myself?

**Comment by xia-lab** [comment]
We aim to systematically address the library creation issue in the new releases
