### ISSUE TITLE
CVTest.LRmodel function issue

### ISSUE THREAD

**Issue by AG3OR4** [xia-lab/MetaboAnalystR#125]
Hi, 

I use the R package version (MetaboAnalystR_3.0.3).
In "Tester" option of Biomarker Analysis, "CVTest.LRmodel" function for logistic regression does not work.
The other Tester function "PerformCV.test" works well.

Is there any way to use CVTest.LRmodel?

Thank you.

**Comment by xia-lab** [comment]
This function (CVTest.LRmodel)  should be called from within PerformCV.test, with method="lr". The documentation is updated to reflect this
