### ISSUE TITLE
hsa.rda error - HTTP status was '404 Not found'

### ISSUE THREAD

**Issue by tenzinlhakhang** [xia-lab/MetaboAnalystR#127]
Hi Guys,

I"m getting the following error.

```
trying URL 'https://www.metaboanalyst.ca/resources/libs/kegg/metpa/hsa.rda'
Error in download.file(my.rda, destfile) : 
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/kegg/metpa/hsa.rda'
In addition: Warning message:
In download.file(my.rda, destfile) :
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/kegg/metpa/hsa.rda': HTTP status was '404 Not Found'


```

Is there a solution to this issue? I saw another thread about the same issue but there was no solution mentioned.

thank you,

Tenzin

**Comment by disneian** [comment]
I'm also getting a similar error when trying to run the code
`mSet<-PerformPSEA(mSet, "mmu_kegg", "current", permNum = 1000)`

Error:
`trying URL 'https://www.metaboanalyst.ca/resources/libs/mummichog/mmu_kegg.rds'`
`Error in download.file(mum.url, destfile = filenm, method = "libcurl",  : `
`  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/mummichog/mmu_kegg.rds'`
`In addition: Warning message:`
`In download.file(mum.url, destfile = filenm, method = "libcurl",  :`
`  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/mummichog/mmu_kegg.rds': HTTP status was '404 Not Found'`

I have try the following resouces and none of them work
https://www.metaboanalyst.ca/resources/libs/mummichog/mmu_kegg.rds
https://www.metaboanalyst.ca/resources/libs/mummichog/sub_lipid_class_mset.rds
https://www.metaboanalyst.ca/resources/libs/mummichog/mmu_biocyc.rds

**Comment by tenzinlhakhang** [comment]
I think they may have moved some files around on their servers that need to be downloaded via curl when running some of the functions...

**Comment by Zhiqiang-PANG** [comment]
This is an out-dated issue. I am closing it.
