### ISSUE TITLE
downloaded compound_db.rds file corrupt

### ISSUE THREAD

**Issue by brejnev** [xia-lab/MetaboAnalystR#129]
Hi,
The following line:
 
download.file("https://www.metaboanalyst.ca/resources/libs/compound_db.rds",destfile="compound_db.rds",method="curl")

does download "compound_db.rds" file which seams corrupt with size 1.1K, cannot be read by readRDS() function.  Two weeks ago the same command was working providing a file of   558K which is readable with readRDS() function. Did anything happen to the file recently?

Error message:
Error in readRDS("compound_db.rds") : unknown input format

**Comment by tenzinlhakhang** [comment]
I'm having general issues with the read.rds() lately, specifically with the hsa.rds file right now as well.

**Comment by Zhiqiang-PANG** [comment]
update to the latest version of MetaboAnalystR will fix this issue.
