### ISSUE TITLE
could not find function "CreateMappingResultTable"

### ISSUE THREAD

**Issue by highsugardiet** [xia-lab/MetaboAnalystR#13]
Thank you so much for writing your software and making it available.  I am running into a problem when I try to do an enrichment analysis.  I tried MetaboAnalystR on Windows (10) R studio Version 1.1.414 (R 3.4.3) and Ubuntu R 3.4.3.  I used the vignette Enrichment_Analysis and the script generated using the web server.  I get the same error:

` mSet<-CreateMappingResultTable(mSet)`

`Error in CreateMappingResultTable(mSet) :
  could not find function "CreateMappingResultTable"`

Thanks

**Comment by jsychong** [comment]
Hi,

Thanks for letting us know of this issue. I can't seem to be able to re-create this error, I would suggest 2 things, the first would be to re-install the R package. The second one, does using MetaboAnalystR::CreateMappingResultTable() work?

**Comment by highsugardiet** [comment]
Hi, 
Thanks for looking into this for me.  I re-installed the R package--the error persisted.  Then I tired to run the function using 
`mSet<-MetaboAnalystR:::CreateMappingResultTable(mSet)` 
which worked, but only using Ubuntu.  It did not work using R studio (Windows).
