### ISSUE TITLE
Error in download.file(lib.url, destfile = filenm, method = "libcurl")

### ISSUE THREAD

**Issue by lnbob** [xia-lab/MetaboAnalystR#131]
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - 由于吊销服务器已脱机，吊销功能无法检查吊销。
[1] "Download unsucceful. Ensure that curl is downloaded on your computer."
[1] "Attempting to re-try download using libcurl..."
试开URL’https://www.metaboanalyst.ca/resources/libs/compound_db.rds'
Error in download.file(lib.url, destfile = filenm, method = "libcurl") : 
  无法打开URL'https://www.metaboanalyst.ca/resources/libs/compound_db.rds'

**Comment by brejnev** [comment]
It works well now, with the update code.

**Comment by brejnev** [comment]
This works now with the updated code
