### ISSUE TITLE
cannot open URL 'https://www.metaboanalyst.ca/resources/libs/mummichog/hsa_mfn.rds'

### ISSUE THREAD

**Issue by bblum9** [xia-lab/MetaboAnalystR#139]
Running peaks to pathways as part of larger pipeline using metaboanalyst r package and cannot download data from website.

**Comment by xiaodfeng** [comment]
I have just noticed the source file has been changed from .rds into .qs in the latest version.

**Comment by bblum9** [comment]
Yes, I see that, too. This is a major issue for people that have incorporated this R package into larger workflows. It would be helpful to find a patch to maintain backwards compatibility.

**Comment by ParizadB** [comment]
I have the same problem. How should I solve that?

**Comment by Zhiqiang-PANG** [comment]
Please re-install the package to the latest version.
