### ISSUE TITLE
Enrichment analysis

### ISSUE THREAD

**Issue by jacorvar** [xia-lab/MetaboAnalystR#14]
Hi,

I have a set of metabolites whose concentration levels have been measured, for a bunch of individuals belonging to two conditions (treatment and control).

I've performed a Wilcoxon Rank test to check if there are significant differences for each metabolite between the two groups and then I'd like to perform an enrichment analysis of the significant genes. For this last task, shouldn't I provide the algorithm two sets: one with the significant and another one with all metabolites?

Is it possible todo this with MetaboAnalystR?

Thanks

**Comment by jsychong** [comment]
Hi,

MetaboAnalystR/web, similar to GSEA, accepts a list of significantly different compounds to perform enrichment analysis and tells you if these differentially abundant compounds are associated with certain biological processes/functions. So all you need to provide is the list of metabolites that were significantly enriched using the Wilcoxon Rank test. Giving the algorithm 2 sets would be redundant, as it only works on the DE metabolites. 

Hope this clarified things!
