### ISSUE TITLE
Feature request: submit to CRAN or bioconductor

### ISSUE THREAD

**Issue by bblum9** [xia-lab/MetaboAnalystR#140]
Hello, writing to request this package be submitted to CRAN or bioconductor. The requirements for these repositories would help make this package more robust for installation and versioning. Seems this is a major impediment for broader adoption.

**Comment by JohanLassen** [comment]
Agree - and if it was built as an Anaconda package as well (through Bioconductor).

**Comment by bblum9** [comment]
Given the dependencies, bioconductor looks like a better potential fit.

**Comment by bblum9** [comment]
We can start finding action items based on: https://www.bioconductor.org/developers/package-guidelines/
