### ISSUE TITLE
Can't download the pacakge 

### ISSUE THREAD

**Issue by mizuwatershui** [xia-lab/MetaboAnalystR#141]
Hi there,
I am trying to install the MetaboAnalystR.
I am using an R 4.0.2 version on Mac (platform x86_64-apple-darwin17.0). I tried to manually load the package by this and it seems working 
> pacman::p_load(impute)
> pacman::p_load(fgsea)

However, I encountered this when I tried to install the next step.

>devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = TRUE, build_manual =T)
Downloading GitHub repo xia-lab/MetaboAnalystR@HEAD
Skipping 15 packages not available: multtest, MSnbase, BiocParallel, siggenes, KEGGgraph, limma, sva, SSPA, genefilter, preprocessCore, Rgraphviz, GlobalAncova, globaltest, pcaMethods, impute
Skipping 1 packages ahead of CRAN: Rserve
pdflatex not found! Not building PDF manual.
✓  checking for file ‘/private/var/folders/54/ysmrqmlj28x05xhwq_l0ndpr0000gn/T/RtmpgDJ3B5/remotes1785d17758013/xia-lab-MetaboAnalystR-f603a56/DESCRIPTION’ (3.5s)
─  preparing ‘MetaboAnalystR’: (1.2s)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes (14.1s)
         -----------------------------------
─  installing *source* package ‘MetaboAnalystR’ ...
   ** using staged installation
   ** libs
   clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c Internal_utils_batch.c -o Internal_utils_batch.o
   gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c decorana.f -o decorana.o
   make: gfortran: No such file or directory
   make: *** [decorana.o] Error 1
   ERROR: compilation failed for package ‘MetaboAnalystR’
─  removing ‘/private/var/folders/54/ysmrqmlj28x05xhwq_l0ndpr0000gn/T/RtmpkjelA2/Rinst181898c46e69/MetaboAnalystR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'MetaboAnalystR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** using staged installation
E> ** libs
E> clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c Internal_utils_batch.c -o Internal_utils_batch.o
E> gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c decorana.f -o decorana.o
E> make: gfortran: No such file or directory
E> make: *** [decorana.o] Error 1
E> ERROR: compilation failed for package ‘MetaboAnalystR’
E> * removing ‘/private/var/folders/54/ysmrqmlj28x05xhwq_l0ndpr0000gn/T/RtmpkjelA2/Rinst181898c46e69/MetaboAnalystR’
E>       -----------------------------------
E> ERROR: package installation failed

I am just wondering how can I install it on my Mac.

Thank you very much!

Best,
Shui

**Comment by Zhiqiang-PANG** [comment]
This is gfortran compiler issue for Mac OS. Please install it. I close this issue.
