### ISSUE TITLE
Error in CalculateGlobalTestScore function

### ISSUE THREAD

**Issue by lpantano** [xia-lab/MetaboAnalystR#142]
Hi authors!

Thank you for this package :) it is really useful. 

I am trying the latest version, 3.0.3 and I am finding an error in this line:

https://github.com/xia-lab/MetaboAnalystR/blob/f603a5643f7627845db31793979f8ccf74ab638c/R/enrich_stats.R#L158

```
Error in c_qread(file, use_alt_rep, strict, nthreads) : 
Failed to open dat.in.qs. Check file path.
```

The object is set up as follow:

```
    mSet<-InitDataObjects("conc", "msetqea", FALSE)
    mSet<-Read.TextData(mSet, filename, "rowu", "disc");
    mSet<-CrossReferencing(mSet, "hmdb");
    mSet<-CreateMappingResultTable(mSet)
    mSet<-SanityCheckData(mSet)
    mSet<-ImputeVar(mSet, method="min")
    mSet<-PreparePrenormData(mSet)
    mSet<-Normalization(mSet, "NULL", "NULL", "AutoNorm", ratio=FALSE, ratioNum=20)
    mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
    mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
    mSet<-SetMetabolomeFilter(mSet, F);
    mSet<-SetCurrentMsetLib(mSet, "kegg_pathway_new", 2);
    mSet<-CalculateGlobalTestScore(mSet)
```

I found that because I am setting to KEGG enrichment, the function ends in this line: https://github.com/xia-lab/MetaboAnalystR/blob/f603a5643f7627845db31793979f8ccf74ab638c/R/enrich_stats.R#L226 before the object file is saved: 

https://github.com/xia-lab/MetaboAnalystR/blob/f603a5643f7627845db31793979f8ccf74ab638c/R/enrich_stats.R#L272

so, then fails when try to read it:

https://github.com/xia-lab/MetaboAnalystR/blob/acd6e6c8582ad07a7277a00cd537461ba7867ebc/R/general_misc_utils.R#L78

Probably I am setting something wrong?

Thanks! Appreciate any help :)

**Comment by xia-lab** [comment]
Closed due to inactivity.
