### ISSUE TITLE
modifying MetaboAnalystR plots with ggplot2 theme to adjust font, background , colours etc.

### ISSUE THREAD

**Issue by saifsikdar** [xia-lab/MetaboAnalystR#145]
Hi @jsychong,

Thank you all for developing this nice R package and web version for metabolomic data analysis. I have found some interesting data using this platform. Now I would like to modify the theme of some graphs such as plot generated by PlotPCA2DScore(). Could you please let me know if it is possible to use ggplot2 to modify the MetaboAnalystR graphs and an example of how to do this? Or, any easy alternative to change the background theme, colour and fonts of the MetaboAnalystR graphs?

I look forward to hearing your suggestions.

Thanks,

Saif

**Comment by DoraCChen** [comment]
Hi, I had the same question and was wondering if there were any updates to this query.
