### ISSUE TITLE
Erreur : Could not connect to database:

### ISSUE THREAD

**Issue by PFRoux** [xia-lab/MetaboAnalystR#147]
Hello !

First of all thanks a lot for this amazing tool.

I am using it for months now without any issue, but I am experiencing database connection problem for a while now (see below).

Could you please help me fix this ?

Please not that I am having the issue with PerformIntegGeneMapping() only, not with PerformIntegCmpdMapping().

```
mSet<-PerformIntegGeneMapping(mSet, geneList, idType = "symbol", org = "hsa")
Erreur : Could not connect to database:
unable to open database file
```

Thanks a lot for your help.

Best,

**Comment by yzhao80** [comment]
I am having the same issue: could not connect to database when using "PerformnGeneMapping()", but no problem with PerformCmpdMapping(). I am not sure if it's related to I have downloaded the "compound_db.qs" file in my folder. But it seems I never read in this compound database file in my code. Have you found a solution?

**Comment by shouguog** [comment]
Have you got a solution?

**Comment by biodavidjm** [comment]
Is there a solution for this issue? I have the same problem

**Comment by biodavidjm** [comment]
Let me provide more details to help you debugging the issue:

Given this list of genes:

```
str(geneList)
 chr [1:56] "POLQ" "NDUFB4" "PRDX2" "MGST3" "DGLUCY" "NDUFAF1" "AIFM1" "PDHX" "ATP5MC1" "NDUFA12" "MRPL38"...
 ```
 and following these steps:

 ```
mSet<-InitDataObjects("conc", "pathinteg", FALSE)
mSet<-SetOrganism(mSet, "hsa")
mSet<-Setup.MapData(mSet, geneList)
mSet<-PerformGeneMapping(mSetObj = mSet, geneIDs = geneList, org = "hsa", idType = "symbol");
 ```

I got this error:

```
mSet<-PerformGeneMapping(mSetObj = mSet, geneIDs = geneList, org = "hsa", idType = "symbol");

Error: Could not connect to database:
unable to open database file
```

however, performing the compound mapping works:
```
mSet<-PerformCmpdMapping(mSetObj = mSet, cmpdIDs = cmpdList, org = "hsa", idType = "kegg");

[1] "Loaded files from MetaboAnalyst web-server."
[1] "1"                                                                              
[2] "Name matching OK, please inspect (and manual correct) the results then proceed."
```

What are we doing wrong?

Thanks a lot!

**Comment by Zhiqiang-PANG** [comment]
This issue is related to the remote api server. It has been fixed. I am closing it.
