### ISSUE TITLE
Retrieving metabolite libraries: how?

### ISSUE THREAD

**Issue by Benfeitas** [xia-lab/MetaboAnalystR#148]
Is it possible to retrieve full metabolite sets? In the FAQs it is mentioned `Each metabolite set will have an associated source (Database links, PubMed ID, etc) to help users further track down the original source of the information. Please click the "Browse Metabolite Set Libraries" button at the Home page to view all the informations.`. But I cannot find this in the web interface, nor can see how to retrieve them from R for instance.

I'd like to get the full metabolite sets for: metabolite name  vs  pathway, pubchem_id vs pathway, kegg_id vs pathway, etc.

Thank you advance

**Comment by Zhiqiang-PANG** [comment]
If you still need them, please post it here: https://omicsforum.ca/c/metaboanalyst/5
