### ISSUE TITLE
Error with PlotSubHeatMap command

### ISSUE THREAD

**Issue by wynstep** [xia-lab/MetaboAnalystR#149]
Hello, I am reporting an error that happen on MetaboAnalyst R (latest available version).

When launching the ** PlotSubHeatMap** command:
`mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "overview", T, T, NULL, T, F)` --> No error
`mSet<-PlotSubHeatMap(mSet, "heatmap_1_", "png", 72, width=NA, "norm", "row", "euclidean", "ward.D","bwm", "tanova", 25, "overview", T, T, T, F)` --> I obtain the following error:

`[1] "A total of 818 significant features were found."
Error in seq.default(-m, m, length.out = n + 1) : 
  'from' must be a finite number
In addition: Warning messages:
1: In min(x, na.rm = T) : no non-missing arguments to min; returning Inf
2: In max(x, na.rm = T) : no non-missing arguments to max; returning -Inf`

Could you please help?

**Comment by xlhd19980327** [comment]
Long time ago this issue exisits but there is no reply about it...

**Comment by Zhiqiang-PANG** [comment]
If this issue still exists, please post here [https://omicsforum.ca/c/metaboanalyst/5](url) with an reproducible example.
