### ISSUE TITLE
Failed to connect to api.xialab.ca port 80: Connection refused

### ISSUE THREAD

**Issue by kmosi0** [xia-lab/MetaboAnalystR#150]
Can't connect to api when  I  do Enrichment analysis. Here is my code below, anyone get this error too?  Wish for you reply. Thank for your reply.

```
library(MetaboAnalystR)
mSet<-InitDataObjects("conc", "msetora", FALSE)
cmpd.vec<-c("C00021","C17867","C19910","C21833")
mSet<-Setup.MapData(mSet, cmpd.vec);
mSet<-CrossReferencing(mSet, "kegg");
mSet<-CreateMappingResultTable(mSet)
mSet<-SetMetabolomeFilter(mSet, F);
mSet<-SetCurrentMsetLib(mSet, "kegg_pathway", 2);
mSet<-CalculateHyperScore(mSet)
[1] "Loaded files from MetaboAnalyst web-server."
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to api.xialab.ca port 80: Connection refused
```

**Comment by xlhd19980327** [comment]
So in which step you get the error? I met the similar error in enrichment analysis.

**Comment by fmarzetta** [comment]
Hi,
I also get this error when running CalculateOraScore(). I am using MetaboAnalystR version 3.0.3.
Many thanks in advance for your help.

```
mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
[1] "Loaded files from MetaboAnalyst web-server."
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to api.xialab.ca port 80: Connection refused
```

**Comment by xlhd19980327** [comment]
> Hi,
> I also get this error when running CalculateOraScore(). I am using MetaboAnalystR version 3.0.3.
> Many thanks in advance for your help.
> 
> ```
> mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
> [1] "Loaded files from MetaboAnalyst web-server."
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Failed to connect to api.xialab.ca port 80: Connection refused
> ```

Did you get any error when runing the CrossReferencing() function?

**Comment by fmarzetta** [comment]
> > Hi,
> > I also get this error when running CalculateOraScore(). I am using MetaboAnalystR version 3.0.3.
> > Many thanks in advance for your help.
> > ```
> > mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
> > [1] "Loaded files from MetaboAnalyst web-server."
> > Error in curl::curl_fetch_memory(url, handle = handle) : 
> >   Failed to connect to api.xialab.ca port 80: Connection refused
> > ```
> 
> Did you get any error when runing the CrossReferencing() function?

Yes, I initially had an error with version 3.0.0. CrossReferencing() was failing with q.type="name", while it was working when choosing other query types. 
```
mSet<-CrossReferencing(mSet, "name")
```
The issue seems to be fixed in v.3.0.3.

**Comment by xlhd19980327** [comment]
> > > Hi,
> > > I also get this error when running CalculateOraScore(). I am using MetaboAnalystR version 3.0.3.
> > > Many thanks in advance for your help.
> > > ```
> > > mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
> > > [1] "Loaded files from MetaboAnalyst web-server."
> > > Error in curl::curl_fetch_memory(url, handle = handle) : 
> > >   Failed to connect to api.xialab.ca port 80: Connection refused
> > > ```
> > 
> > 
> > Did you get any error when runing the CrossReferencing() function?
> 
> Yes, I initially had an error with version 3.0.0. CrossReferencing() was failing with q.type="name", while it was working when choosing other query types.
> 
> ```
> mSet<-CrossReferencing(mSet, "name")
> ```
> 
> The issue seems to be fixed in v.3.0.3.

You do? That's interesting. No matter what I choose the query type, I get the similar http error.
I search for its original code. The script will first download the rds file with this code(of any query type you choose):
>lib.url <- paste("https://www.metaboanalyst.ca/resources/libs/", "compound_db.rds", sep = "")
>download.file(lib.url, destfile = filenm, method = "curl")

That means the script will download the rds file in the url(https://www.metaboanalyst.ca/resources/libs/compound_db.rds). 
And then if you choose "name" type , it will using the similar code and download another rds file with url(https://www.metaboanalyst.ca/resources/libs/syn_nms.rds). But unfortunately, I failed to download the first rds file in the first step. And I visited the url in the browser and get 404(Not found) error code, which means the requested resource cannot be found by the server. 

So I really wonder why you can go through the first step(i.e. working well when choosing other query types). I suspect that the resource in that server move to a different location.

**Comment by xlhd19980327** [comment]
I wish the author can read this thread and fix the issue. Otherwise, we really can NOT use the enrichment function locally with the R package.

**Comment by xlhd19980327** [comment]
> > > Hi,
> > > I also get this error when running CalculateOraScore(). I am using MetaboAnalystR version 3.0.3.
> > > Many thanks in advance for your help.
> > > ```
> > > mSet<-CalculateOraScore(mSet, "rbc", "hyperg")
> > > [1] "Loaded files from MetaboAnalyst web-server."
> > > Error in curl::curl_fetch_memory(url, handle = handle) : 
> > >   Failed to connect to api.xialab.ca port 80: Connection refused
> > > ```
> > 
> > 
> > Did you get any error when runing the CrossReferencing() function?
> 
> Yes, I initially had an error with version 3.0.0. CrossReferencing() was failing with q.type="name", while it was working when choosing other query types.
> 
> ```
> mSet<-CrossReferencing(mSet, "name")
> ```
> 
> The issue seems to be fixed in v.3.0.3.

My version is also 3.0.3 but cannot request the resource.

**Comment by mathiaskalxdorf** [comment]
Same issue here with version 3.0.3 since few days. When running 
mSet<-CalculateHyperScore(mSetObj = mSet)
I get the error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to api.xialab.ca port 80: Connection refused
All lines above meaning e.g. CrossReferencing() works without problems.

**Comment by xlhd19980327** [comment]
> Same issue here with version 3.0.3 since few days. When running
> mSet<-CalculateHyperScore(mSetObj = mSet)
> I get the error:
> Error in curl::curl_fetch_memory(url, handle = handle) :
> Failed to connect to api.xialab.ca port 80: Connection refused
> All lines above meaning e.g. CrossReferencing() works without problems.

Are you in China? I suspect the Wall may block some feature.

**Comment by mathiaskalxdorf** [comment]
> 
> 
> > Same issue here with version 3.0.3 since few days. When running
> > mSet<-CalculateHyperScore(mSetObj = mSet)
> > I get the error:
> > Error in curl::curl_fetch_memory(url, handle = handle) :
> > Failed to connect to api.xialab.ca port 80: Connection refused
> > All lines above meaning e.g. CrossReferencing() works without problems.
> 
> Are you in China? I suspect the Wall may block some feature.

No I´m located in Germany. Functions were working for me without problems until few days ago.

**Comment by kmosi0** [comment]
> 
> 
> > > Same issue here with version 3.0.3 since few days. When running
> > > mSet<-CalculateHyperScore(mSetObj = mSet)
> > > I get the error:
> > > Error in curl::curl_fetch_memory(url, handle = handle) :
> > > Failed to connect to api.xialab.ca port 80: Connection refused
> > > All lines above meaning e.g. CrossReferencing() works without problems.
> > 
> > 
> > Are you in China? I suspect the Wall may block some feature.
> 
> No I´m located in Germany. Functions were working for me without problems until few days ago.
Those function work well in web of MetaboAnalyst, but cant't be used in local R package. maybe some problem occurs in api. hope the author fixes this problem.
