### ISSUE TITLE
lipids analysis in the Enrichment Analysis module Error

### ISSUE THREAD

**Issue by xlhd19980327** [xia-lab/MetaboAnalystR#151]
You upgrade your lipid analysis in your web server. But I found something wrong in over representation analysis. I uploaded my lipid data in your website. I found in name assigning step(name check step), there is no issue. But in next setting parameter step(choosing database), when I choose the option of "Pathway based" or "Disease signatures" or  "Other types" database, it will show the error message:
 
```
Possible causes of error (last one being the most relevant):
No match was found to the selected metabolite set library!
```

Even if I use your example data, selecting the  "Pathway based" or "Disease signatures" database will also occur an error. I wonder if the lipid analysis cannot handle these database above enrichment or with some missing function now.

Looking for your reply!

**Comment by xia-lab** [comment]
This is expected - as most libraries don't contain lipids. Please try those databases that do contain lipids indicated with ".. **lipid sets**"
