### ISSUE TITLE
Data after CalculateGlobalTestScore is scrambled

### ISSUE THREAD

**Issue by synthbiont** [xia-lab/MetaboAnalystR#152]
Hello, I am running a quantitative enrichment analysis for a dataset with ~90 metabolites and 4 groups (concentrations of a stimulator; 1, 2, 3 and 4 micromolar).

All the data reading, filtering and normalization goes without any problem. After preforming the quantitative enrichment analysis I am doing some plots for specific sets:

`mSet<-SetMetabolomeFilter(mSet, F);`
`mSet<-SetCurrentMsetLib(mSet, "smpdb_pathway", 2);`
`mSet<-CalculateGlobalTestScore(mSet)`
`mSet<-PlotQEA.Overview(mSet, "qea_0_", "net", "png", 72, width=NA)`
`mSet<-PlotEnrichDotPlot(mSet, "qea", "qea_dot_0_", "png", 72, width=NA)`
`mSet<-PlotQEA.MetSet(mSet, "Purine Metabolism", "png", 72, width=NA)`

Here is the image that I obtain:

![PurineMetabolismdpi72](https://user-images.githubusercontent.com/16675137/100904713-905bbe80-34c7-11eb-8259-28d01e44849a.png)

If I compare the data shown in this figure with the data obtained after normalization, it does not match. For example, for the metabolite Hipoxanthine, this is what is stored in `mSet$analSet$msea.data`:

![image](https://user-images.githubusercontent.com/16675137/100904815-af5a5080-34c7-11eb-998f-244d2f6f7fcb.png)

It is clear that the range of variation of this metabolite is between -12 and +14, while in the figure previously shown it only changes between -5 and +5. If I plot the data myself, I obtain this box plot...

![image](https://user-images.githubusercontent.com/16675137/100902953-abc5ca00-34c5-11eb-8bbd-9dfe67f4ad83.png)

... that looks very similar to the one shown in column 2 row 2 of the output figure of `PlotQEA.MetSet` (picture above), which is labelled (incorrectly?) as Adenosine.

This type of permutation between label and plot is all over the figure:

- L-Glutamine data plotted as L-Aspartic acid
- L-Aspartic acid data plotted as Adenine
- Adenine data plotted as Ribose-1-phosphate)
- ...

~~I suspect, based on the p-values of metabolites that clearly have significant difference over time, that the issue is not in the plotting but in the function `CalculateGlobalTestScore`, either on the `.prepare.globaltest.score(mSetObj)` function or in `.perform.computing()`~~

Attached is a script reproducing this issue (with the dataset used).

[example_bug_qmea.zip](https://github.com/xia-lab/MetaboAnalystR/files/5630651/example_bug_qmea.zip)

**Comment by synthbiont** [comment]
After comparing all the plots of the figure generated using `PlotQEA.MetSet`, this is what the box plots are really showing:

| col1            | col2          | col3      | col4               |
|-----------------|---------------|-----------|--------------------|
| Adenine         | Adenosine     | Fumarate  | Guanine            |
| Guanosine       | Hypoxahnthine | Inosine   | L-Aspartic acid    |
| L-Glutamic acid | L-Glutamine   | Phosphate | Ribose-1-phosphate |

Metabolites seem to be organized in alphabetic order, even though neither in my dataset nor in the metabolite sets I am using the metabolites are organized that way. Maybe a step in `PlotQEA.MetSet` is causing this?

I also verified the p-values and those are ok. Thus, I really think it is an issue in the plotting.

**Comment by xlhd19980327** [comment]
> After comparing all the subplots of the figure generated using `PlotQEA.MetSet` that I included in the previous post, this is the data that they are really showing:
> 
> col1	col2	col3	col4
> Adenine	Adenosine	Fumarate	Guanine
> Guanosine	Hypoxahnthine	Inosine	L-Aspartic acid
> L-Glutamic acid	L-Glutamine	Phosphate	Ribose-1-phosphate
> Metabolites seem to be organized in alphabetic order, even though neither in my dataset nor in the metabolite sets I am using the metabolites are organized that way. Maybe a step in `PlotQEA.MetSet` is causing this?
> 
> I also verified the p-values and those are ok (I modified a metabolite to not have any change accross my 4 groups, and indeed I have a p-value of 1). Thus, I really think it is an issue in the plotting.

I wonder if you are the member in xia-lab? I found they quickly went through your pull request but no one fixed the bug we uploaded several days ago.

**Comment by synthbiont** [comment]
I am not a member of the xia-lab. I decided to try to fix the issue myself, and that is why I opened the pull request you already saw with the fix I propose. Let's see if they approve it.

For now, I just created a modified version of the `PlotQEA.MetSet` function that I load every time that I run my script and that works as I want.

**Comment by xia-lab** [comment]
Accepted with appreciation
