### ISSUE TITLE
Installation isntruction should be updated

### ISSUE THREAD

**Issue by xlhd19980327** [xia-lab/MetaboAnalystR#154]
Instruction of the installartion is very old and the source code has many bugs(at least enrichment function will cause issue, see #150 And some new feature may not update in old version). So I think the instruction should change a lot.

Here is some solution:

In step two, using option A) or B) to install the main package and its dependencies. But when you start to compile the package you will get many errors about missing required packages, eg.

> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘ctc’

So you should install these packages in your R library first. Do not use `install.package()` command, cuz they  are all bioconductor packages. Using the following code will go through the compile:

> BiocManager::install("ctc")
> BiocManager::install("glasso")
> BiocManager::install("huge")
> BiocManager::install("ppcor")

After installing these packages, you will successfully install the latest version of MetaboAnalystR. And many issue may be fixed in this way(eg. #150).

**Comment by Leo-Guan-git** [comment]
One more needed, all in all: 
> BiocManager::install(c('ctc','glasso','huge','ppcor','plotly'))
