### ISSUE TITLE
Question of MetaboAnalyst‘s KEGG database

### ISSUE THREAD

**Issue by leump** [xia-lab/MetaboAnalystR#155]
Hello,

When using the package, We found that the KEGG database in MetaboAnalyst does not match the compound data in the KEGG database (hsa). What are MetaboAnalyst's screening criteria for metabolic pathways and metabolites in the KEGG database?

Thank you. 
Best regards, 
Leump

**Comment by leump** [comment]
[Uploading different_compound.xlsx…]()

**Comment by leump** [comment]
[different_compound.xlsx](https://github.com/xia-lab/MetaboAnalystR/files/5656557/different_compound.xlsx)

**Comment by xlhd19980327** [comment]
> [different_compound.xlsx](https://github.com/xia-lab/MetaboAnalystR/files/5656557/different_compound.xlsx)

This sheet is what you have organized for the unmatching metabolites in the metabolic pathways, isn't it?

**Comment by leump** [comment]
yes

xlhd19980327 <notifications@github.com> 于2020年12月8日周二 下午2:36写道：

**Comment by synthbiont** [comment]
Indeed I have the same problem, but with SMPDB. For example, I run a pathway enrichment analysis with a list of metabolites that includes L-glutamine (HMDB0000641). One of the hits I obtain is the pathway **Warburg effect** ([SMP0000654](https://smpdb.ca/view/SMP0000654)). Glutamine is involved in the pathway, but when I run CalculateQeaScore I don't get any hit for glutamine in that pathway.

**Comment by synthbiont** [comment]
I can also confirm now that the if I use KEGG for the pathway enrichment analysis, the hsa.qs [file downloaded](https://www.metaboanalyst.ca/resources/libs/kegg/metpa/hsa.qs) contains data about KEGG pathways that is missing some metabolites.

For example, the metabolite pathway hsa00240 (Pyrimidine metabolism) of the KEGG database contains the metabolite Cytosine (C00380). However, when I check the mset.list variable in the hsa.qs file, the pathway hsa00240 does not contain Cytosine.

I would also like to know what is the criteria to not include those metabolites.
