### ISSUE TITLE
can not iinstall the package from GitHub

### ISSUE THREAD

**Issue by lixiang117423** [xia-lab/MetaboAnalystR#156]
Hi Guys,
I was trying ti install the package from GitHub, but I failed.
This is the info on the Console:
'unable to open URL'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6/PACKAGES'

So, what should I do to get the issue?

Thanks!

**Comment by synthbiont** [comment]
Maybe you can try what is suggested in [this link](https://stackoverflow.com/questions/45108484/warning-unable-to-access-index-for-repository-https-www-stats-ox-ac-uk-pub-rw)?

I had the same issue when installing MetaboAnalystR (Windows set-up), and I recalled I solved those issues either by deactivating CRAN Extra, or by forcing the installation of required packages using Bioconductor/BiocManager.

**Comment by candidosobrinhosa** [comment]
Dear colleague, you are using a R 3.6. Have you tried updating to 4.0? I cannot confirm 100% but:

1) probably you're attempting to install a binary package (instead from source), and the binary may not be available anymore?
2) or there may have conflict dependencies between your R (3.6) version and the available packages (requires >=4.0).

I installed 3 weeks ago in Ubuntu, forcing to install the dependencies with BiocManager::install(c(""))

Best,
