### ISSUE TITLE
MSEA using kegg_pathway not generating dat.in.qs

### ISSUE THREAD

**Issue by synthbiont** [xia-lab/MetaboAnalystR#157]
I am having problems running the function `CalculateGlobalTestScore` if I define kegg_pathway as the set for analysis:

```
mSet <- SetCurrentMsetLib(mSet,
                          "kegg_pathway",
                          excludeNum = 2);
mSet <- CalculateGlobalTestScore(mSet)
```

When I run this, I get the following error:

```
Error in c_qread(file, use_alt_rep, strict, nthreads) : 
  Failed to open dat.in.qs. Check file path.
```

After some debugging, it seems the problem comes from the call to the function`.perform.computing(mSetObj)` in `CalculateGlobalTestScore`. This function tries to open the file **dat.in.qs**. However, this file does not exist because it is not generated in `.prepare.globaltest.score(mSetObj)` if I use kegg_pathway as set database. This is because in line 49 of the function `.prepare.globaltest.score` the mSetObj is returned, before creating any dat.in.qs file (which happens in line 88).

This problem does not happen when I use other sets, such as smpdb_pathway. This is because when I use that set, it does generate the dat.in.qs file, which means I don't get the error I mentioned above.

![image](https://user-images.githubusercontent.com/16675137/102214405-7fa04500-3ed8-11eb-9583-1ac0f08a0b36.png)

Regardless of the error that I obtain in `CalculateGlobalTestScore`, the results file msea_qea_result.csv is generated (line 45 in `.prepare.globaltest.score`).  However, I cannot run the functions PlotQEA.Overview or PlotEnrichDotPlot becase the mSet object does not contain the results of the MSEA.

**Comment by synthbiont** [comment]
A possible solution until this is addressed by the xia lab is to create your own version of `CalculateGlobalTestScore` in which the steps `.perform.computing()` and `.save.globaltest.score()` are skipped if you use kegg_pathway. This is because, as explained above, both the global test computation and saving the results in the .csv file seem to be already done in `.prepare.globaltest.score()` if you use this specific set.

An example of how this custom-made function looks like would be:

```
CalculateGlobalTestScore.Custom <- function (mSetObj = NA) 
{
  mSetObj <- MetaboAnalystR:::.get.mSet(mSetObj)
  if (MetaboAnalystR:::.on.public.web) {
    MetaboAnalystR:::.prepare.globaltest.score(mSetObj)
    MetaboAnalystR:::.perform.computing()
    MetaboAnalystR:::.save.globaltest.score(mSetObj)
    return(MetaboAnalystR:::.set.mSet(mSetObj))
  }
  else {
    mSetObj <- MetaboAnalystR:::.prepare.globaltest.score(mSetObj)
    if(mSetObj$analSet$msetlibname != "kegg_pathway") {
      MetaboAnalystR:::.perform.computing()
      mSetObj <- MetaboAnalystR:::.save.globaltest.score(mSetObj)
    }
  }
  return(MetaboAnalystR:::.set.mSet(mSetObj))
}
```

**Comment by xia-lab** [comment]
Thank you for the post. Indeed, the R package is designed to be compatible with the web flow so both can use the same code base. We are refining the design and will make this more intuitive in the version 4.0
