### ISSUE TITLE
Error in `*tmp*`$dataSet : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by YuanwenGuo** [xia-lab/MetaboAnalystR#16]
Hello!

I am trying to learn MetoboAnalystR using sample data your provided (lcms_netcdf.zip) on your website. However, when I input "mSet <- Read.MSspec(mSet, "upload", "bin", 30.0, 30.0)", R came up with the error message "Processing 3195 mz slices ... OK
Error in `*tmp*`$dataSet : $ operator is invalid for atomic vectors".

Could you please give me suggestions to deal with this issue? Any help will be appreciated!

Best,
Yuanwen

**Comment by jsychong** [comment]
Hi Yuanwen,

Could you please give me all the R commands you ran to get to that issue?

Thank you!
Jasmine

**Comment by YuanwenGuo** [comment]
Hello Jasmine,

Sorry for the late reply, I just saw your message.

Generally I just followed the sample scripts on the vignettes:
> mSet <- InitDataObjects("msspec", "stat", FALSE)
[1] "R objects intialized ..."
> mSet <- UnzipUploadedFile("lcms_netcdf.zip", "upload", rmFile=T)
> mSet <- Read.MSspec(mSet, "upload", "bin", 30.0, 30.0)
Processing 3195 mz slices ... OK
Error in `*tmp*`$dataSet : $ operator is invalid for atomic vectors
In addition: Warning messages:
1: package ‘xcms’ was built under R version 3.4.2 
2: package ‘Biobase’ was built under R version 3.4.2 
3: package ‘BiocGenerics’ was built under R version 3.4.2 
4: package ‘BiocParallel’ was built under R version 3.4.2 
5: package ‘mzR’ was built under R version 3.4.2 
6: package ‘Rcpp’ was built under R version 3.4.3 
7: In fun(libname, pkgname) :
  mzR has been built against a different Rcpp version (0.12.13)
than is installed on your system (0.12.15). This might lead to errors
when loading mzR. If you encounter such issues, please send a report,
including the output of sessionInfo() to the Bioc support forum at 
https://support.bioconductor.org/. For details see also
https://github.com/sneumann/mzR/wiki/mzR-Rcpp-compiler-linker-issue.
8: package ‘ProtGenerics’ was built under R version 3.4.2

I will much appreciate your suggestions!

Best,
Yuanwen

**Comment by OlleyShore** [comment]
I solved this problem by removing some unused packages based on the suggestions here:
https://stackoverflow.com/questions/23299684/r-error-in-xed-operator-is-invalid-for-atomic-vectors

**Comment by Zhiqiang-PANG** [comment]
I am closing this because all functions here are deprecated.
