### ISSUE TITLE
Can't download compound_db.rds when calling CrossReferencing method

### ISSUE THREAD

**Issue by danlessa** [xia-lab/MetaboAnalystR#163]
Hey, I'm using MetaboAnalystR 3.0.3 on a Ubuntu 20.10, and when I execute the CrossReferencing method, I get this error:

`mSet<-CrossReferencing(mSet, "hmdb");`
> [1] "Reading data unsuccessful, attempting to re-download file..."
> [1] "Loading files from server unsuccessful. Ensure curl is downloaded on your computer."
```
Error in .read.metaboanalyst.lib("compound_db.rds"): object 'my.lib' not found
Traceback:

1. CrossReferencing(mSet, "hmdb")
2. MetaboliteMappingExact(mSetObj, q.type)
3. .read.metaboanalyst.lib("compound_db.rds")
```

My curl is all set-up, and digging through the issues, I've found out that the link https://www.metaboanalyst.ca/resources/libs/compound_db.rds gives me a internal 404 error.

My feeling is that there is some problem with the default locations used by MetaboAnalystR for storing datasets. Maybe the resources were removed from the server?

**Comment by bowenli37** [comment]
You may want to update to the latest github version, which use .qs format for all the databases, like
https://www.metaboanalyst.ca/resources/libs/compound_db.qs

**Comment by xia-lab** [comment]
Solved as suggested
