### ISSUE TITLE
Functional analysis GSEA and Mummichog

### ISSUE THREAD

**Issue by vthaker** [xia-lab/MetaboAnalystR#164]
Cannot get the figure for the PlotIntegPaths for the joint analysis of GSEA and mummichog.

```
mSet<-InitDataObjects("mass_all", "mummichog", FALSE)
SetPeakFormat("rmp")
mSet<-UpdateInstrumentParameters(mSet, 5.0, "mixed", "yes", 0.02);
mSet<-Read.PeakListData(mSet, "/~oe_function1.txt");
mSet<-SanityCheckMummichogData(mSet)
mSet<-SetPeakEnrichMethod(mSet, "integ", "v2")
mSet<-SetMummichogPval(mSet, 1.0E-5)
mSet<-PerformPSEA(mSet, "hsa_mfn", "current", 100)
mSet<-PlotIntegPaths(mSet, "integ_peaks_0_", "png", 72, width=NA)
```
`Error in symbols(x, y, add = TRUE, inches = F, circles = radi.vec, bg = bg.vec,  : 
  invalid symbol parameter`

How can this be fixed? Thank you

**Comment by Zhiqiang-PANG** [comment]
Please update this with a reproducible example. I am closing this issue, please post to: https://omicsforum.ca/c/metaboanalyst/5
