### ISSUE TITLE
class_compound_db_2020.qs is not available on the metaboanalyst.ca website

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#165]
When I was doing enrichment analysis, an error occurred due to missing file "class_compound_db_2020.qs". It was not found at this url "https://www.metaboanalyst.ca/resources/libs/class_compound_db_2020.qs". 

Please advise @Zhiqiang-PANG. Thank you very much.

    mSet<-CalculateHyperScore(mSet)
        ## inside CalculateHyperScore
        nm.map <- GetFinalNameMap(mSetObj)
           ## inside GetFinalNameMap
            cmpd.db <- .get.my.lib("class_compound_db_2020.qs")
                ## inside .get.my.ib
                ## lib.url="https://www.metaboanalyst.ca/resources/libs/class_compound_db_2020.qs"
                download.file(lib.url, destfile = filenm, method = "curl")

**Comment by Zhiqiang-PANG** [comment]
Thanks @bowenli37 , this issue have been fixed. Please have a try.

**Comment by S-KD** [comment]
@Zhiqiang-PANG today, I also get an error in `cmpd.db <- .get.my.lib("class_compound_db_2020.qs")`
In my case, MetaboanalystR v3.0.3 downloaded class_compound_db_2020.qs (a 2 KB) file in my working directory but was unable to read it with the following error
`my.lib <- qs::qread(lib.path)
Error in c_qread(file, use_alt_rep, strict, nthreads) : 
QS format not detected`

Please help thanks.

**Comment by bowenli37** [comment]
@S-KD update to the latest commit, which use https://www.metaboanalyst.ca/resources/libs/master_compound_db.qs instead. download.file() always fails on my computer, so I normally just download from a browser。
