### ISSUE TITLE
SetPeakParam is declared twice (OptiLCMS reference incorrectly takes precedence)

### ISSUE THREAD

**Issue by tew42** [xia-lab/MetaboAnalystR#166]
Hi @Zhiqiang-PANG,

The function SetPeakParam() is not absolutely required, but certainly useful for running PerformParamsOptimization (it's even suggested if the parameters are missing). Unfortunately, it's declared twice:

For the purposes of properly running this package, _the "correct" SetPeakParam is found in parameters_db.R_ . I ended up just using the code found there to manually construct a peak parameter object.

However, **SetPeakParam declared in the recently-added spectra_processing.R unfortunately takes precedence**, introducing a dependence on OptiLCMS . While I imagine outsourcing optimization etc. into OptiLCMS is a good thing long-term (see also #167), this isn't cohesively implemented in MetaboAnalystR yet. E.g. in the present case, the output format of OptiLCMS::SetPeakParam is somewhat different from what the MetaboAnalystR::PerformParamsOptimization expects.

**Comment by Zhiqiang-PANG** [comment]
Hi @tew42 , thanks for your feedback. OptiLCMS is designed to replaced the raw spectra processing component in MetaboAnalystR, but work together with MetaboAnalystR. Now you have a duplicate functions if you install both, everything will be organized this week.
