### ISSUE TITLE
parameters_optimization.R fails due to calcGaussianS always returning 0

### ISSUE THREAD

**Issue by tew42** [xia-lab/MetaboAnalystR#167]
Hi @Zhiqiang-PANG ,
when attempting parameter optimization on my data, the algorithm fails due to calcGaussianS() returning 0 for all conditions (thus, due to multiplication of GaussianSI, also leading to QS = 0)...
This is already fixed in the OptiLCMS implementation (and thus I didn't try tracking down the issue further), but I thought I'd still leave a bug report here for others who are attempting to run the existing MetaboAnalystR code.

**Comment by Zhiqiang-PANG** [comment]
Hi @tew42 , yes this is a known issue, will be solved by integrating MetaboAnalystR with OptiLCMS. Thanks
