### ISSUE TITLE
q.size in CalculateOraScore and CalculateHyperScore

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#168]
In function CalculateOraScore

```
  if (mSetObj$dataSet$use.metabo.filter && !is.null(mSetObj$dataSet$metabo.filter.kegg)) {
    current.mset <- lapply(current.mset, function(x) {
      x[x %in% mSetObj$dataSet$metabo.filter.kegg]
    })
    mSetObj$analSet$ora.filtered.mset <- current.mset
    uniq.count <- length(unique(unlist(current.mset, use.names = FALSE)))
  }
```

In function CalculateHyperScore, the corresponding block
```
  if (mSetObj$dataSet$use.metabo.filter && !is.null(mSetObj$dataSet$metabo.filter.hmdb)) {
    current.mset <- lapply(current.mset, function(x) {
      x[x %in% mSetObj$dataSet$metabo.filter.hmdb]
    })
    mSetObj$dataSet$filtered.mset <- current.mset
    ora.vec <- ora.vec[ora.vec %in% unique(unlist(current.mset, 
                                                  use.names = FALSE))]
    q.size <- length(ora.vec)
  }
```

ora.vec should be limited to the metabolites in the current.mset. Metabolites not included in current.mset should be removed, and q.size should be updated accordingly. This should take place regardless of whether metabolome filter is to be applied.

**Comment by cailing20** [comment]
Hi @jsychong and @xia-lab, @bowenli37 first found a bug in issue #34, then I posted issue #96, plus this issue from @bowenli37, we have reported the problem three times for this function. Lots of people use this function for pathway analysis and are reporting incorrect results in their papers. Could you please look into these issues and address them? Thank you.

**Comment by jessica-ewald** [comment]
This was fixed, see: https://omicsforum.ca/t/use-all-compounds-in-the-selected-pathway-library-is-a-misleading-option-for-reference-metabolome/832
