### ISSUE TITLE
mSetObj$analSet$msetlibname is not set in function CalculateHyperScore

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#169]
In SetCurrentMsetLib, mSetObj$api$libname is set when kegg_pathway is used.

```
    if ( !.on.public.web & grepl("kegg", libname)) {
      mSetObj$api$libname <- libname
      mSetObj$api$excludeNum = excludeNum
      return(.set.mSet(mSetObj))
    }
```

In that situation, mSetObj$analSet$msetlibname does not exist, but CalculateHyperScore tries to access it.
```
if (!.on.public.web & grepl("kegg", mSetObj$analSet$msetlibname)) {
    mSetObj$api$oraVec <- ora.vec
```

mSetObj$analSet$msetlibname can be changed to mSetObj$api$libname

**Comment by xia-lab** [comment]
Thanks - now both mSetObj$analSet$msetlibname and mSetObj$api$libname are updated during library selection
