### ISSUE TITLE
Dendrogram variables

### ISSUE THREAD

**Issue by susheelbhanu** [xia-lab/MetaboAnalystR#17]
Hi, 

This isn't an issue per se, but I have a dendrogram that splits my samples into 2 groups at the root. Is there any way to determine which features/variables are causing this split? 

That is, if I have a table with 100 features, and 8 samples per group, my table is set up with samples as columns. Is there a function or code, that will tell me which features are contributing to the split in the dendrogram. I'm running the clustering analysis using Euclidean and Wards. 

Thank you,
Susheel

**Comment by susheelbhanu** [comment]
Hey @jessica-ewald would still be useful to have this information before closing the issue 😉.

Thanks for a great tool though

**Comment by jessica-ewald** [comment]
Hi @susheelbhanu - sorry, we are going through all open Issues in preparation for releasing a new version and trying to clean things up :) 

I'm not aware that it's possible to do this - if you find some code that can do this, we might be able to integrate into MetaboAnalystR.

**Comment by susheelbhanu** [comment]
Sure thing, thanks. Looking forward to the new version then!
