### ISSUE TITLE
compound name not in smpdb_pathway

### ISSUE THREAD

**Issue by RPGraciotti** [xia-lab/MetaboAnalystR#170]
When doing an enrichment analysis, after calling 

`SetCurrentMsetLib(mSetObj = mSet, libname = "smpdb_pathway", excludeNum = 2)`

downloading the database and setting the current.msetlib object, some compound names are not present in any pathway of that object, such as PC(16:0/18:2(9Z,12Z)) (HMDB0007973) even though such compound is present in smpdb database: https://smpdb.ca/search?q=HMDB0007973. 

```
> grep(pattern = "PC(16:0/18:2(9Z,12Z))", x = current.msetlib)
integer(0)
```

Is it possible that the https://www.metaboanalyst.ca/resources/libs/msets/smpdb_pathway.qs is outdated?

**Comment by bowenli37** [comment]
smpdb_pathway library has 99 metabolite sets and doesn't include any lipid pathways. One reason for that is entire SMPDB is too big and MetaboAnalystR on the local computer has to download the database, which will take an unreasonable amount of time. Only class-based enrichment is possible at the moment.

**Comment by RPGraciotti** [comment]
Thank you @bowenli37 !

I actually tried to perform an enrichment analysis in the web app by selecting the "sub-class" under Chemical Structures tab, and replicated the 

`mSet<-SetCurrentMsetLib(mSet, "sub_class", 2)`

in MetaboAnalystR, and it worked. Is that correct?

**Comment by bowenli37** [comment]
Yes. For lipid enrichment analysis, super-class, main-class, and sub-class works.

**Comment by RPGraciotti** [comment]
Thank you again @bowenli37,

I beg your pardon as I'm not familiarized with such processes, what exactly is the difference between those databanks "super-class", "main-class" and "sub-class"? Do they yeld very different results depending on which one you selected, or isn't that much of a difference?

**Comment by bowenli37** [comment]
@RPGraciotti There is a hierarchical classification system for lipids. I suppose "super-class", "main-class" and "sub-class" are adopted from HMDB. There is a Lipidmaps classification system that is most widely used. You may want to check the actual data in the lipid_compound_db.qs file (https://www.metaboanalyst.ca/resources/libs/lipid_compound_db.qs). Use qs::qread in R to read it.
