### ISSUE TITLE
qs::qread encoding in SetCurrentMsetLib

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#172]
Hi @Zhiqiang-PANG ,

qs::qread doesn't set the default encoding to UTF8, so some characters can not be mapped correctly in Windows OS. For example in Chinese locale, I saw the following warning and the resulting list element is NA.

```
Warning messages:
1: In strsplit(current.msetlib[, 3], "; ", fixed = TRUE) :
  输入的字符串2不适用于此语言环境
2: In strsplit(current.msetlib[, 3], "; ", fixed = TRUE) :
  输入的字符串11不适用于此语言环境
3: In strsplit(current.msetlib[, 3], "; ", fixed = TRUE) :
  输入的字符串26不适用于此语言环境
```

I use iconv to do the trick.

```
ms.list <- strsplit(
      iconv(current.msetlib[, 3], from = 'utf8', to = 'utf8'),
      "; ", fixed = TRUE)
```

**Comment by xia-lab** [comment]
Thank you for the note. It is updated in MetaboAnalystR 4.0 to be released soon
