### ISSUE TITLE
ERROR: package installation failed

### ISSUE THREAD

**Issue by KOscripts** [xia-lab/MetaboAnalystR#173]
Attempted installation using the function method, build fails, Using Debian 10, R version 3.6.3 but I get the same error with the latest version of R as well. There is some package that is required  ,"ctc", but it is not installed(or installed properly) by the installation method you describe in your instructions. How to resolve this issue?

  installing to /tmp/RtmpFs0CAu/Rinst6ea45a894c61/00LOCK-MetaboAnalystR/00new/MetaboAnalystR/libs
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
     there is no package called ‘ctc’
   Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
   Execution halted
   ERROR: lazy loading failed for package ‘MetaboAnalystR’
─  removing ‘/tmp/RtmpFs0CAu/Rinst6ea45a894c61/MetaboAnalystR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'MetaboAnalystR' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
E>   there is no package called ‘ctc’
E> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
E> Execution halted
E> ERROR: lazy loading failed for package ‘MetaboAnalystR’
E> * removing ‘/tmp/RtmpFs0CAu/Rinst6ea45a894c61/MetaboAnalystR’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by bowenli37** [comment]
You can manually install the required packages using install.packages() or BiocManager::install()
```
BiocManager::install('ctc')
```

**Comment by moutazhelal** [comment]
Hello @KOscripts , 

I am having the same exact error in installing the package. did you manage to solve it ?

Regards,
Moutaz

**Comment by moutazhelal** [comment]
@KOscripts  Solved in this issue 
https://github.com/xia-lab/MetaboAnalystR/issues/132#issuecomment-698858999
