### ISSUE TITLE
compound_db.qs and syn_nms.qs are inconsistent

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#175]
There are 19835 records in compound_db.qs, but there are 19837 records in syn_nms.qs.

These 2 databases are different at 7247 10465 10466 10467 10490 17347 and from 19018 to the end.

Besides, there are many names that are incorrect, as shown in the screenshot

![图片](https://user-images.githubusercontent.com/2127513/106433838-ad9f1000-64ab-11eb-8ca6-cb7618c65a3a.png)

@Zhiqiang-PANG

**Comment by xia-lab** [comment]
To be addressed with the new HMDB release
