### ISSUE TITLE
CrossReferencing and CreateMappingResultTable use different database

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#176]
In MSEA analysis, CrossReferencing function loads compound_db.qs, but CreateMappingResultTable loads master_compound_db.qs.

cmpd.db <- .get.my.lib("compound_db.qs")
mSetObj$name.map$query.vec <- qvec
mSetObj$name.map$hit.inx <- hit.inx
mSetObj$name.map$hit.values <- match.values
mSetObj$name.map$match.state <- match.state

cmpd.db <- .get.my.lib("master_compound_db.qs")

**Comment by bowenli37** [comment]
In function CrossReferencing and CreateMappingResultTable, the same database must be used. The logic in MetaboliteMappingExact  is correct.

```
  if(anal.type %in% c("msetora", "msetssp", "msetqea") & lipid){
    cmpd.db <- .get.my.lib("lipid_compound_db.qs");
  }else if(anal.type == "utils"){
    cmpd.db <- .get.my.lib("master_compound_db.qs");
  }else{
    cmpd.db <- .get.my.lib("compound_db.qs");
  }
```

**Comment by bowenli37** [comment]
GetFinalNameMap also load "master_compound_db.qs" and returns wrong nm.mat (column hmdb_id, kegg_id). But it does not affect the final output from CalculateHyperScore because it uses hmdb names set in CrossReferencing.

```
    if (anal.type %in% c("msetora", "msetssp", "msetqea")) {
        cmpd.db <- .get.my.lib("master_compound_db.qs")
    }
    else {
        cmpd.db <- .get.my.lib("compound_db.qs")
    }
```

**Comment by xia-lab** [comment]
Thanks for the note. The reason for using different databases is to save computing time  for web server -  as the only those defined in the pathways will matter.
