### ISSUE TITLE
Any support of mouse KEGG pathway?

### ISSUE THREAD

**Issue by hh1985** [xia-lab/MetaboAnalystR#177]
Hi,

If I want to perform enrichment analysis (through metaboAnalystR or metaboanalyst online), is there any way I can set the database to mouse KEGG pathway?

Thanks,

-hh1985

**Comment by bowenli37** [comment]
Can you try the metabolic pathway analysis (MetPA)? MetPA and MSEA essential use the same statistical test, and MetPA gives additional impact factor which is not related to the P-val. MetaboAnalyst uses a modified version of KEGG pathway from KEGG database, where some unvalidated nodes were removed.

**Comment by hh1985** [comment]
I see. Thanks for the suggestion.
