### ISSUE TITLE
How to get model summary statistics like R2X, R2Y, Q2, pre in PCA (o)PLS-DA analysis?

### ISSUE THREAD

**Issue by ray1919** [xia-lab/MetaboAnalystR#178]
How to get model summary statistics like R2X, R2Y, Q2, pre in PCA (o)PLS-DA analysis?
I do not found in the doc, thank you for your time

**Comment by xia-lab** [comment]
The information is available from _mSetObj$analSet$plsda$fit.info_
We have exposed the command "**GetPLS_CVMat()**" to R command history
