### ISSUE TITLE
Class label were sorted in alphabetical order while leaving the sample values as what it is (found in sample-column format)

### ISSUE THREAD

**Issue by MASHUOA** [xia-lab/MetaboAnalystR#184]
this issue provides a mismatch between the original class labeled input data table and the final loaded table.
the class label row was read and sorted but the sample name keeps in their origional order.

**Comment by xia-lab** [comment]
Solved and the web interface (Data Editor) further allows users to specify orders based on their preference (to overwrite the alphabetic order).
