### ISSUE TITLE
Problem with Case Study IBD on MetaboAnalystR 3.0.3

### ISSUE THREAD

**Issue by mcmuffin413** [xia-lab/MetaboAnalystR#185]
Hello,

I am very new to R and am trying to use MetaboAnalystR 3.0.3 for the first time.  I was trying to use the Case study IBD data set for practice.  

I made it to step 2.1.3 in the tutorial (https://www.metaboanalyst.ca/docs/RTutorial.xhtml#2.1%20Raw%20Data%20Processing) before I got the following error:
> # Inspect the MS data via a 3D image. "res" are used to specify the resolution for the MS data.
> PerformDataInspect(data_folder_QC,res = 50)
Error in loadNamespace(name) : there is no package called ‘OptiLCMS’

Upon further investigation I got the following output: 
this R is version 3.6.3, package 'OptiLCMS' requires R >= 4.0.0

However I was a bit confused by this: I am running R ver 3.6.3 based on the recommendation of the wiki as it says: "R base with version > 3.6.1 is recommended. The compatibility of latest version (v4.0.0) is under evaluation."

I was just wondering what I should do to run the test data?  Is there an older version of OptiLCMS or can I use R version 4.0.0?

Thank you so much!

-Madison

**Comment by demonlj** [comment]
got the same problem
with R. 4.1.0, some package is missing compatibility too

**Comment by demonlj** [comment]
better to use R 4.0.3, could solve the OptiLCMS (<4.0.0 failed), mzR(4.0.0 failed)

**Comment by Zhiqiang-PANG** [comment]
We recommend all users to use the latest version of R (not dev).
