### ISSUE TITLE
Howto combined the analysis of both positive and negative results?

### ISSUE THREAD

**Issue by demonlj** [xia-lab/MetaboAnalystR#188]
The ESI-MSn experiments were used with the spray voltage of 3.5 kV and -2.5 kV in positive
and negative modes, respectively. With the workflow pdf file, I still cannot understand how to combine the analysis of both positive and negative modes results.

**Comment by Zhiqiang-PANG** [comment]
Not sure which module you are referring. If you still have questions, please post it here: https://omicsforum.ca/c/metaboanalyst/5
