### ISSUE TITLE
[bug] Error in `WaveICA()` function

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#192]
I encountered an error in `WaveICA()` function deriving from the line: `level<-floor(log10(nrow(data),2))`, where it should either be `log10(nrow(data))` or `log(nrow(data),2)`, since `log10()` only takes one argument. Please check, thanks.

**Comment by zhuxr11** [comment]
With reference to the original `WaveICA()` function, this should be `log(nrow(data),2)`.

**Comment by Zhiqiang-PANG** [comment]
fixed already. Closed
