### ISSUE TITLE
[bug] Error in `ExperimentsCluster_doe()` function

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#193]
I encountered an error when running  `ExperimentsCluster_doe()` function: `object 'optimize_function_list' not found`. This seems to be caused by the line `parallel::clusterExport(cl, optimize_function_list, envir = asNamespace("MetaboAnalystR"))`. Actually, this `optimize_function_list` is not used in the parallel-evaluated function `SlaveCluster_doe()`. So this export might not be necessary.

**Comment by Zhiqiang-PANG** [comment]
thanks for reporting. I will check and fix in the coming version 4.0 of MetaboAnalystR.
