### ISSUE TITLE
[bug] `RT_method = "loess"` not supported in `PerformParamsOptimization()`

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#194]
The `PerformParamsOptimization()` function only supports `RT_method = "peakgroup"` and `RT_method = "obiwarp"`, while the former is not used as one of the options in `SetPeakParam()` function; `SetPeakParam()` function uses `RT_method = "loess"` instead. This causes inconsistency while optimizing parameters using `SetPeakParam()` and then `PerformParamsOptimization()`.

This problem also matters in that if `RT_method = "peakgroup"`, `extra` argument will not be part of the return value (as processed by `SetPeakParam()` function), and the `extraPeaks` argument in `xcms::groupChromPeaks-density` will be missing since `UpdateRawSpectraParam()` (called by `PerformParamsOptimization()`) passes the `extra` field of the parameter to the `extraPeaks` argument. Now I have to use `RT_method = "loess"` when calling `SetPeakParam()` to get the `extra` field, and then manually change the `RT_method` to `"peakgroup"`, and finally call `PerformParamsOptimization()`. This is an unnecessarily complicated process.

**Comment by Zhiqiang-PANG** [comment]
Yes, this function is not supported now. We will consider to add this option in the coming release.
