### ISSUE TITLE
[bug] `unused argument (plotSettings$width)` in `PerformPeakProfiling()` function

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#195]
There are two versions of `PlotSpectraRTadj()` functions in the package, one with 4 arguments while the other with 5. `PerformPeakProfiling()` seems to call the 4-argument version while passing on 5 arguments, resulting in `unused argument (plotSettings$width)` error.

**Comment by xia-lab** [comment]
The issue has been fixed, and will be available in MetaboAnalystR 4.0 to be released soon
