### ISSUE TITLE
[bug] `reg` field is not updated into `mSetObj` in function `OPLSR.Anal()`

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#196]
In function `OPLSR.Anal()`, the first function call `.prepare.oplsr.anal(mSetObj, reg)` updates `reg` field into `mSetObj` with: `mSetObj$analSet$opls.reg <- reg`, as well as other fields. However, the returned object is not updated into the following function call `.save.oplsr.anal(mSetObj)`. I think the line `.prepare.oplsr.anal(mSetObj, reg)` should be `mSetObj <- .prepare.oplsr.anal(mSetObj, reg)` so that `mSetObj` is updated and `.save.oplsr.anal(mSetObj)` should use the updated `mSetObj` from `.prepare.oplsr.anal`.

**Comment by zhuxr11** [comment]
Similar problems also observed in functions `SAM.Anal` and `EBAM.Init`, since both `.prepare.*` functions update the `mSetObj` but do not assign the updated results.

**Comment by xia-lab** [comment]
These workflows are used for the web application only, and should not be used when running MetaboAnalystR locally.

**Comment by linlin0026** [comment]
thanks!!!! As in 4.0.0, I got  problem with **OPLSR.Anal function** (https://github.com/xia-lab/MetaboAnalystR/issues/252), I chose back to 3.3.0. Then I got the same question about 
 **OPLSDA.Permut** like u did; As u mentioned, I add _mSetObj_ <- before _.prepare.oplsr.anal(mSetObj, reg)_  
 It got the same result as online web, thanks
