### ISSUE TITLE
'compound_db.rds' cannot be downloaded

### ISSUE THREAD

**Issue by readmeh** [xia-lab/MetaboAnalystR#197]
- windows
- platform       x86_64-w64-mingw32          
- arch           x86_64                      
- os             mingw32                     
- system         x86_64, mingw32             
- status                                     
- major          4                           
- minor          0.5                         
- year           2021                        
- month          03                          
- day            31                          
- svn rev        80133                       
- language       R                           
- version.string R version 4.0.5 (2021-03-31)
- nickname       Shake and Throw 

```R
>       download.file(lib.url, destfile = filenm, method = "curl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0   1062      0  0:00:01 --:--:--  0:00:01  1358
>       my.lib <- readRDS(lib.path)
Error in readRDS(lib.path) : unknown input format
> paste("https://www.metaboanalyst.ca/resources/libs/", 
+         filenm, sep = "")
[1] "https://www.metaboanalyst.ca/resources/libs/compound_db.rds"
```
**I can't download the full cmpound_db.rds, there will only be a 1k file after the download.**

**Comment by Zhiqiang-PANG** [comment]
Please reinstall MetaboAnalyst, MetaboAnalystR is not using .rds file any longer.
