### ISSUE TITLE
[bug] `PlotSAM.Cmpd()` does not return an `mSetObj` as others

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#198]
I found out that `PlotSAM.Cmpd()` function does not return an `mSetObj` as other functions (including plotting functions). One of the features I like most of this package is that every function takes as the first argument and returns an `mSet` object, so that they can be chained with `%>%` to produce elegant code. However, `PlotSAM.Cmpd()` function has the last call of `dev.off()` returning an integer. Although it is not necessary to call `.save.*` in a plotting function, we need to explicitly return the modified `mSetObj` returned by `.prepare.sam.cmpd`. So the code for `PlotSAM.Cmpd()` should be:
```
PlotSAM.Cmpd <- function(mSetObj=NA, imgName, format="png", dpi=72, width=NA){
    mSetObj <- .prepare.sam.cmpd(mSetObj, imgName, format, dpi, width);
    .perform.computing();
    # no need to collect as it is an image, but still need to return the modified mSet
    return(.set.mSet(mSetObj))
}
```

**Comment by zhuxr11** [comment]
Similar problem observed in function `PlotEBAM.Cmpd()`.

**Comment by xia-lab** [comment]
This issue is fixed, and will be available in the next release
