### ISSUE TITLE
Function Not Found

### ISSUE THREAD

**Issue by litepalmer** [xia-lab/MetaboAnalystR#2]
Installing the package as described leaves me with only 3 functions available
- InitDataObjects
- PlotROCTest
- Read.TextData

Not sure if I'm doing anything wrong but installing exactly as guide suggests. 
Many thanks for all the work.

**Comment by litepalmer** [comment]
May have solved it. Seems as though it wasn't install the package properly under R 3.4.2, installed under R 3.3.2 and all functions have now appeared.

**Comment by bidezhu** [comment]
I have the similar issue. I have installed all the required packages on a Unix-based cluster computer. However, most of the functions cannot be used.

**Comment by litepalmer** [comment]
Seems to install OK know, all functions are available for use when installing on a clean version of R (3.4.2)

**Comment by jsychong** [comment]
Hi,

The package has been updated to address this issue, please re-download, all functions should be now available.
