### ISSUE TITLE
Error in CrossRefencing: 'curl' call had nonzero exit status

### ISSUE THREAD

**Issue by fzhang1117** [xia-lab/MetaboAnalystR#20]
Hi, 
I'm trying perform pathway enrichment and I meet a problem and I don't know how to solve it.

Many thanks for your reply

P.S: my code is: 
> library(MetaboAnalystR)
> mSet<-InitDataObjects("conc", "pathora", FALSE)
[1] "R objects intialized ..."
Warning message:
In Cairo::CairoFonts(regular = "Arial:style=Regular", bold = "Arial:style=Bold",  :
  CairoFonts() has no effect on Windows. Please use par(family="...") to specify the desired font - see ?par.
> cmpd.vec <-c("C03564","C00147","C00230","C00156","C01197","C01481","C00811","C03758","C00189","C01494","C00122","C01732","C00880","C00031","C02670","C00330")
> mSet<-Setup.MapData(mSet, cmpd.vec);
> mSet<-CrossReferencing(mSet, "kegg");
Error in download.file(lib.url, destfile = filenm, method = "curl") : 
  'curl' call had nonzero exit status
In addition: Warning message:
running command 'curl  "http://www.metaboanalyst.ca/resources/libs/compound_db.rds"  -o "compound_db.rds"' had status 127

**Comment by bowenli37** [comment]
Same problem here. The url "http://www.metaboanalyst.ca/resources/libs/compound_db.rds" was not accessible.

**Comment by jsychong** [comment]
Hi,
It seems like the downloading of "compound_db.rds" failed, are you using a Windows computer? I've updated the package recently, please retry to get this file. If this fails again, I can send you the "compound_db.rds" file directly.

Cheers

**Comment by dpanyard** [comment]
Hi there,
I've been running into this same issue with curl. In my case, I'm trying to run the function `CrossReferencing( my_list_of_compounds, q.type = "name", hmdb = TRUE, pubchem = TRUE, chebi = TRUE, kegg = TRUE, metlin = TRUE`.

I'm getting the same error message:
```
Error in download.file(lib.url, destfile = filenm, method = "curl") : 
  'curl' call had nonzero exit status
```
I'm also running R on a Windows machine, though, which I'm guessing is why the system call to curl is failing. You mentioned earlier that you had updated the package recently, but I downloaded MetaboAnalystR just this week using devtools (Option A on the GitHub page for MetaboAnalystR) and still ran into the problem.

Any ideas on how to get around this issue on Windows?

Thanks!

**Comment by jsychong** [comment]
Hi,

I've not yet found the solution as to why this function works on some Windows platforms (tested on 2 Windows 10 laptops) and not on others. If you shoot me an email I can send you the necessary file.

**Comment by dpanyard** [comment]
Hi,
I was able to download the file that curl was trying to download (compound_db.rds) using a Linux server separately. Is that the file you mean? If so, what's the way to have CrossReferencing() use that file?

Thanks for your help!

**Comment by samehmgd** [comment]
> Hi,
> It seems like the downloading of "compound_db.rds" failed, are you using a Windows computer? I've updated the package recently, please retry to get this file. If this fails again, I can send you the "compound_db.rds" file directly.
> 
> Cheers

still have the same issue could you help in solving
thanks

**Comment by jsychong** [comment]
According to https://cran.r-project.org/doc/manuals/r-patched/NEWS.pdf, download.file in R 3.5.2 should permit curl to work on Windows.

**Comment by dpanyard** [comment]
I think I figured out the problem. The version of Windows 10 my server is running is from before Windows 10 Version 1803, which it seems was when Windows started including curl natively (see this StackOverflow [comment](https://stackoverflow.com/questions/9507353/how-do-i-install-and-use-curl-on-windows/50200838#50200838)). Since .read.metaboanalyst.lib() eventually calls download.file() with method = "curl", it's giving a 127 status error when run on my Windows server.

My workaround was to use Windows Powershell manually outside of R. I moved to the directory where I was running the R code with MetaboAnalyst, then manually ran the curl calls for both the compound_db.rds and syn_nms.rds files:
```
PS C:\...\my_r_project> curl  https://www.metaboanalyst.ca/resources/libs/compound_db.rds  -o compound_db.rds
PS C:\...\my_r_project> curl  https://www.metaboanalyst.ca/resources/libs/syn_nms.rds  -o syn_nms.rds
```

These commands downloaded the files to my project directory, and now CrossReferencing() seems to be running fine from R.

For others who may run into this in the future, the call stack when I ran into the problem was...
CrossReferencing() >> MetaboliteMappingExact() >> .read.metaboanalyst.lib() >> download.file()

**Comment by samehmgd** [comment]
thanks a lot . yes im using 5.3.1 . ill update appreciating your helpand thanks for the super package you made. you are genus 

Sameh Magdeldin Mohamed, DVM, 2 Ph.D Head of Proteomics research program
Children's Cancer Hospital Egypt 57357.
Cairo, Egypt.
Phone:(202) 25351500. Ext:7204
Handy: 01064962210             http://samehmagd.tripod.com/https://scholar.google.co.jp/citations?user=EnP_f8UAAAAJ&hl=enhttps://scholar.google.co.jp/citations?user=EnP_f8UAAAAJ&hl=en


 

    On Monday, January 14, 2019, 5:37:07 PM GMT+2, jsychong <notifications@github.com> wrote:  
 
 
According to https://cran.r-project.org/doc/manuals/r-patched/NEWS.pdf, download.file in R 3.5.2 should permit curl to work on Windows.

**Comment by xlhd19980327** [comment]
Now it get 404 error code...
