### ISSUE TITLE
[bug] `PLSDA.CV()` needs to import `mvrValstats` from `pls` package

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#200]
`PLSDA.CV()` needs to import `mvrValstats` from `pls` package, since its calling `pls::R2` tries to evaluate `mvrValstats` in `pls::R2`'s parent frame, which is the running environment where `pls::R2` is called, namely the running environment of `PLSDA.CV()`, or an error of `mvrValstats` not found is thrown.

**Comment by Zhiqiang-PANG** [comment]
thanks for reporting. The coming version 4.0 of MetaboAnalystR would fix this issue.
