### ISSUE TITLE
[bug] `.setup.psea.library()` tries to modify the `currency` variable locked in the namespace

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#201]
`.setup.psea.library()` uses a super-assign operator (`<<-`) to assign`user.curr` to `currency`, but `currency` is a locked binding to the package namespace, which results in an error of trying to modify a locked binding. Here, I solve this problem by testing whether the variable exists in the namespace and whether it is locked there, and then try unlocking the binding before the assignment and locking it again after that if it is locked in the first place.

```
    # Test whether "currency" from namespace exists and is locked
    if (!rlang::is_missing(rlang::env_get(asNamespace("MetaboAnalystR"), "currency",
                                          default = rlang::missing_arg())) &&
        bindingIsLocked("currency", asNamespace("MetaboAnalystR"))) {
      currency_locked <- TRUE
      unlockBinding("currency", asNamespace("MetaboAnalystR"))
    }
    currency <<- user.curr;
    if (currency_locked) {
      lockBinding("currency", asNamespace("MetaboAnalystR"))
    }
```

**Comment by Zhiqiang-PANG** [comment]
thanks for your advice. I will consider this point in our coming version 4.
