### ISSUE TITLE
[warning] `brewer.pal(25, colorpalette)` raises a warning `n too large, allowed maximum for palette RdYlBu is 11`

### ISSUE THREAD

**Issue by zhuxr11** [xia-lab/MetaboAnalystR#203]
`brewer.pal(25, colorpalette)` raises a warning `n too large, allowed maximum for palette RdYlBu is 11`. This should be modified as:

```
brewer.pal(if (colorpalette %in% "Grey") 9 else 11,
                  colorpalette)
```

**Comment by Zhiqiang-PANG** [comment]
thanks for this advice. I have fixed this issue based on your comments. The fixing will appear in the coming version 4.0 of MetaboAnalystR.
