### ISSUE TITLE
CalculateHyperScore function failed to connect to Xia Lab API Server

### ISSUE THREAD

**Issue by S-KD** [xia-lab/MetaboAnalystR#205]
In MetaboAnalystR version 3.1.0 the CalculateHyperScore function always failed to connect to Xia Lab API Server. Here is the screenshot of the content of variable "request" from line 32 of the function.

![image](https://user-images.githubusercontent.com/66018301/128855017-024af3a4-8918-4e30-a8a7-fa6d05117c6a.png)

Can someone please explain how to resolve this error?

Thanks.

**Comment by Zhiqiang-PANG** [comment]
This is related to the failure of our api server. It has been fixed now.

**Comment by S-KD** [comment]
@Zhiqiang-PANG Thanks
