### ISSUE TITLE
MetaboAnalystR in proteomics data analysis

### ISSUE THREAD

**Issue by Shicheng-Guo** [xia-lab/MetaboAnalystR#207]
I am wondering whether MetaboAnalystR also can be applied in proteomics data analysis? 
Thanks
Shicheng

**Comment by Zhiqiang-PANG** [comment]
This is mainly designed for Metabolomics. If you want to perform statistics, they are applicable too for other omics data. But for raw data processing, it is not. I am closing this, if you have more question, please post it: https://omicsforum.ca/c/metaboanalyst/5
