### ISSUE TITLE
WormJam Consensus Model as Basis for Metabolic Studies in the Model Organism Caenorhabditis elegans

### ISSUE THREAD

**Issue by mvandervoet** [xia-lab/MetaboAnalystR#209]
Metabolite data is currently retrieved from KEGG, for C. elegans there is an improved metabolic model created by the WormJam community. Can this data, which is more accurate, be integrated in MetaboAnalyst? Publication: https://pubmed.ncbi.nlm.nih.gov/30488036/, repository: https://github.com/wormjam-consortium, contact: admin@wormjam.life (I'm not affiliated with the work).

**Comment by Zhiqiang-PANG** [comment]
thanks for recommending. We will evaluate this work and consider your advice carefully!
