### ISSUE TITLE
 could not find function "exportMetaboAnalyst"

### ISSUE THREAD

**Issue by Waqar54** [xia-lab/MetaboAnalystR#21]
Hi 
Thanks for all your work in creating MetaboAnalystR. 

I'm following the XCMS_to_MetaboAnalystR tutorial and have come across the following error from calling the exportMetaboAnalyst function: 

`> exportMetaboAnalyst(data, file = "met_test1.csv", label = data$sample_group)`

> Error in exportMetaboAnalyst(data, file = "met_test1.csv", label = data$sample_group) : 
  could not find function "exportMetaboAnalyst"

I'm using R Studio (Windows) with R version 3.4.4. I've tried reinstalling the package but this doesn't solve the issue. 

Thank you in advance

**Comment by jsychong** [comment]
Yes, the latest version of xcms does not yet include this function. Please follow etrh's codes to get the most up-to-date version. I will append the XCMS to MetaboAnalystR tutorial to include this information.

**Comment by Waqar54** [comment]
Many thanks both
