### ISSUE TITLE
PlotKEGGPath not working

### ISSUE THREAD

**Issue by ccshao** [xia-lab/MetaboAnalystR#210]
Dear MetaboAnalystR support,

It seems that `PlotKEGGPath` is not working in the latest github version (v 3.1.0), it simply returns an empty object. How to correctly retrive the data? Thanks!

```
Browse[2]> request
Response [http://api.xialab.ca/pathway_kegg_plot]
  Date: 2021-11-03 13:33
  Status: 200
  Content-Type: text/plain
<EMPTY BODY>
Browse[2]> httr::content(request)
NULL
Browse[2]> httr::content(request, "raw")
raw(0)
```

**Comment by Zhiqiang-PANG** [comment]
This is related to the failure of our api server. It has been fixed now. I close it.
