### ISSUE TITLE
Error API

### ISSUE THREAD

**Issue by wgarzon** [xia-lab/MetaboAnalystR#211]
Hi,

I'm trying to obtain information by HMDB ID using API for Python. I use the following code and it does not work, it returns empty values. The code is based on your web site. https://www.metaboanalyst.ca/docs/APIs.xhtml

Python code:
import requests
url = "http://api.xialab.ca/mapcompounds"
payload = "{\n\t\"queryList\": \"HMDB0000002;\",\n\t\"inputType\": \"hmdb\"\n}"

headers = {
    'Content-Type': "application/json",
    'cache-control': "no-cache",
    }

response = requests.request("POST", url, data=payload, headers=headers)
print(response.text)

Thanks for your help.

**Comment by Zhiqiang-PANG** [comment]
There is an error in your python syntax:
please use this one
`payload = '{\n\t"queryList": "HMDB0000002;",\n\t"inputType": "hmdb"\n}'
`
I am closing this since it is fixed now.
