### ISSUE TITLE
Increasing maxpeakwidth decreases called peak counts

### ISSUE THREAD

**Issue by grangel0955** [xia-lab/MetaboAnalystR#213]
I have found that increasing the maxpeakwidth parameter used by PerformPeakProfiling function from 500 to 1000 counterintuitively decreases the number of peaks called. I initially increased it to 1000 from default to ensure I pick up dihydroorotate, which has a long chromatographic tail in our system. Though increasing the max peak width did bring out dihydroorotate, I lost our chlorpropamide (peak width of about 4 seconds) internal standard peak with this parameter set, and the peak list overall is much shorter (~6000 peaks with maxpeakwidth=1000 compared to 11,000 peaks with maxpeakwidth=500). Comparing the optimized parameters shows that indeed maxpeakwidth was the only reported parameter that changed. I know both chlorpropamide and dihydroorotate peaks are present in the raw data via visual inspection.

Could you give any insight into why the decrease in peaks may be the case, even though the window of acceptable peak sizes was increased? Is there any way to ensure 

Please find my code below. The only thing that varied is the "maxpkwdth" parameter from 500 to 1000. 

`######  MetaboAnalystR Script Variables ######
data_files_QC <- [PathtoQC]	 #Location of directory with centroided QC .mzXML files
data_files_samples <- [PathtoFiles] #Location of directory with all centroided .mzXML files sorted by group into subdirectories
minpkwdth <- 2		#Manual set for minimal peak width in seconds
maxpkwdth <- 500	#Manual set for maximum peak width in seconds (things like dihydroorotate have a very long tail)
minFrctn <- 0.15 	#Manual set for minimal fraction of samples needed with peak to call peak across samples
snthresh <- 8		#Manual set for signal to noise ratio
nz <- 50000			#Manual set for signal min

##########################################################################################
##########################################################################################
currentDate<-Sys.Date()		#System Date for File Naming

###### Load In Packages Necessary for MA Script	######
library(MetaboAnalystR)

### Load In and Trim QC Data and Parameter Optimization ######
print("============ Begin Importing and Trimming Data ============")
raw_data_QC <- PerformDataTrimming(data_files_QC, rt.idx = .25)
save.image(file=paste("MetabAnalystR_",currentDate,".RData", sep=""))
print("============ Done with Importing and Trimming. Image Saved. ============")

library(OptiLCMS)

print("============ Begin Parameter Optimization ============")
param_initial <- SetPeakParam(platform="HPLC-Orbitrap", Peak_method="centWave", RT_method="obiwarp", polarity=polarity)
param_optimized <- PerformParamsOptimization(raw_data_QC, param = param_initial, ncore = 1)

param_optimized$min_peakwidth <- minpkwdth	 #Numeric, specify the minimum peak width in seconds. Only work for ’centWave’
param_optimized$max_peakwidth <- maxpkwdth #Numeric, specify the maximum peak width in seconds. Only work for ’centWave’.
param_optimized$minFraction <- minFrctn #Numeric, specify fraction of samples in each group that contain the feature for it to be grouped.
param_optimized$noise <- nz #Numeric, specify the noise level for peaking picking. Only work for ’centWave’.
param_optimized$polarity <- polarity
param_optimized$snthresh <- snthresh #Numeric, specify the signal to noise threshold.

print("**********************************")
print("============ Parameters Used for Profiling ============")
print(param_optimized)
print("**********************************")
write.table(t(param_optimized), file="Parameters_Utilized.txt", sep = "\t")
save.image(file=paste("MetabAnalystR_",currentDate,".RData", sep=""))
print("============ Done with Parameter Optimization. Image Saved. ============")

##### Peak Profiling of All Data with Optimized Parameters ######
print("============ Begin Peak Profiling ============")
raw_data <- ImportRawMSData(
	path=data_files_samples, #Character, input the file path to the folder containing the raw MS spectra to be processed.
	mode="onDisk" #Character, the data input mode. Default is "onDisk" to avoid memory crash. "inMemory" will absorb data into the memory.
)

mSet_1start <- PerformPeakProfiling(raw_data, Params = param_optimized, plotSettings = SetPlotParam(Plot = T))
save.image(file=paste("MetabAnalystR_",currentDate,".RData", sep=""))
print("============ Done with Peak Profiling. Image Saved. ============")

###### Peak Annotation ######
print("============ Begin Peak Annotations ============")

annParams<-SetAnnotationParam(
  polarity = polarity,
  perc_fwhm = 0.6,
  mz_abs_iso = 0.005,
  max_charge = 2,
  max_iso = 2,
  corr_eic_th = 0.85,
  mz_abs_add = 0.001
)

mSet_2annotPeaks <- PerformPeakAnnotation(mSet_1start, annParams)
save.image(file=paste("MetabAnalystR_",currentDate,".RData", sep=""))
print("============ Done with Peak Annotations. Image Saved. ============")

###### Format Peak List for MetaboAnalyst Statistical Analysis ######
print("============ Begin Formatting Peak List for MA ============")
mSet_3maPeaks <- FormatPeakList(
  mSet_2annotPeaks,             #The object created using the PerformPeakAnnotation.
  annParams,                    #The object created using the SetAnnotationParam function, containing user?~@~Ys specified or default parameters for downstream raw MS data pre- processing.
  filtIso =F,                   #Logical, filter out all isotopes except for [M]+ for positive ion mode and [M]- for negative ion mode. By default it is set to true.
  filtAdducts = T,              #Logical, filter out all adducts except [M+H]+ for positive ion more and [M-H]- for negative ion mode. By default it is set to false.
  missPercent = .8)             #Numeric, specify the threshold to remove features missing in X% of samples. For instance, 0.5 specifies to remove features that are missing from 50% of all samples per group. Method is only valid when there are two groups.
dev.off()
write.csv(mSet_3maPeaks@dataSet, file = "untargetedDataSet.csv", row.names=T)
save.image(file=paste("MetabAnalystR_",currentDate,".RData", sep=""))
print("============ Done with formatting peak lists. Image Saved. ============ ")

`

**Comment by Zhiqiang-PANG** [comment]
I would suggest you adjusting the parameter manually if you do have some interests in some specific peaks. Based on my experience, 500 for max_peakwidth is not common. Usually, thie parameter is less than 100. I am closing this issue. If you have more comments, please post it: https://omicsforum.ca/c/metaboanalyst/5
