### ISSUE TITLE
Integrated Pathway Analysis failed

### ISSUE THREAD

**Issue by mdidish** [xia-lab/MetaboAnalystR#214]
Dear,
Thank you for you very usefuls programs. I failed to run Integrated Pathway Analysis on R version:
- `PerformIntegGeneMapping` suggested in [this tutorial](https://drive.google.com/file/d/1HVoXNX98CZLcpr7MkpVZP5DueXcnZeIj/view) doesn't exist in MetaboAnalystR 3.1
- `PerformGeneMapping` exist, but I obtained an error :
`Erreur : Could not connect to database:
unable to open database file`

How can I resolve this error?

Thank you for your help.
Marc

**Comment by xia-lab** [comment]
It appears to be caused by the same issue related to qs package (with [solution provided](https://github.com/xia-lab/MetaboAnalystR/issues/219))
