### ISSUE TITLE
object 'anal.type' not found

### ISSUE THREAD

**Issue by MoonooK** [xia-lab/MetaboAnalystR#215]
Hello,

I would be thankful to know if anyone could help me with this error that I am keep getting: 
mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv", "rowp", "disc");
mSet<-SanityCheckData(mSet);
mSet<-ReplaceMin(mSet);
mSet <- Normalization(mSet, rowNorm = "NULL", transNorm = "LogNorm", scaleNorm = "AutoNorm", ref="NULL", ratio=FALSE, ratioNum=20)

trying URL 'http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv'
Content type '`}1·ù' length 32491 bytes (31 KB)
downloaded 31 KB

**Error in Read.TextData(mSet, "http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv",  : 
  object 'anal.type' not found**

Thank you,
Best,
Mona

**Comment by ichrak97** [comment]
Hello,

I have also the same problem, did you overcome the error ?!

IA
