### ISSUE TITLE
 EXCEPTION POINT CODE: PU3 when running PerformPeakProfiling

### ISSUE THREAD

**Issue by grangel0955** [xia-lab/MetaboAnalystR#216]
I keep getting the following error when I run PerformPeakProfiling. The code works with other datasets, but not with this particular one. It appears the processing gets to "Step 5/6: Started peak filling! This step may take some time..." right before the error pops up. Does anyone have any insight as to what is happening or how to fix it? 

```
ERROR:trying to get slot "params" from an object (class "simpleError") that is not an S4 object </font>
Error in PerformPeakProfiling(raw_data, Params = param_optimized, plotSettings = SetPlotParam(Plot = T)) : 
  EXCEPTION POINT CODE: PU3
```

**Comment by Gollha** [comment]
Same here, have you found any solution yet?

**Comment by oolonek** [comment]
Same on this side ! @xia-lab @Zhiqiang-PANG any clue ?

**Comment by kmh005** [comment]
Also experiencing issues with this PU3 error, either when I use 
```
Params = SetPeakParam(ppm = 15, 
            bw = 10, 
            mzdiff = 0.001, 
            max_peakwidth = 15, 
            min_peakwidth = 10)
```
as in the Opti-LCMS help, or try to manually add `param_optimized` to the `params` slot on my mSet.
```
rawData@params<-param_optimized
```
Any guidance would be greatly appreciated!

MetaboAnalystR_3.2.0 /OptiLCMS_0.99.4

**Comment by Zhiqiang-PANG** [comment]
PU3 error is specific for the data. Please share a reproducible example to check. I am closing this issue, please post any update here: https://omicsforum.ca/c/metaboanalyst/5
Bests.

**Comment by KarenGoncalves** [comment]
So, three years and no answer on this issue either here or on omicsforum?

**Comment by xia-lab** [comment]
Please read this post: https://omicsforum.ca/t/requirements-for-troubleshooting/857. Someone must be willing to provide a minimal reproducible example.

**Comment by KarenGoncalves** [comment]
I was able to run the peak profiling by changing the source code to make it use SnowParam for windows and setting ncores=1L.
My issue now is with the DIADeconvolution, let's see if I can make it work.

**Comment by Zhiqiang-PANG** [comment]
Hi Karen,
Please report your case together with a reproducible example and codes with me(zhiqiang.pang[at]xialab.ca) if you encounter with an issue.
Bests,
Zhiqiang
