### ISSUE TITLE
Test failed for test-metaboanalystr-analytical.R

### ISSUE THREAD

**Issue by bjxiezz** [xia-lab/MetaboAnalystR#217]
After installation of MetaboAnalystR I run test-metaboanalystr-analytical.R (https://github.com/xia-lab/MetaboAnalystR/blob/master/tests/testthat/test-metaboanalystr-analytical.R). The result showed:

"...
[1] "Resampling,  100 permutations to estimate background ..."
<packageNotFoundError in loadNamespace(x): there is no package called 'fitdistrplus'>
[ FAIL 3 | WARN 5 | SKIP 0 | PASS 28 ]
...
-- Failure (test-metaboanalystr-analytical.R:154:3): MS Peaks to Paths Module Works --
mSet$mummi.resmat[1, 1] not equal to 54.
1/1 mismatches
[1] 16 - 54 == -38

-- Failure (test-metaboanalystr-analytical.R:155:3): MS Peaks to Paths Module Works --
mSet$mummi.resmat[1, 2] not equal to 38.
1/1 mismatches
[1] 14 - 38 == -24

-- Failure (test-metaboanalystr-analytical.R:156:3): MS Peaks to Paths Module Works --
rownames\(mSet\$mummi\.resmat\)\[1\] does not match "Vitamin E metabolism".
Actual value: "Vitamin D3 \(cholecalciferol\) metabolism"
Backtrace:
 1. testthat::expect_match(rownames(mSet$mummi.resmat)[1], "Vitamin E metabolism") test-metaboanalystr-analytical.R:156:2
 2. testthat:::expect_match_(...)

[ FAIL 3 | WARN 5 | SKIP 0 | PASS 28 ]
"

Does this suggest that MetaboAnalystR installation is not completed? How can I fix this problem?

**Comment by xia-lab** [comment]
There is a hint in the first error message. Please make sure the this package (**fitdistrplus**) is installed correctly
