### ISSUE TITLE
Error in apply(is.na(int.mat), 2, sum) :    dim(X) must have a positive length

### ISSUE THREAD

**Issue by samehmgd** [xia-lab/MetaboAnalystR#22]
i keep getting an error when using metaboanalyst with R

mSet<-RemoveMissingPercent(mSet, percent=0.50)

Error in apply(is.na(int.mat), 2, sum) : 
  dim(X) must have a positive length
or even when trying to normalize, scale or remove the missing values

**Comment by jsychong** [comment]
Hi, 

Can you please include the entire code you used to get this error?
