### ISSUE TITLE
Need Information

### ISSUE THREAD

**Issue by devenderarora** [xia-lab/MetaboAnalystR#220]
Dear MetaboAnalyst Developer,

I am trying to run R version of MetaboAnalyst after performing the run on test dataset. During the run I found you choose rt.idx = 0.2 to retain 20% of total. May I know how we decide to what percentage is best? Any paper supporting the information could provide immense help. 

:
Thanks
Regards
Devender Arora

**Comment by Zhiqiang-PANG** [comment]
Hi Devender Arora,
The percentage depends on the how much sparse of your data. If you are not sure, you can use a large value (e.g. 0.9), as long as it is less than 1.

Hope this helps!
Zhiqiang
