### ISSUE TITLE
Error in Cairo::Cairo(file = imgName, unit = "in", dpi = dpi, width = w,  :    Unknown output type `72'

### ISSUE THREAD

**Issue by whitedayrat** [xia-lab/MetaboAnalystR#221]
Hi, I'm glad that you see this issue，thank you so much！
When I run this code : 

mSet<-PlotPathSummary(mSet, "path_view_0_", "png", 72, width=NA)

I got the Error:

Error in Cairo::Cairo(file = imgName, unit = "in", dpi = dpi, width = w,  :   Unknown output type `72'.

When I run this code : 
mSet<-InitDataObjects("conc", "pathora", FALSE)

I got the Warning:
Warning message:
In Cairo::CairoFonts(regular = "Arial:style=Regular", bold = "Arial:style=Bold",  :
  CairoFonts() has no effect on Windows. Please use par(family="...") to specify the desired font - see ?par.

My Cairo_1.5-14 version is latest run in R version 4.1.2, Platform: x86_64-w64-mingw32/x64 (64-bit), and Running under: Windows 10 x64 (build 19044).

**Comment by whitedayrat** [comment]
mSet<-PlotPathSummary(mSet, show.grid=T, "path_view_0_", "png",72,width=NA)
When I add a argument, it runs successfully. 
Thanks.

**Comment by xia-lab** [comment]
This function works as expected - the 2nd argument should be TRUE/FALSE for "show.grid" as described in the second post
