### ISSUE TITLE
Cannot install MetaboAnalystR

### ISSUE THREAD

**Issue by vshalkey** [xia-lab/MetaboAnalystR#223]
I am unable to install MetaboAnalystR. First, I installed all dependencies which I did one by one using BiocManager. I had to use a workaround to install SSPA. I am using R version 4.1.1, Bioconductor version 3.13 (BiocManager 1.30.16).  I have tried loading MetaboAnalystR using all 3 methods explained on the website. 

Option 1: 
> devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@HEAD
Skipping 9 packages not available: Biobase, pcaMethods, siggenes, MSnbase, impute, fgsea, edgeR, BiocParallel, RBGL
✓  checking for file ‘/private/var/folders/wm/ydm00_l94vv8nkvh1vlps4_40000gn/T/Rtmpz88SkM/remotes6c83d0c3204/xia-lab-MetaboAnalystR-1003fb1/DESCRIPTION’ ...
─  preparing ‘MetaboAnalystR’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (409ms)
─  checking for empty or unneeded directories
─  building ‘MetaboAnalystR_3.2.0.tar.gz’
   
* installing *source* package ‘MetaboAnalystR’ ...
** using staged installation
** libs
rm -f fortran/decorana.o c/Internal_utils_batch.o c/util.o cpp/melt.o c/fastmatch.o c/nncgc.o c/mzROI.o c/xcms_binners.o Exports.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c fortran/decorana.f -o fortran/decorana.o
make: gfortran: No such file or directory
make: *** [fortran/decorana.o] Error 1
ERROR: compilation failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/MetaboAnalystR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wm/ydm00_l94vv8nkvh1vlps4_40000gn/T//Rtmpz88SkM/file6c86ba7c3eb/MetaboAnalystR_3.2.0.tar.gz’ had non-zero exit status

I also tried this using the remotes package:
> remotes::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@HEAD
Skipping 9 packages not available: Biobase, pcaMethods, siggenes, MSnbase, impute, fgsea, edgeR, BiocParallel, RBGL
✓  checking for file ‘/private/var/folders/wm/ydm00_l94vv8nkvh1vlps4_40000gn/T/Rtmpz88SkM/remotes6c875eaabbb/xia-lab-MetaboAnalystR-1003fb1/DESCRIPTION’ ...
─  preparing ‘MetaboAnalystR’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (411ms)
─  checking for empty or unneeded directories
─  building ‘MetaboAnalystR_3.2.0.tar.gz’
   
* installing *source* package ‘MetaboAnalystR’ ...
** using staged installation
** libs
rm -f fortran/decorana.o c/Internal_utils_batch.o c/util.o cpp/melt.o c/fastmatch.o c/nncgc.o c/mzROI.o c/xcms_binners.o Exports.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c fortran/decorana.f -o fortran/decorana.o
make: gfortran: No such file or directory
make: *** [fortran/decorana.o] Error 1
ERROR: compilation failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/MetaboAnalystR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wm/ydm00_l94vv8nkvh1vlps4_40000gn/T//Rtmpz88SkM/file6c81b0be78/MetaboAnalystR_3.2.0.tar.gz’ had non-zero exit status

Option 2: 
> install.packages("https://www.dropbox.com/s/pp9vziji96k5z5k/MetaboAnalystR_3.2.0.tar.gz", repos = NULL, method = "wget")
sh: wget: command not found
Warning in install.packages :
  error in running command
Error in download.file(p, destfile, method, mode = "wb", ...) : 
  'wget' call had nonzero exit status

Option 3: 
> git clone https://github.com/xia-lab/MetaboAnalystR.git
Error: unexpected symbol in "git clone"

**Comment by sunsvet** [comment]
Did you manage to figure it out? I am having the same problem.

**Comment by vshalkey** [comment]
No, I couldn’t figure it out

**Comment by Zhiqiang-PANG** [comment]
Option 1 -> You need to make sure the "gfortran" has been installed successfully to compile the source code.
Option 2 -> You need to install wget from OS level;
Option 3 -> You have to install git from your OS level, too.
