### ISSUE TITLE
no applicable method for 'melt' applied to an object of class "character"

### ISSUE THREAD

**Issue by Cao-lab-zcmu** [xia-lab/MetaboAnalystR#224]
We submit the txt peak list file, however, the problem caused.
We don't kown the reason.
While we submit the file via web version of MetaboAnalyst, it got successed.
The error report is:

[1] "MetaboAnalyst R objects initialized ..."
[1] "Got 696 mass features."
[1] "779 inital ECs created!"
Error in UseMethod("melt", data) : 
  no applicable method for 'melt' applied to an object of class "character"

**Comment by ekgough** [comment]
I recently encountered the exact same problem.

**Comment by xiaowenchenjax** [comment]
I also encountered the exact same problem when running the example data.

**Comment by guanhomer** [comment]
I had the same problem recently.

Minimal reproducible codes:
```
library(MetaboAnalystR)
MetaboAnalystR:::melt.list(list(a="aa"))
# Loading required package: plyr
# Error in UseMethod("melt", data) : 
#   no applicable method for 'melt' applied to an object of class "character"
```

My solution is to replace `melt` to `reshape2::melt` in the `MetaboAnalystR:::melt.list` function as below.
```
tem <- function (data, ..., level = 1) 
{
    require(plyr)
    parts <- lapply(data, reshape2::melt, level = level + 1, ...)
    result <- rbind.fill(parts)
    names <- names(data) %||% seq_along(data)
    lengths <- vapply(parts, nrow, integer(1))
    labels <- rep(names, lengths)
    label_var <- attr(data, "varname") %||% paste("L", level, 
        sep = "")
    result[[label_var]] <- labels
    result
}
environment(tem) <- asNamespace("MetaboAnalystR")
assignInNamespace("melt.list", tem, ns = asNamespace("MetaboAnalystR"))

MetaboAnalystR:::melt.list(list(a="aa"))
#   value L1
# 1    aa  a
```

**Comment by Zhiqiang-PANG** [comment]
Thanks for reporting. This issue has been fixed. You can see it from the coming version 4.0. I am closing this.
