### ISSUE TITLE
Issue with 'meta.vec does not exist' error with PlotHeatMap2 function

### ISSUE THREAD

**Issue by jarcosh** [xia-lab/MetaboAnalystR#225]
Greetings,

I'm having trouble reproducing the output from the MetaboAnalyst web version while using MetaboAnalystR.

Specifically, while all the preliminary steps (reading my data and metadata, sanity checking it, normalization) work out just fine, meaning the output and seemingly the data adquired is identical when copying
```
1. | mSet<-InitDataObjects("specbin", "ts", FALSE)
-- | --
2. | mSet<-SetDesignType(mSet, "multi")
3. | mSet<-Read.TextDataTs(mSet, "Replacing_with_your_file_path", "rowts");
4. | mSet<-ReadMetaData(mSet, Replacing_with_your_file_path);
5. | mSet<-SanityCheckData(mSet)
6. | mSet<-ReplaceMin(mSet);
7. | mSet<-SanityCheckMeta(mSet, 1)
8. | mSet<-SetDataTypeOfMeta(mSet);
9. | mSet<-SanityCheckData(mSet)
10. | mSet<-FilterVariable(mSet, "none", "F", 25)
11. | mSet<-PreparePrenormData(mSet)
12. | mSet<-Normalization(mSet, "NULL", "LogNorm", "NULL", ratio=FALSE, ratioNum=20)
13. | mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
14. | mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
```

into my Rstudio console, an error appears when I get to the

```
15. mSet<-PlotHeatMap2(mSet, "heatmap2_0_", "norm", "row", "png", 72, width=NA, "euclidean","ward.D","bwm","overview","mean",2000, F, F, F, F)
```

step, namely
```
Error in which(colnames(sel.meta.df) == meta.vec[i]:
   object 'meta.vec' not found 
```
I checked the PlotHeatMap2 function from the repository and it seems meta.vec ought to come from how it's done in lines 138 to 149 of the utils heatmap script (https://github.com/xia-lab/MetaboAnalystR/blob/master/R/util_heatmap.R) just replacing dataSet$cls with mSet$dataSet$cls, but defining meta.vec that way soon gives way to a different error when repeating my line 15 trying to use PlotHeatMap2:

``` 
>Error in `[.data.frame`(meta.info, , meta.vec, drop = FALSE) : 
>  undefined columns selected 
```

this might be related to how meta.vec is a vector with only the chr of the first condition for each sample, while mSet$dataSet$meta.info is a list S3:data.frame with both two conditions. But then I'm not sure where meta.vec has to come from for this to work correctly. Attempting to use the GetMetaVec function from /general_proc_utils.R gives so many errors I'm wondering if perhaps not everything was imported correctly just by using library(MetaboAanalystR). 

Perhaps related, after 
``` 
> mSet<-Normalization(mSet, "NULL", "LogNorm", "NULL", ratio=FALSE, ratioNum=20)
```
I got
```
 >Warning message:
>In if (rownames(mSetObj$dataSet$norm) != rownames(mSetObj$dataSet$meta.info)) { :
>the condition has length > 1 and only the first element will be used
although this warning doesn't appear or impede anything in the web version 
```

I'm working in an Ubuntu20 virtualbox on a Windows host and used the metanr_packages() function and devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_vignettes = TRUE, build_manual =T) options to install, in case that information is helpful. EDIT 24/03/2022: R is version 4.1.3, but 3.6 gave me trouble with installing the dependencies, so I'm not sure what to do regarding that.

Thanks in advance 
@Zhiqiang-PANG

**Comment by xia-lab** [comment]
This issue should be fixed in the web platform, and will be available in MetaboAnalystR 4.0 to be released soon
