### ISSUE TITLE
Error in google driver

### ISSUE THREAD

**Issue by lh12565** [xia-lab/MetaboAnalystR#226]
Hi, I want to run your tutorial, and when I  run the code as below, there is an error:
```R
dl <- drive_download(
    as_id("10DBpPEWy2cZyXvmlLOIfpwqQYwFplKYK"), path = temp, overwrite = TRUE)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```
Can I download your example data directly? Thanks!

**Comment by Zhiqiang-PANG** [comment]
Hi, please do the authentication correctly and give the function full access via the authentication page. Besides, if you want some testing files, please find it here: https://www.dropbox.com/s/lh4ema8fn0f12hz/IBD_small.zip?dl=0
Bests,
Zhiqiang
