### ISSUE TITLE
  could not find function "ImportRawMSData"

### ISSUE THREAD

**Issue by andrifm** [xia-lab/MetaboAnalystR#228]
Hello, I am new to this metabolomic analysis. I already installed metaboanalystR without any Issues ( I Think!). When I try to follow the tutorial according to this page : https://www.metaboanalyst.ca/docs/RTutorial.xhtml, I got this error in the Script that I try to run : 

`rawData <- ImportRawMSData(NULL, data_folder_Sample, plotSettings = SetPlotParam(Plot=FALSE))
`
```
Error in ImportRawMSData(NULL, data_folder_Sample, plotSettings = SetPlotParam(Plot = FALSE)) : 
  could not find function "ImportRawMSData"
```

can anyone help me?

**Comment by louxiaoying** [comment]
only this function error ,or you can't use any function in [MetaboAnalystR]?

**Comment by Zhiqiang-PANG** [comment]
"ImportRawMSData" function is available from "OptiLCMS" pacakge (https://github.com/xia-lab/OptiLCMS), you need to install this dependancy if you want to use this.
 I am closing this.
