### ISSUE TITLE
Add enrichment analysis database

### ISSUE THREAD

**Issue by ChaoXu1997** [xia-lab/MetaboAnalystR#229]
This tool is great, but I found that there is no enrichment analysis database for pig species, can you add enrichment analysis for pig species?

**Comment by xia-lab** [comment]
Enrichment analysis is based on metabolite sets either created by our manual curation from literature and or extracted from public databases. We are not aware of this resource for pig. I will close it for now. Please feel free to re-open and provide links to public resources on this species.
