### ISSUE TITLE
PerformDataInspect with CDF-files - no graph, no info

### ISSUE THREAD

**Issue by ausdrehBio** [xia-lab/MetaboAnalystR#230]
I don't get any return when I give PerformDataInspect a path to a directory with CDF-files.
All I get is 
"
First file in  directoryX  will be inspected !
> 
"
... and thats it. Is there someone who also struggles with cdf-files or has an explanation for this?

**Comment by Zhiqiang-PANG** [comment]
Hi,Can you please convert your cdf file into mzML? If you like to share more information (e.g. an example data), please post it https://omicsforum.ca/c/metaboanalyst/5
I am closing this.
