### ISSUE TITLE
mSet<-InitDataObjects() Crash

### ISSUE THREAD

**Issue by CaptainMurzuk** [xia-lab/MetaboAnalystR#231]
Hi everyone,

I recently installed MetaboAnalyst and wanted to use it on R.

I tried to use this tool on my data.

When I use the mSet<-InitDataObjects() function, R crashes directly.
I get the following message: 
Starting Rserve...
"...\x64\Rserve.exe" --no-save
Fontconfig error: Cannot load default config file

I am using the version of R 4.2.0.

Do you have any solution?

Thank you so much !

**Comment by Zhiqiang-PANG** [comment]
Can you please provide more information on your case, like your OS and sessionInfo. I am closing this, if you have more update, please post it: https://omicsforum.ca/c/metaboanalyst/5
Best
