### ISSUE TITLE
param_optimized <- PerformParamsOptimization(raw_data, param = param_initial, ncore=4)  error in Mac

### ISSUE THREAD

**Issue by ghatlar** [xia-lab/MetaboAnalystR#233]
> param_optimized <- PerformParamsOptimization(raw_data, param = param_initial, ncore=3) 

Step 1/6: Start to optimize parameters! 
                
This step may take a long time...
DoE Optimization Starting Now...
Evaluating Noise level...
Done!                                                                      
Preparing Parameters for optimization finished !
Data Spliting Finished !
Peak Preparing Begin...
Peak Preparing Done !
Round:1
DoE Running Begin...
awk: can't open file /proc/meminfo
 source line number 1
Error in if (memtotal/data.size > 30) { : argument is of length zero
In addition: Warning message:
In system("awk '/MemTotal/ {print $2}' /proc/meminfo", intern = TRUE) :
  running command 'awk '/MemTotal/ {print $2}' /proc/meminfo' had status 2
How can I solve this error?

**Comment by ausdrehBio** [comment]
Same Problem here. MacOS doesn't have the /proc-filesystem like Linux. Still searching for a solution...

**Comment by Zhiqiang-PANG** [comment]
I think you are using OptiLCMS here. I will check and fix this from OptiLCMS level. Closing this issue.

**Comment by zxc098** [comment]
Hi,

I see the issue has been closed, but using MacOS just had exact error message above occur using OptiLCMS with Metabonalayst also loaded (tried every available install method and version but made no difference). 

Not sure if it's just local issue with me, but in case anyone is encountering same thing, found simple work around (in my case): leave ncore = 1. This now takes forever but seems to work as temporary stop gap...

If this is more broad issue/other people are encountering it, would it be possible to modify OptiLCMS so number of cores can be increased?

Thank you.
