### ISSUE TITLE
Error in socketConnection(port = port, server = TRUE, blocking = TRUE, : cannot open the connection

### ISSUE THREAD

**Issue by gcooper907** [xia-lab/MetaboAnalystR#235]
I'm getting this error just working with the example dataset from the MetaboAnalyst website. I cannot seem to find anyone else experiencing this issue or how to fix it. When this error occurs, it then doesn't run the mSet so I cannot work through this any further. Any guidance/help would be greatly appreciated.

**Comment by Zhiqiang-PANG** [comment]
Hi Gcooper, thanks for reporting. Please provide more details on how to reproduce this error. We recommend you posting this question to Omicsforum: https://omicsforum.ca/c/metaboanalyst/5
I am closing this.
