### ISSUE TITLE
can not  install MetaboAnalystR

### ISSUE THREAD

**Issue by litianhui333** [xia-lab/MetaboAnalystR#236]
When I try to install the MetaboAnalystR, the error came out as below:

Error: ! error in callr subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package 'MetaboAnalystR'

how can I fix this problem? Thank you!

**Comment by Zhiqiang-PANG** [comment]
Hi Hui,
Can you provide more details on your R and your PC's information. I am closing this, please update your feedback from Omicsform: https://omicsforum.ca/c/metaboanalyst/5
Bests,
Zhiqiang
