### ISSUE TITLE
cannot download the demo

### ISSUE THREAD

**Issue by gerrardmai** [xia-lab/MetaboAnalystR#237]
download.file("https://www.metaboanalyst.ca/MetaboAnalyst/resources/data/integ_genes.txt", "integ_genes.txt", "curl")

##########
HTTP Status 404 - Not Found
type Status report

messageNot Found

descriptionThe requested resource is not available.

Payara Server 5.194 #badassfish

#############
nothing but error?

**Comment by Zhiqiang-PANG** [comment]
Please use this updated link: https://www.metaboanalyst.ca/MetaboAnalyst/resources/data/integ_genes_1.txt
