### ISSUE TITLE
.read.metaboanalyst.lib should add a test to detect the corrupted rds file

### ISSUE THREAD

**Issue by GBsuperman** [xia-lab/MetaboAnalystR#24]
The code was working for a long time.  But today, it suddenly stopped to work (CrossReferencing).  
Error in readRDS(lib.path) : unknown input format

It turns out that due to the network issue, a corrupted compound_db.rds was downloaded.  Add an evaluation to allow re-download of the rds file  in .read.metaboanalyst.lib will avoid the problem.

**Comment by jsychong** [comment]
This is a great solution, thanks for the suggestion!
