### ISSUE TITLE
Small bug fix for the function PlotMetaCorrHeatmap() and PlotMetaHeatmap()

### ISSUE THREAD

**Issue by xiaodfeng** [xia-lab/MetaboAnalystR#240]
The recently launched module of "Statistical Analysis [metadata table]" is quite helpful for analyzing datasets with more than two factors. The website version works fine. When I tried the local R version, there are errors reported. By checking the time_asca_heatmap2.R file, I think the reason comes from the functions PlotMetaCorrHeatmap() and PlotMetaHeatmap() are not exported. Thus, adding @export before these two functions should fix the small bug. I am also looking forward to the tutorial for the local R version.

**Comment by xia-lab** [comment]
Fixed in the web, and will be fixed in the MetaboAnalsytR 4.0
