### ISSUE TITLE
Request to add the three-way ANOVA analysis in the module of "Statistical Analysis [metadata table]"

### ISSUE THREAD

**Issue by xiaodfeng** [xia-lab/MetaboAnalystR#242]
The recently launched module of "Statistical Analysis [metadata table]" is quite helpful for analyzing datasets with more than two factors. We have a dataset containing three factors, thus I would like to perform a three-way ANOVA analysis. However, there are only one-way and two-way ANOVA functions in the module. Would it be possible to have a three-way ANOVA analysis in the module "Statistical Analysis [metadata table]"?

**Comment by xia-lab** [comment]
I assume the question is for the web platform, and I posted the answer on our [OmicsForum](https://omicsforum.ca/t/request-to-add-the-three-way-anova-analysis-in-the-module-of-statistical-analysis-metadata-table/1068). Note how to do three-way ANOVA in R is a general statistics question, not unique to MetaboAnalystR. Please feel free to re-open this thread if this is not the case.
