### ISSUE TITLE
404 error in SearchNetDB

### ISSUE THREAD

**Issue by slzhao** [xia-lab/MetaboAnalystR#244]
Hello,
Would you please help to fix the database download issue? Using the lates version from github (MetaboAnalystR_3.2.0)

Data and codes were extracted from the website.

```
mSet<-InitDataObjects("conc", "network", FALSE)
mSet<-SetOrganism(mSet, "hsa")
cmpdListFile<-"temp.txt"
cmpdList<-readChar(cmpdListFile, file.info(cmpdListFile)$size)
mSet<-PerformCmpdMapping(mSet, cmpdList, "hsa", "kegg");
```
[1] "Loaded files from MetaboAnalyst web-server."
[1] "1"                                                                              
[2] "Name matching OK, please inspect (and manual correct) the results then proceed."
`mSet<-CreateMappingResultTable(mSet)`
[1] "Loaded files from MetaboAnalyst web-server."
`#mSet<-GetNetworkGeneMappingResultTable(mSet) #comments as no genes in this data`
`mSet<-PrepareNetworkData(mSet);`
[1] "Loaded files from MetaboAnalyst web-server."
[1] "All IDs are unique."
[1] "A total of  26 unique compounds were found."
`mSet<-SearchNetDB(mSet, "pheno", "global", FALSE, 0.5)
`trying URL 'https://www.metaboanalyst.ca/resources/libs/network/MetPriCNet.sqlite'
Error in download.file("https://www.metaboanalyst.ca/resources/libs/network/MetPriCNet.sqlite",  : 
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/network/MetPriCNet.sqlite'
In addition: Warning messages:
1: In download.file("https://www.metaboanalyst.ca/resources/libs/network/MetPriCNet.sqlite",  :
  downloaded length 0 != reported length 1062
2: In download.file("https://www.metaboanalyst.ca/resources/libs/network/MetPriCNet.sqlite",  :
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/network/MetPriCNet.sqlite': HTTP status was '404 Not Found'

**Comment by Zhiqiang-PANG** [comment]
Hi, this issue has been fixed in the lastest update. I am closing this.
