### ISSUE TITLE
could not find function "GetImpFeatureMat"

### ISSUE THREAD

**Issue by qqwxp** [xia-lab/MetaboAnalystR#245]
I am learning the module Biomarker Analysis. 
When I run the code:
imp.feats <- GetImpFeatureMat(mSet, mSet$analSet$multiROC$imp.cv, 10), it said "could not find function "GetImpFeatureMat"".

Besides, use ?GetImpFeatureMat in rstudio can return the help page of this function.

Version info:
R4.1.2,
MetaboAnalystR 3.2
Windows 11

**Comment by Zhiqiang-PANG** [comment]
This function has been added back in today's update. Please reinstall and try. I am closing this.
