### ISSUE TITLE
ERROR: compilation failed for package 'MetaboAnalystR'

### ISSUE THREAD

**Issue by cyber765** [xia-lab/MetaboAnalystR#246]
* installing *source* package 'MetaboAnalystR' ...
** using staged installation
** libs
rm -f fortran/decorana.o c/Internal_utils_batch.o c/util.o cpp/melt.o c/fastmatch.o c/nncgc.o c/mzROI.o c/xcms_binners.o Exports.o
gfortran  -fno-optimize-sibling-calls    -O2  -mfpmath=sse -msse2 -mstackrealign  -c fortran/decorana.f -o fortran/decorana.o
gcc  -I"D:/R/R-42~1.2/include" -DNDEBUG     -I"D:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c c/Internal_utils_batch.c -o c/Internal_utils_batch.o
c/Internal_utils_batch.c: In function 'do_decorana':
c/Internal_utils_batch.c:114:3: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
  114 |   for (i = 0, nid = 0; i < nr*nc; i++)
      |   ^~~
c/Internal_utils_batch.c:118:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'for'
  118 |     int *ibegin = (int *) R_alloc(nr, sizeof(int));
      |     ^~~
gcc  -I"D:/R/R-42~1.2/include" -DNDEBUG     -I"D:/R/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c c/util.c -o c/util.o
g++  -std=gnu++11 -I"D:/R/R-42~1.2/include" -DNDEBUG     -I"D:/R/rtools42/x86_64-w64-mingw32.static.posix/include"  -fopenmp    -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c cpp/melt.cpp -o cpp/melt.o
cpp/melt.cpp:1:10: fatal error: Rcpp.h: No such file or directory
    1 | #include <Rcpp.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [D:/R/R-42~1.2/etc/x64/Makeconf:260: cpp/melt.o] Error 1
ERROR: compilation failed for package 'MetaboAnalystR'
* removing 'D:/R/R-4.2.2/library/MetaboAnalystR'

**Comment by Zhiqiang-PANG** [comment]
It seems the Rcpp.h is not included. Please update your Rcpp package and RTools for windows. I am closing this. If you have more question, post it here: https://omicsforum.ca/c/metaboanalyst/5
