### ISSUE TITLE
can't download the databases

### ISSUE THREAD

**Issue by ZhangFuchang** [xia-lab/MetaboAnalystR#249]
Hi, sorry to trouble you! I am using “MetaboAnalystR” package.
I download it and install, but when I am trying to use “joint analysis”, I can’t get the database.

I thought these databases were in the downloaded installation package, but I went into the installation package and searched all the directories, but I didn't see the data.

This is the download address of my installation package under Linux:
https://www.dropbox.com/s/pp9vziji96k5z5k/MetaboAnalystR_3.2.0.tar.gz

And this is the download address of my installation package under windows:
https://drive.google.com/file/d/1OHRUzXFDukWXEKxTLMF9X1fHRN06uFFu/view?usp=sharing

I went to check the source code to see where the database can be downloaded,
the code are as below:
url.pre ← "https://github.com/xia-lab/MetaboAnalystR3.0/raw/master/inst/database/sqlite/GeneID_25Species_JE/"
(according to the code, this url is on the line 198 of general_data_utils.R)
and as you can see the "url.pre" doesn’t exist.

Then I go to google search, I found that this website seems to have these database:
https://rdrr.io/github/xia-lab/MetaboAnalystR3.0/f/
but the sqlite database files in that url also doesn’t exist.

those databases that I can’t find is as follows:
docs/MetaboAnalystR_3.0.0_manual.pdf
docs/MetaboAnalystRlogo.png
docs/log_v3.0.png
inst/CITATION
inst/database/sqlite/GeneID_25Species_JE/.DS_Store
inst/database/sqlite/GeneID_25Species_JE/ath_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/bsu_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/bta_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/cel_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/cjo_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/dme_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/dre_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/eco_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/gga_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/hsa_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/mlo_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/mmu_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/mtb_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/osa_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/pae_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/pfa_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/ppu_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/rno_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/sau_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/sce_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/smm_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/ssc_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/syf_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/tbr_genes.sqlite
inst/database/sqlite/GeneID_25Species_JE/tma_genes.sqlite
inst/lists/ions.csv
inst/lists/neutraladdition.csv
inst/lists/neutralloss.csv
inst/rules/extended_adducts_neg.csv
inst/rules/extended_adducts_pos.csv
inst/rules/primary_adducts_neg.csv
inst/rules/primary_adducts_pos.csv

So the question is that, where can I download those databases?
Looking forward to your reply. Thank you very much!

**Comment by Zhiqiang-PANG** [comment]
Hi, I have fixed this missing db issue. Please download the latest version. If you have more questions, post it here: https://omicsforum.ca/c/metaboanalyst/5
I am closing this.
