### ISSUE TITLE
error with metaboanalyst with R

### ISSUE THREAD

**Issue by samehmgd** [xia-lab/MetaboAnalystR#25]
Hi
i still have some errors come when using metaboanalyst in R 
Warning message:
In Cairo::CairoFonts(regular = "Arial:style=Regular", bold = "Arial:style=Bold",  :
  CairoFonts() has no effect on Windows. Please use par(family="...") to specify the desired font - see ?par.

if the issue is compound_db.rds file how to use it , where i can find it

could you help to solve it? thanks

**Comment by jsychong** [comment]
Hi, 

Even though you have this message, does the command still work? If not if you shoot me an email I can forward you the necessary files.

**Comment by sstandage** [comment]
Good afternoon,

I'm getting this same error on a windows 10 machine. What files do I need and how do I install them?

Thank you.

**Comment by jessica-ewald** [comment]
Curl issues were in R .. recent R update fixed this.
