### ISSUE TITLE
No 'PreparePrenormData' function

### ISSUE THREAD

**Issue by jackrrryan** [xia-lab/MetaboAnalystR#26]
Hi, I noticed that you updated 'gen_norm_utils.R' a day ago, and on GitHub it has the PreparePrenormData function. When I downloaded the repository and attempted to install, I got this message:

`Quitting from lines 35-53 (Biomarker_Analysis.Rmd) 
Error: processing vignette 'Biomarker_Analysis.Rmd' failed with diagnostics:
could not find function "PreparePrenormData"
Execution halted`

I can't install the package because of this. Any updates? Thanks!

**Comment by J-Sabino** [comment]
I just installed the MetaboAnalyst R package, however, when I try to read the R code I get from the online tutorial:

> mSet<-PreparePrenormData(mSet)
Error in PreparePrenormData(mSet) : 
  could not find function "PreparePrenormData"

**Comment by Deedis** [comment]
I also have the same issue. So when I try the normalization without it, I get the following error message:
"Error in abs(data[data != 0]) : 
non-numeric argument to mathematical function"
Any recommendation on how to solve it? Thanks!

**Comment by jsychong** [comment]
I've updated the underlying code to expose this, thanks for the notes!
