### ISSUE TITLE
Error on PerformPSEA()

### ISSUE THREAD

**Issue by apulvino** [xia-lab/MetaboAnalystR#273]
I get the following error when attempting to run PerformPSEA()

Error in FUN(X[[i]], ...) : all(head(S, -1) < tail(S, -1)) is not TRUE

I'm a little confused as to where this one is coming from. It's unclear from the function's associated code. For reference, I'm attempting to execute as the vignette suggests:
PerformPSEA(mSet, "hsa_mfn", "current", permNum = 100)

Thanks ahead for any insight anyone can offer on this!

**Comment by apulvino** [comment]
If I swap '5' for '1' in UpdateInstrumentParameters() (which recommends 5 in the vignette), I get the following:

Warning: NaNs producedWarning: NaNs produced<simpleError in fitdistrplus::fitdist(perm_minus, distr = "gamma", method = "mle",     lower = c(0, 0), start = list(scale = 1, shape = 1)): the function mle failed to estimate the parameters, 
                with the error code 7

... No opportunity to traceback from this error to figure out how I might continue parameterizing code from the vignette.

I think it would also be helpful to have a clear understanding/documentation which references what numeric refers to what instrument...

**Comment by ekopylova** [comment]
Tracing back the original error, it seems the MetaboAnalystR code throws the error at the [following line call](https://github.com/xia-lab/MetaboAnalystR/blob/master/R/util_fgsea.R#L86):

util_fgsea.R
```
  #perform gsea
  gseaStatRes <- do.call(rbind,
                         lapply(pathwaysFiltered, fgsea::calcGseaStat,
                                stats=stats,
                                returnLeadingEdge=TRUE))
```
Looking at the function ```fgsea::calcGseaStat```, the error is raised in the [following line call](https://github.com/ctlab/fgsea/blob/master/R/fgsea.R#L134):

fgsea.R
```
   S <- sort(S)
   stopifnot(all(head(S, -1) < tail(S, -1)))
```

Here is a minimal example of input that will cause the function to yield an error:

```
> S
EC00019 EC00020 EC00068 EC00030 EC00038  EC0009  EC0008 EC00093  EC0006  EC0007 
     14      37      95      95     161     216     225     296     320     328 
> stopifnot(all(head(S, -1) < tail(S, -1)))
Error: all(head(S, -1) < tail(S, -1)) is not TRUE
> stats[95]
EC00030; EC00068 
       0.6997122 
```

The function ```stopifnot(all(head(S, -1) < tail(S, -1)))``` is checking whether each element in the vector ```head(S, -1)``` (which includes all elements of S except the last one) is less than the corresponding element in the vector ```tail(S, -1)``` (which includes all elements of S except the first one). 

If we break down the vectors ```head(S, -1)``` and ```tail(S, -1)``` based on their definitions:

```head(S, -1)``` includes all elements except the last one: 14 37 95 95 161 216 225 296 320
```tail(S, -1)``` includes all elements except the first one: 37 95 95 161 216 225 296 320 328

Comparing the elements:

14 < 37 - This condition is satisfied.
37 < 95 - This condition is satisfied.
95 < 95 - This condition is NOT satisfied.
...

There is an issue having two different empirical compounds (e.g. EC00030; EC00068) having the same value in the stats array? Why does this come up in the latest version of MetaboAnalystR?

Thanks!

**Comment by apulvino** [comment]
Thanks for your reply! Still not quite sure why the problem persists, but I chose different approaches for analysis, and will close this one out.
