### ISSUE TITLE
Request for common metabolism names in pathway view 

### ISSUE THREAD

**Issue by holgerman** [xia-lab/MetaboAnalystR#28]
Thank you for providing MetabolAnalzst(R) especially for the large flexibility already established!

When using  MetabolAnalzst(R) for pathway enrichment, the pathway view is of high value. As an enhancement or feature request, it would be great if names of compounds in the pathway could be human-readable, e.g. L-Phenylalanine or Phe instead of C00079.

Thanks and best,
Holger

**Comment by jsychong** [comment]
Thanks for this suggestion, we will keep this in mind when updating our graphics!
