### ISSUE TITLE
MetaboAnalyst Docker Installation Error

### ISSUE THREAD

**Issue by FleurGaBru** [xia-lab/MetaboAnalystR#29]
Our MetaboAnalyst_Docker installation works perfect, except that the Correlations Function in Statistical Analysis does not give any output or HTTPS Status 404- Not found. 
When checking on the command line in the docker, I get the following Error message:

```
Error in loadNamespace(name) : there is no package called 'Hmisc'
org.rosuda.REngine.Rserve.RserveException: voidEval failed, request status: error code: 127
```

Installing Hmisc with install.packages("Hmisc") in the Docker broke the current Docker deployment. Is there a way how I can add the missing package to Docker (temporary) or could you please add it to the next version of the Docker MetaboAnalyst installation?

**Comment by jsychong** [comment]
Thanks for the note! I will try adding the Hmisc package and see if it still works fine.
