### ISSUE TITLE
ImputeVar function

### ISSUE THREAD

**Issue by litepalmer** [xia-lab/MetaboAnalystR#3]
When attempting to use the imputeVar function I get the following error: 

Error in as.data.frame(new.mat) : object 'new.mat' not found

This is after using the following code which is given by the online service:
```

mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "data.csv", "colu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-RemoveMissingPercent(mSet, percent=0.5)
mSet<-ImputeVar(mSet, method="knn")
```

Any help would be appreciated.

**Comment by jsychong** [comment]
Hi,

The R package has been updated to fix this issue, thanks for letting us know!
