### ISSUE TITLE
Normalization using internal standard mixture

### ISSUE THREAD

**Issue by XiaoyangSu** [xia-lab/MetaboAnalystR#30]
I see that the normalization can be done to a specified feature, such as an internal standard. If we have a mixture of internal standards, can we normalize each sample to this mixture to maximize accuracy?

**Comment by jsychong** [comment]
Hi, it makes sense to do that - by your mixture of internal standards do you mean having several internal standards with different RT spanning your entire analysis time? If so, MetaboAnalystR does not support such normalization, but you should be able to do this in R.

**Comment by XiaoyangSu** [comment]
Yes. We have a mixture of internal standards to cover multiple metabolite classes and the whole chromatography time domain. Is there a plan to support it in MetaboAnalystR? Thanks!

**Comment by jsychong** [comment]
Not at this point but we will now add it to our considerations for future upgrades, cheers!
