### ISSUE TITLE
Error in Cairo::Cairo(file = imgName, unit = "in", dpi = dpi, width = w,  :    Failed to create Cairo backend!

### ISSUE THREAD

**Issue by marcelolaia** [xia-lab/MetaboAnalystR#31]
Hi,

When I run the command:

 mSet<-PlotHeatMap(mSet, "heatmap_1_", "png", 300, width=NA, "norm", "row", "euclidean", "ward.D","gbr", "detail", T, T, NA, T, T)

I got the error:

Error in Cairo::Cairo(file = imgName, unit = "in", dpi = dpi, width = w,  : 
  Failed to create Cairo backend!

The command

mSet<-PlotHeatMap(mSet, "heatmap_0_", "png", 1200, width=NA, "norm", "row", "euclidean", "ward.D","gbr", "overview", T, T, NA, T, T)

Works!

**Comment by jsychong** [comment]
Hi, it seems possible to be an issue with your Cairo - can you try re-installing the Cairo R package (newest update).
