### ISSUE TITLE
Installation issues on Windows (11) in conda environment 

### ISSUE THREAD

**Issue by iamthegregman** [xia-lab/MetaboAnalystR#311]
Hi,

I was hoping to run this from a windows/conda environment and have tried to follow the instructions for windows installs but hit various snags. 

I wondered if anyone with a stable windows build would be willing to share the exact version that they are using for:
R-Base
R-Tools 
Bioconductor/Biocmanager 
SSPA 
Other relevant packages?

Sorry I appreciate this is slightly basic but I'd hoped to find a stable solution (without a linux dual boot, which will be the alternative)

Thanks

**Comment by rocilia** [comment]
I installed and run the MetaboAnalystR 4.0 packages successfully. Here are my version of the packages you mentioned:
R-Base: 4.2.0
R-Tools: 4.2.0
Bioconductor/Biocmanager: 1.30.23
SSPA: I haven't downloaded this yet, but I found another answer under the issues, probably you can have a try: https://github.com/xia-lab/MetaboAnalystR/issues/309
Other relevant packages: several packages are needed for dependency, I installed separately based on the warnings.

**Comment by rocilia** [comment]
And I think this might also help you: https://github.com/xia-lab/MetaboAnalystR/issues/130
