### ISSUE TITLE
font size in PlotHeatMap

### ISSUE THREAD

**Issue by marcelolaia** [xia-lab/MetaboAnalystR#32]
Hi,

I suggest a parameter to change font size in the PlotHeatMap function (and others plot functions). I try pointsize from Cairo and it not worked.

**Comment by jsychong** [comment]
Hi, thanks for the suggestion, I can definitely provide this as an option.

**Comment by lmjohnstone** [comment]
Do you have any updates on this request? I would love to see an option to change the font size in other types of plots, including ROCs and PLS-DA.
