### ISSUE TITLE
possible bug in CalculateHyperScore

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#34]
I first found that the p values of CalculateHyperScore were NaN in some cases. It was caused by this line:
res.mat[i, 4] <- phyper(hit.num[i] - 1, set.num[i], uniq.count - set.num[i], q.size, lower.tail = F)
when uniq.count < q.size, which means the number of balls drawn from the urn is more than the total number of balls in the urn.
The correct value of q.size should be:
q.size <- length(which(ora.vec %in% unique(unlist(current.mset))))

**Comment by jsychong** [comment]
Hi, thanks for pointing out this issue. Would you be able to provide your dataset for me to recreate the NaN p-values so I can verify this?

**Comment by bowenli37** [comment]
example.txt is the ID mapping table.
list.txt is the list of HMDB ID as input.
ref.txt is the list of compound names as the reference metabolome.

A screenshot of the output:
![image](https://user-images.githubusercontent.com/2127513/54575422-05a30980-4a2f-11e9-9ec2-db32632d9b80.png)

[example.txt](https://github.com/xia-lab/MetaboAnalystR/files/2981207/example.txt)
[ref.txt](https://github.com/xia-lab/MetaboAnalystR/files/2981208/ref.txt)
[list.txt](https://github.com/xia-lab/MetaboAnalystR/files/2981211/list.txt)

**Comment by bowenli37** [comment]
CalculateOraScore could be affected in the same way.

**Comment by bowenli37** [comment]
There is invalid string in cmpd.db[2953,] in compound_db.rds
Browse[2]> cmpd.db[2953,]
         hmdb_id                 name pubchem_id chebi_id      kegg_id metlin_id lipid                  smiles
2953 HMDB0006831 3-Dehydroxycarnitine        725    16244 C05543鈬<a5>        NA     1 C[N+](C)(C)CCCC(=O)[O-]

**Comment by bowenli37** [comment]
cmpd.db[7295,]
         hmdb_id                  name pubchem_id chebi_id       kegg_id metlin_id lipid
7295 HMDB0011723 2-Methylhippuric acid      91637   613303 鈬<a5> C01586        NA     0
                        smiles
7295 CC1=CC=CC=C1C(=O)NCC(=O)O

**Comment by bowenli37** [comment]
cmpd.db[7668,]
         hmdb_id                        name pubchem_id chebi_id       kegg_id metlin_id lipid
7668 HMDB0012110 5(6)-Epoxy Prostaglandin E1   53481368       NA 鈬<a5> C04741        NA     1
                                                              smiles
7668 CCCCC[C@@H](/C=C/[C@@H]1[C@H](CC(=O)[C@H]1CC2C(O2)CCCC(=O)O)O)O

**Comment by jessica-ewald** [comment]
This was fixed in September as part of addressing Issues #96 and #168.
