### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by kengcher** [xia-lab/MetaboAnalystR#36]
Hi I am trying to install MetaboAnalystR with R 3.6 and after successfully installing all the dependencies, i ran into this error:

> devtools::install_github("xia-lab/MetaboAnalystR", build_vignettes=FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 17 packages not available: BiocParallel, CAMERA, fgsea, genefilter, GlobalAncova, globaltest, impute, KEGGgraph, limma, MSnbase, pcaMethods, preprocessCore, Rgraphviz, siggenes, SSPA, sva, xcms
✔  checking for file ‘/private/var/folders/85/9dt7x0p54jz2pcphfjjptz44k00167/T/Rtmpma5nsQ/remotes130c23c545919/xia-lab-MetaboAnalystR-0502b92/DESCRIPTION’ ...
─  preparing ‘MetaboAnalystR’:
✔  checking DESCRIPTION meta-information ...
   Warning: /private/var/folders/85/9dt7x0p54jz2pcphfjjptz44k00167/T/RtmpanEkkU/Rbuild13e254564b498/MetaboAnalystR/man/FormatPeakList.Rd:28: unexpected section header '\description'
   Warning: /private/var/folders/85/9dt7x0p54jz2pcphfjjptz44k00167/T/RtmpanEkkU/Rbuild13e254564b498/MetaboAnalystR/man/FormatPeakList.Rd:31: unexpected section header '\author'
   Warning: /private/var/folders/85/9dt7x0p54jz2pcphfjjptz44k00167/T/RtmpanEkkU/Rbuild13e254564b498/MetaboAnalystR/man/FormatPeakList.Rd:37: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘MetaboAnalystR_2.0.1.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
* installing *source* package ‘MetaboAnalystR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘CAMERA::annotate’ by ‘ggplot2::annotate’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘MSnbase::normalize’ by ‘igraph::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::recast’ by ‘reshape2::recast’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::melt’ by ‘reshape2::melt’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::colsplit’ by ‘reshape2::colsplit’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::normalize’ by ‘xcms::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::groups’ by ‘xcms::groups’ when loading ‘MetaboAnalystR’
** help
Error : (converted from warning) /private/var/folders/85/9dt7x0p54jz2pcphfjjptz44k00167/T/RtmpqERbPZ/R.INSTALL13e372fc4083d/MetaboAnalystR/man/FormatPeakList.Rd:28: unexpected section header '\description'
ERROR: installing Rd objects failed for package ‘MetaboAnalystR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/MetaboAnalystR’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/85/9dt7x0p54jz2pcphfjjptz44k00167/T//Rtmpma5nsQ/file130c245a59740/MetaboAnalystR_2.0.1.tar.gz’ had non-zero exit status

Please advise. Thank you.

**Comment by jsychong** [comment]
Hi,

It's odd that an error in the documentation would cause the package to fail but nonetheless I updated it. Installation should work for you now.

For me:

> devtools::install_github("xia-lab/MetaboAnalystR", build_vignettes=FALSE)
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 17 packages not available: BiocParallel, CAMERA, fgsea, genefilter, GlobalAncova, globaltest, impute, KEGGgraph, limma, MSnbase, pcaMethods, preprocessCore, Rgraphviz, siggenes, SSPA, sva, xcms
✔  checking for file ‘/tmp/Rtmp4sewXg/remotes571d4d19a73e/xia-lab-MetaboAnalystR-652f86a/DESCRIPTION’ ...
─  preparing ‘MetaboAnalystR’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘MetaboAnalystR_2.0.1.tar.gz’
   
Installing package into ‘/home/jasmine/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package ‘MetaboAnalystR’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘CAMERA::annotate’ by ‘ggplot2::annotate’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘MSnbase::normalize’ by ‘igraph::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::recast’ by ‘reshape2::recast’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::melt’ by ‘reshape2::melt’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::colsplit’ by ‘reshape2::colsplit’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::normalize’ by ‘xcms::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::groups’ by ‘xcms::groups’ when loading ‘MetaboAnalystR’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: replacing previous import ‘CAMERA::annotate’ by ‘ggplot2::annotate’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘MSnbase::normalize’ by ‘igraph::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::recast’ by ‘reshape2::recast’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::melt’ by ‘reshape2::melt’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘reshape::colsplit’ by ‘reshape2::colsplit’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::normalize’ by ‘xcms::normalize’ when loading ‘MetaboAnalystR’
Warning: replacing previous import ‘igraph::groups’ by ‘xcms::groups’ when loading ‘MetaboAnalystR’
* DONE (MetaboAnalystR)

Cheers!

**Comment by efratmuller** [comment]
Is it ok that the following is printed:

> Skipping 17 packages not available: BiocParallel, CAMERA, fgsea, genefilter, GlobalAncova, globaltest, impute, KEGGgraph, limma, MSnbase, pcaMethods, preprocessCore, Rgraphviz, siggenes, SSPA, sva, xcms

(As @kengcher also wrote, this is printed even after successfully installing all dependencies)

Many thanks!

**Comment by jsychong** [comment]
I believe it's ok as it doesn't turn into an error about missing dependencies - the package should work as long as all required packages are successfully installed on your computer. Please let me know though if you do run into any issues!
