### ISSUE TITLE
 CAMERA’, ‘MSnbase’, ‘xcms’ are not available (for R version 3.5.0)

### ISSUE THREAD

**Issue by FADHLyemen** [xia-lab/MetaboAnalystR#39]
Hi 
I got the below error when trying to install it
`devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))`

 devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 17 packages not available: BiocParallel, CAMERA, fgsea, genefilter, GlobalAncova, globaltest, impute, KEGGgraph, limma, MSnbase, pcaMethods, preprocessCore, Rgraphviz, siggenes, SSPA, sva, xcms
Installing 4 packages: CAMERA, MSnbase, spls, xcms
Installing packages into ‘/nfs/turbo/umms-garmire/home/alakwaaf/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
Error: (converted from warning) packages ‘CAMERA’, ‘MSnbase’, ‘xcms’ are not available (for R version 3.5.0)

**Comment by jsychong** [comment]
Hi,

You need to install CAMERA, MSnbase, and xcms separately before you can install MetaboAnalystR. Make sure you download them from Bioconductor. Also, here's a good link that can help with your particular issue if you run into other issues: https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa. 

Note that these packages themselves require other libraries to be installed on your computer such as NetCDF.
