### ISSUE TITLE
error message with normalization procedure using time series factor analysis

### ISSUE THREAD

**Issue by sonytuteja** [xia-lab/MetaboAnalystR#4]
Here is my code
# Create object mset for storing processed data, read in data
mSet<-InitDataObjects("conc", "ts", FALSE)
mSet<-SetDesignType(mSet, "time")
mSet<-Read.TextData(mSet,"GENE_time_sex.csv", "rowts", "disc")
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet)

#Normalization procedures- normalization by median and data scaling- mean-centered and divided by the standard deviation of each variable
mSet<-Normalization(mSet, "MedianNorm", "NULL", "AutoNorm", "GENE1003_D08", ratio=FALSE, ratioNum=20)
 	
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)

mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)

I get the following error "Error in apply(data, 1, MedianNorm) : dim(X) must have a positive length"

**Comment by jsychong** [comment]
The R package has been recently updated, after re-installing, does this error still show up? And is it happening immediately after the "mSet <- Normalization" function?

**Comment by sonytuteja** [comment]
Yes- this has been corrected with the install. yes it was happening right after the normalization step.
I have some additional questions
1)what is the best software to view the json file to visualize the PCA plot? Right now its opening with the text editor and just shows the data that goes into the plot.
2) I am creating a Rmd file for my analyses. Is there a way to view the output in the Rmd file rather than the program sending output files to the local directory?
