### ISSUE TITLE
Supported organisms PerformPSEA

### ISSUE THREAD

**Issue by nayfous** [xia-lab/MetaboAnalystR#41]
Hi,
Is there a list of supported organisms and their lib codes for the function PerformPSEA?
I would like to use the function with Mouse data.
Best,
Nayfous

**Comment by jsychong** [comment]
Hi, there isn't a clear list anywhere, I will include such a list in the vignette. For mice there's "mmu_biocyc", which is the BioCyc library, and "mmu_kegg" for the KEGG library.

Cheers!
