### ISSUE TITLE
Installation error in Statistical Analysis Module

### ISSUE THREAD

**Issue by ninadsc** [xia-lab/MetaboAnalystR#43]
Hi,

I am trying to install the software on my windows desktop. I am unable to complete the process with respect to two .Rmd 
 SUMMARY: processing the following files failed:
     'MetaboAnalystR_2_Workflow_From_Raw_Spectra_to_Biological_Insights.Rmd'
     'Statistical_Analysis_Module.Rmd'

The errors are: 
1.
 --- re-building 'MetaboAnalystR_2_Workflow_From_Raw_Spectra_to_Biological_Insights.Rmd' using rmarkdown
   Warning in system2(..., stdout = FALSE, stderr = FALSE) :
     '"pdflatex"' not found
   Error: processing vignette 'MetaboAnalystR_2_Workflow_From_Raw_Spectra_to_Biological_Insights.Rmd' failed with diagnostics:
   Failed to compile MetaboAnalystR_2_Workflow_From_Raw_Spectra_to_Biological_Insights.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips.

2.
-- re-building 'Statistical_Analysis_Module.Rmd' using rmarkdown
   Quitting from lines 64-70 (Statistical_Analysis_Module.Rmd) 
   Error: processing vignette 'Statistical_Analysis_Module.Rmd' failed with diagnostics:
   $ operator is invalid for atomic vectors
   --- failed re-building 'Statistical_Analysis_Module.Rmd'

Any response is appreciated. 

Thanks,

**Comment by etrh** [comment]
Try installing `MiKTeX` on your Windows machine.

https://miktex.org/download

**Comment by jsychong** [comment]
Did etrh's comment help to get this resolved?

**Comment by ninadsc** [comment]
Hello,

Thank you for your response. No, it did not solve the problem after following the other steps too. From what I see the system does not recognize the changes for R.  The pathway analysis on the website seems to be under maintenance too. 

Thanks,
