### ISSUE TITLE
Pass dataframe to function 

### ISSUE THREAD

**Issue by sstandage** [xia-lab/MetaboAnalystR#44]
Is there a way to pass a dataframe to MetaboAnalystR import functions?

**Comment by jsychong** [comment]
At the moment there's not a way, is your dataframe just a matrix of peaks/metabolites by samples?

**Comment by sstandage** [comment]
Almost. I've created specific factor levels for my conditions variable that get lost when I export it to .csv and then import it to MetaboAnalyst. I'd like to be able to retain the appropriate factor levels for the analyses and figures.
