### ISSUE TITLE
Inconsistent 3D PCA Score Plot point characteristics

### ISSUE THREAD

**Issue by sstandage** [xia-lab/MetaboAnalystR#48]
The function that builds the 3D PCA scores plot in MetaboAnalystR uses point characters that differ from the 2D plot and the 3D plot generator online, which I find more aesthetically pleasing. Can the package function be updated so that the plot characteristics are the same? Or is there something I should modify in my code? 

Thank you!

**Comment by jessica-ewald** [comment]
We are synchronizing the web and MetaboAnalystR now as part of an effort to release version 4.0

**Comment by sstandage** [comment]
Thanks!
