### ISSUE TITLE
Setting anova output file names

### ISSUE THREAD

**Issue by litepalmer** [xia-lab/MetaboAnalystR#5]
When attempting to perform multiple sequential ANOVA from the same dataset but using different groups, there is no obvious way to set file names to prevent the previous ANOVA being overwritten. Therefore you have to move the csv file from the working directory before performing the next ANOVA. 

Additionally, when using

`mSet <- ANOVA.Anal(mSet, F, 0.05, "fisher") `

this replaces the mSet object with 
`1`
therefore preventing any further analysis being completed on the same dataset unless the data is reloaded in.

**Comment by jsychong** [comment]
If I'm understanding correctly, do you wish to perform multiple different ANOVAs on the same dataset, therefore the same CSV file, but using different groups of samples? Or on different CSV files?

To address your second point, that bug has been fixed! Please update your package.
