### ISSUE TITLE
Sorting bug in PerformApproxMatch

### ISSUE THREAD

**Issue by henrywilmantessella** [xia-lab/MetaboAnalystR#51]
This bug could affect the possible matches returned 
At the end of the function, the possible matches are reduced to 10 before they are returned. 
However the object is not sorted before that, so rather than returning the 10 matches with the lowest score, the ten matches with the lowest index are returned. 

The lines are 280-284 of R/enrich_name_match.R:

```
mSetObj$dataSet$candidates<-candidates[order(candidates[,3], decreasing=F), , drop=F];   
      
if(nrow(candidates) > 10){
        mSetObj$dataSet$candidates<-candidates[1:10,];
} 
```

I suspect that `candidates` should be sorted before it is subset to the first ten rows in the third line.

**Comment by jsychong** [comment]
Thanks for pointing this out! I will look into it.

**Comment by jessica-ewald** [comment]
Sorting is performed in this line: 
mSetObj$dataSet$candidates<-candidates[order(candidates[,3], decreasing=F), , drop=F];
