### ISSUE TITLE
MS Peaks to Pathways.R : 2 issues

### ISSUE THREAD

**Issue by julienfoucaud** [xia-lab/MetaboAnalystR#53]
Hi,

I just found 2 issues in your "MS Peaks to Pathways.R" file I tried to run.

1. line 6: impossible to download the example file (both in https or in http)
mSet <- Read.PeakListData(mSet, "https://www.metaboanalyst.ca/MetaboAnalyst/resources/data/mummichog_mzs.txt")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://www.metaboanalyst.ca/MetaboAnalyst/resources/data/mummichog_mzs.txt': HTTP status was '404 Not Found'

2. line 9 : there is no function "UpdateMummichogParameters" in MetaboAnalystR v2.0.1 :
mSet <- UpdateMummichogParameters(mSet, "0.1", "positive", 1.0E-4)
Error in UpdateMummichogParameters(mSet, "0.1", "positive", 1e-04) : 
  could not find function "UpdateMummichogParameters"

I hoped I could try your mummichog implementation.
Thanks for your input on those issues

Julien

**Comment by julienfoucaud** [comment]
As I just found out, function "PerformMummichog" is also missing : 
mSet <- PerformMummichog(mSet, "hsa_mfn", "fisher", "gamma")
Error in PerformMummichog(mSet, "hsa_mfn", "fisher", "gamma") : 
  could not find function "PerformMummichog"

Other required functions are present (Read.PeakListData , SanityCheckMummichogData)

**Comment by jsychong** [comment]
Hi Julien, is it the vignette you're refering to? I belive you might be using an older version. To try out the mummichog implementation, you can follow this tutorial, starting from section 4: https://github.com/jsychong/MetaboAnalystR/blob/master/MetaboAnalystR_2_Workflow_From_Raw_Spectra_to_Biological_Insights.pdf

**Comment by julienfoucaud** [comment]
Yeah I was speaking about the current vignette. Thanks for the tip.
