### ISSUE TITLE
Example data is not accessible

### ISSUE THREAD

**Issue by bayegy** [xia-lab/MetaboAnalystR#54]
Dear @jsychong,

This url "https://www.dropbox.com/s/1v0a9b3y6pe0cbl/iHMP.zip?dl=0" for example data is not accessible now. Is there any other way by which I can access this example data?

Thanks

**Comment by jsychong** [comment]
Hi,

From what I can see the link should still work. If this is still not accessible for you please shoot me an email and I can directly send you a subset of files.

Cheers!
________________________________

**Comment by bayegy** [comment]
@jsychong

Well, that is weird. It is still not accessible for me. Here is my email: 947366452@qq.com 

Thanks a lot !
