### ISSUE TITLE
permutation test in the sample data, p value is very bad 

### ISSUE THREAD

**Issue by yiluheihei** [xia-lab/MetaboAnalystR#56]
Empirical p value is very bad, inconsistent with the results in your paper

My code is as following:

```
mSet<-InitDataObjects("pktable", "stat", FALSE)
mSet<-Read.TextData(mSet, "iHMP2_48_metaboanalyst_input.csv", "colu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "MedianNorm", "LogNorm", "AutoNorm", ratio=FALSE, ratioNum=20)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PLSDA.CV(mSet, "T",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PLSDA.Permut(mSet, 1000, "accu")
```

Thanks for your attention.

**Comment by jsychong** [comment]
Hi, the p-values that we showed were using OPLS-DA, not PLS-DA.

mSet<-OPLSR.Anal(mSet, reg=TRUE)
mSet<-PlotOPLS2DScore(mSet, "opls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotOPLS.Splot(mSet, "opls_splot_0_", "all", "png", 72, width=NA);
mSet<-PlotOPLS.MDL(mSet, "opls_mdl_0_", "png", 72, width=NA)
mSet<-OPLSDA.Permut(mSet, 1000)
mSet<-PlotOPLS.Permutation(mSet, "opls_perm_1_", "png", 72, width=NA)

![opls_perm_1_dpi72](https://user-images.githubusercontent.com/29406820/65533639-04fe9a80-decc-11e9-8e49-8f9da8c1f749.png)
