### ISSUE TITLE
Plots not showing

### ISSUE THREAD

**Issue by VeronikaKP** [xia-lab/MetaboAnalystR#57]
Hi,

visualization of data suddenly stopped working for me, although it was ok before. No error appears but neither the plot. Can it be connected to the new version?

the R code looks like this:

mSet <- InitDataObjects("conc", "stat", FALSE)
mSet <- Read.TextData(mSet, "dataset.csv", "rowu", "disc")
mSet <- SanityCheckData(mSet)
mSet<-ReplaceMin(mSet)
.on.public.web <- FALSE; 
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "SumNorm", "LogNorm","ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)

The last two lines don't do anything, no plots show up.

the code is working because when I want to extract the normalized data by
write.table(mSet[["dataSet"]][["norm"]], "normdata", row.names=T,sep="\t")
that works.

Do you have any advise?

Kind Regards
Veronika

**Comment by jsychong** [comment]
Hi Veronika, apologies for the delays, but do you still get this error?

**Comment by VeronikaKP** [comment]
Hi, yes, I cannot plot within the metaboanalyst R package. Any other package works for me. Do you have any tips how to fix it? I tried reinstalling the package, even R itself.

Veronika

**Comment by jsychong** [comment]
What errors get thrown when you try to plot? Note that the plots should appear in your working directory, and will not pop up in the plots panel in Rstudio (if using that).

**Comment by VeronikaKP** [comment]
Thank you for the explanation, it is that. I did not even think of checking the working directory! I am a new user to R. Could you please specify this in the manual? There might be some other people like me….

Kind Regards
Veronika
