### ISSUE TITLE
Web tool not saving names of metabolomics pathways, in pathway_results.csv

### ISSUE THREAD

**Issue by brinrosenthal** [xia-lab/MetaboAnalystR#6]
Hi,

Thanks for maintaining this tool- it is really helpful!

I ran into a problem downloading the results from the pathway analysis web tool (http://www.metaboanalyst.ca/faces/upload/PathUploadView.xhtml).  

When I download results, the pathway_results file does not contain the names of the pathways (see screenshot of pathway_results.csv below).  Could you please fix this?

![image](https://user-images.githubusercontent.com/6013110/33577179-0e55ba8c-d8f7-11e7-8282-9e8e953354db.png)

Thank you!!

**Comment by xzt41** [comment]
Yes， I've met the same question as you to.

**Comment by xzt41** [comment]
Could you please recover the old server "http://old.metaboanalyst.ca/" before you fixe this?

**Comment by xzt41** [comment]
And when I used the command line, I encountered another problem:

**Comment by xzt41** [comment]
And when I used the command line, I encountered another problem: 
could not find function "SetMetabolomeFilter"

**Comment by jsychong** [comment]
Hi, 

Thank you for pointing out these bugs. The pathway_results issue has been resolved! So has the finding of "SetMetabolomeFilter" in the R package. Please re-download the updated package.
