### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by markmaciejewski** [xia-lab/MetaboAnalystR#61]
Hi, I am having an issue with the installation of MetaboAnalystR_2.0.0.tar.gz in Ubuntu 18.04 with R 3.6.0

I installed all the dependencies using the instructions in the README and I do not get any dependency errors when I install or load MetaboAnalystR, but I do get a list of warning messages (shown below). The warnings only appear in version 2.0.0 and not for version 1.0.1.

It seems another person asked a similar support question earlier - but I was unsure from the thread what the fix was.

Any help you could provide would be appreciated.

> library(MetaboAnalystR)
Loading required package: lattice
Loading required package: pls

Attaching package: ‘pls’

The following object is masked from ‘package:stats’:

    loadings

Loading required package: data.table
data.table 1.12.2 using 2 threads (see ?getDTthreads).  Latest news: r-datatable.com
Warning messages:
1: replacing previous import ‘CAMERA::annotate’ by ‘ggplot2::annotate’ when loading ‘MetaboAnalystR’ 
2: replacing previous import ‘MSnbase::normalize’ by ‘igraph::normalize’ when loading ‘MetaboAnalystR’ 
3: replacing previous import ‘igraph::groups’ by ‘plotly::groups’ when loading ‘MetaboAnalystR’ 
4: replacing previous import ‘ggplot2::last_plot’ by ‘plotly::last_plot’ when loading ‘MetaboAnalystR’ 
5: replacing previous import ‘plotly::rename’ by ‘reshape::rename’ when loading ‘MetaboAnalystR’ 
6: replacing previous import ‘igraph::normalize’ by ‘xcms::normalize’ when loading ‘MetaboAnalystR’ 
7: replacing previous import ‘plotly::groups’ by ‘xcms::groups’ when loading ‘MetaboAnalystR’

**Comment by boegel** [comment]
@markmaciejewski I'm observing the same, but I think those are harmless warnings.

They are just signaling that some functions are being shadowed; for example `plotly::groups` is being shadowed by `xcms::groups` because `xcms` was loaded after `plotly` was.

That doesn't need to be problematic though, it just means that the API of the different libraries being used partially overlap. As long as the code loads them in the right order (or doesn't use those functions), it should be fine.

**Comment by jsychong** [comment]
Hi, yes I also get these warnings. MetaboAnaystR uses so many packages that a lot of the libraries end up having the same function names. This isn't an issue as we make sure that the correct functions from the library that we want are being used.
