### ISSUE TITLE
Volcano.Anal manual page has something wrong

### ISSUE THREAD

**Issue by xlhd19980327** [xia-lab/MetaboAnalystR#65]
In the function Volcano.Anal manual page, the parameter 'cmpType' of the function annotates: "Comparison type, 1 indicates group 1 vs group 2, and 2 indicates group 2 vs group 1". 
But in the R command in MetaboAnalyst web page, group 1 vs group 2 will let the parameter be 0, while group 2 vs group 1 will let the parameter be 1.
Is that something wrong?

**Comment by jsychong** [comment]
Thanks for this, it should be 0 and 1, updated manual.
