### ISSUE TITLE
Can't download any resources

### ISSUE THREAD

**Issue by chaosmaker** [xia-lab/MetaboAnalystR#69]
Hi,

When using the package, I seem to currently be always failing when doing any type of analysis because the files online aren't available. 
I.e. 
```trying URL 'https://www.metaboanalyst.ca/resources/libs/msets/pathway.rda'
Error in download.file(libPath, destfile) : 
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/msets/pathway.rda'
In addition: Warning messages:
1: In Cairo::CairoFonts(regular = "Arial:style=Regular", bold = "Arial:style=Bold",  :
  CairoFonts() has no effect on Windows. Please use par(family="...") to specify the desired font - see ?par.
2: In download.file(libPath, destfile) :
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/msets/pathway.rda': HTTP status was '404 Not Found'
```

Any ideas on how to fix that?

Thanks

**Comment by jsychong** [comment]
Hi, can you paste your code that threw your file? It seems like you're trying to do enrichment analysis, changing the file from "pathway" to "smpdb_pathway" could fix this.

**Comment by bowenli37** [comment]
So enrichment analysis use
https://www.metaboanalyst.ca/resources/libs/msets/smpdb_pathway.rda,
and pathway analysis use either
https://www.metaboanalyst.ca/resources/libs/msets/smpdb_pathway.rda
or
https://www.metaboanalyst.ca/resources/libs/msets/kegg_pathway.rda?

**Comment by jsychong** [comment]
For enrichment analysis, the path is .../resources/libs/msets/smpdb_pathway.rda, this uses the smpdb pathway library for enrichment analysis. The path is .../resources/libs/msets/kegg_pathway.rda is also used by enrichment analysis using the underlying kegg pathway library.

But for the pathway enrichment, the path is .../resources/libs/kegg/metpa/hsa.rda, in this case uses the kegg human pathway library for pathway enrichment.
________________________________

**Comment by danlessa** [comment]
The links above are broken

**Comment by jsychong** [comment]
We've changed the rda files to qs files:

# metabolite sets
 .../resources/libs/msets/smpdb_pathway.qs
.../resources/libs/msets/kegg_pathway.qs

# pathway libraries
.../resources/libs/kegg/metpa/hsa.qs
________________________________

**Comment by marcwarmoes** [comment]
Hi,
The QS files don't work with me, I get the following error:
 qs::qread("smpdb_pathway.qs")
Error in qs::qread("smpdb_pathway.qs") : QS format not detected

Maybe the are corrupt? I can read and write other qs files.

Best,

Marc

**Comment by jessica-ewald** [comment]
Links to download .qs version of files were fixed previously.
