### ISSUE TITLE
PlotPCA3DScore outputs JSON file, how to view?

### ISSUE THREAD

**Issue by ekopylova** [xia-lab/MetaboAnalystR#7]
Hello,

The documentation for function PlotPCA3DScore says the image format can be "png" or "pdf", however the code only allows for option "json" ([see Line 293](https://github.com/xia-lab/MetaboAnalystR/blob/master/R/stats_chemometrics.R#L293)). The output is a JSON file, how can I view this as a 3D PCA?

Thanks,
Jenya

**Comment by jsychong** [comment]
Hi Jenya,

There are a few software that exist to visualise your 3D PCA from the JSON file such as E-charts (online web-tool), CanvasXpress (R package), and plotly. In further updates, we plan on updating the 3D plots so users will be able to visualise plots directly.

Cheers,
Jasmine
