### ISSUE TITLE
Add one column peaks to pathways enrichment

### ISSUE THREAD

**Issue by bblum9** [xia-lab/MetaboAnalystR#70]
Hello,

Trying to reproduce analysis done on the website with the r package. The website allows for peaks to pathways enrichment using one column data (mz values ranked by t score or p value) but I cannot find documentation on how to reproduce this with the r package. Is this functionality enabled? Could it be added to the r package or better documentation provided?

Thanks!

**Comment by jsychong** [comment]
Hi, do you mean how to get one column from when users have a peak list table? Or in general the workflow starting from a one-column list?

**Comment by jessica-ewald** [comment]
Web and MetaboAnalystR are being synchronized now. Any recent additions to web code will be added here soon.
