### ISSUE TITLE
paired samples

### ISSUE THREAD

**Issue by kengcher** [xia-lab/MetaboAnalystR#75]
Hi 

I was wondering how can i indicate the pairing information in the metabolite intensities csv file?

Thank you.

**Comment by jsychong** [comment]
Hi,

To show pair information you'd need to set up your table as follows:

![nmrbin_pair](https://user-images.githubusercontent.com/29406820/65530125-5c4d3c80-dec5-11e9-836c-b42a89f90bc2.png)
