### ISSUE TITLE
Should I autoscaled my data?

### ISSUE THREAD

**Issue by FADHLyemen** [xia-lab/MetaboAnalystR#79]
Hello,
These two lines generate different downstream analysis results? Should I scaled my metabolites or just log transformed? Thank you

mSet<-Normalization(mSet, "QuntileNorm", "LogNorm", "None", ratio=FALSE, ratioNum=20)

mSet<-Normalization(mSet, "QuntileNorm", "LogNorm", "AutoNorm", ratio=FALSE, ratioNum=20)

**Comment by candidosobrinhosa** [comment]
Dear colleague,

The data normalization steps are meant to 'statistically adjust' your data. They may not (all) be necessary if they adjust properly to a normal distribution.

1. The sample normalization is intended to put your samples 'at a comparable level'. E.g.: You're working with quite heterogeneous samples in groups/treatment.

2. The data scaling will adjust your data to the normal/gaussian distribution model. Roughly, this will adjust your 'sampling' to a gaussian (frequency) distribution which would 'model' sampling of random phenomena/events (not a statistician expert here, there may be a more orthodox explanation for this).

metaboanalystR provides 'lognorm' and 'croot' transformations, but you may use other transformations calculating them prior uploading into mSet object. For instance, you may run a Box-Cox transformation test and check a best exponential transformation to your data. The test will compute an optimal power transformation, where your data may be powered to this value, λ.

After running this, I'd recommend check heatmap and multivariate modules for sample outliers.

Best regards,
