### ISSUE TITLE
Error with plotting normalized data

### ISSUE THREAD

**Issue by lstevenson09** [xia-lab/MetaboAnalystR#8]
Hi! I've been trying this package out and am getting errors trying to plot the data post normalization. Here's the code I have:
```
library(MetaboAnalystR)
mSet <- InitDataObjects("conc", "stat", FALSE)
mSet <- Read.TextData(mSet, "alldataformetabanalyst.csv", "rowu", "disc")
mSet$msgSet$read.msg
mSet <- SanityCheckData(mSet)
mSet$msgSet$check.msg
#columnwise normalization, log transformation and autoscaling
mSet <- Normalization(mSet, rowNorm = "NULL", transNorm = "LogNorm", scaleNorm = "AutoNorm", ref="NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "feature_norm", format="png", dpi=300, width=0)
mSet<-PlotSampleNormSummary(mSet, "sample_norm", format="pdf", width=NA)
```
For the last two commands, I get the same error (twice, once for each line):

> Error in if (total < sub.num) { : argument is of length zero

I've tried it with a couple different subsets of the same data set and all the data and it doesn't seem to work. I can get it to work on the online MetabAnalyst tool, which is strange.  Any help would be much appreciated and please let me know if you need more info from me!

**Comment by jsychong** [comment]
Hi!

You must use the function ReplaceMin, which replaces any missing or 0 values from your uploaded dataset before using the Normalization function like below:

mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "http://www.metaboanalyst.ca/MetaboAnalyst/resources/data/human_cachexia.csv", "rowu", "disc");
mSet<-SanityCheckData(mSet);
**mSet<-ReplaceMin(mSet);**
mSet <- Normalization(mSet, rowNorm = "NULL", transNorm = "LogNorm", scaleNorm = "AutoNorm", ref="NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "feature_norm", format="png", dpi=300, width=0)
mSet<-PlotSampleNormSummary(mSet, "sample_norm", format="pdf", width=NA)

Cheers,
Jasmine

**Comment by lstevenson09** [comment]
Hi Jasmine!
Thank you so much for your help! Just in case this helps others, I wanted to confirm that Jasmine's fix (adding the ReplaceMin command) does fix my problem - thank you! What's strange is that I don't have any missing or 0 values in my data set, which is why I didn't have that command because I didn't think I needed it. But I guess the program needs you to run that command anyways even if it doesn't do anything to the data? Anyways, thanks very much for your help!
Best,
Louise

**Comment by jsychong** [comment]
Hi Louise,

Indeed, even though it would do nothing to your data, it still "processes" it for the next step.

Happy holidays,
Jasmine
