### ISSUE TITLE
Error in SetKEGG.PathLib(mSet,"hsa")

### ISSUE THREAD

**Issue by guijie2015** [xia-lab/MetaboAnalystR#80]
Hi,when I run mSet<-SetKEGG.PathLib(mSet,"hsa"),it will report that 
"Error in download.file(libPath, destfile) : 
  cannot open URL 'https://www.metaboanalyst.ca/resources/libs/kegg/hsa.rda'"
Where I can download the "hsa.rda" to solve the problem?

**Comment by wydty** [comment]
me too

**Comment by guijie2015** [comment]
I find the solution. 
First,Download MetaboAnalyst-4.93.war from [https://www.metaboanalyst.ca/docs/Resources.xhtml]
Second,Use Decompression software to decompress the file.Then,you can find hsa.rda from MetaboAnalyst-4.93.war\resources\libs\kegg
Finally,just move the hsa.rda to your work directory.It willl work when you run SetKEGG.PathLib(mSet,"hsa") .

**Comment by KMaheswari** [comment]
@guijie2015 I tried what you suggested, but it still didn't work for me.

**Comment by rpalli** [comment]
I similarly can't get this solution to work. MetaboAnalystR does see the new hsa.rda file that has been deposited but somehow opens and deletes it without doing pathway analysis.

**Comment by junli-song** [comment]
me too！I find it still doesn't work well. I guess the code must be changed when moving the hsa.rda to  work directory，But how?

**Comment by synthbiont** [comment]
I am running the current version of the package, and it seems the hsa library is in a format different than .rda.

Now it is a qs file (that the package loads using qs). Maybe that is what caused that the hsa.rda file that you downloaded does not work anymore?

**Comment by jessica-ewald** [comment]
All files were converted to different formats. Any broken links in MetaboAnalystR will be fixed when we release the new version 4.0
