### ISSUE TITLE
Add a filename parameter to either PerformPeakAnnotation or SetAnnotationParam functions

### ISSUE THREAD

**Issue by till-bornemann** [xia-lab/MetaboAnalystR#83]
Dear Sir or Madam,

Would it be possible to add a filename parameter to either the SetAnnotationParam or PerformPeakAnnotation functions to allow definition of a file-path/-name for the currently static "{workingDirectory}/annotated_peaklist.csv" output file of the PerformPeakAnnotation function? In the current implementation, I wasnt aware that this file is actually saved before looking into the function code since I hadnt set a global working directory in my Rmarkdown and the file thus was saved to my home folder. Thus I believe that making the filename an optional parameter would raise awareness that this file is an actual output table and be an improvement to the function. 

Best regards,
Till

**Comment by jessica-ewald** [comment]
It is good practice to set your working directory at the beginning of the analysis. Many of our functions rely on reading/writing files in the working directory.
