### ISSUE TITLE
No vignette information

### ISSUE THREAD

**Issue by kerenzhou062** [xia-lab/MetaboAnalystR#84]
Hi there, I got "No vignettes found" in R v3.6.2 when running `vignette(package="MetaboAnalystR")` and `browseVignettes("MetaboAnalystR")`.

**Comment by jessica-ewald** [comment]
MetaboAnalystR can be installed with the "build_vignettes" parameter set to either TRUE or FALSE. Are you sure that you installed the vignettes along with the package? 

See the documentation in the main page (in README.md) for more details.
