### ISSUE TITLE
How to draw Network View plot from enrichment analysis results in R

### ISSUE THREAD

**Issue by kerenzhou062** [xia-lab/MetaboAnalystR#85]
Hi there, MetaboAnalystR is really helpful in metabolism analysis.
I want to know to know how to draw Network View plot. Here's the code I used for enrichment analysis.
```
  mSet <- InitDataObjects("conc", "msetora", FALSE)
  cmpd.vec <- c("C02630","C00197","C00170","C00417","C00062","C03406","C00152","C00049","C00002","D07769")
  mSet <- Setup_MapData(mSet, cmpd.vec);
  mSet <- CrossReferencing(mSet, "kegg");
  mSet <- CreateMappingResultTable(mSet)
  mSet <- SetMetabolomeFilter(mSet, F);
  mSet <- SetCurrentMsetLib(mSet, "smpdb_pathway", 2);
  mSet <- CalculateHyperScore(mSet)
  mSet <- PlotORA(mSet, 'test', "net", "pdf")
```

**Comment by dong87** [comment]
maybe the Network plot was not implemented in R, but R can do that.

**Comment by KR-Chow** [comment]
Hi dong,
Do you know how to do this in R?
Thanks,
Keren

**Comment by jessica-ewald** [comment]
Many of the figures in the web tool are generated with JavaScript and are not possible to generate with MetaboAnalystR
