### ISSUE TITLE
Error: Failed to install 'MetaboAnalystR' from GitHub

### ISSUE THREAD

**Issue by MjelleLab** [xia-lab/MetaboAnalystR#87]
Hi, do know how to overcome this error?

> devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))
Downloading GitHub repo xia-lab/MetaboAnalystR@master
Skipping 14 packages not available: impute, pcaMethods, globaltest, GlobalAncova, Rgraphviz, preprocessCore, genefilter, SSPA, sva, limma, KEGGgraph, siggenes, BiocParallel, multtest
Skipping 4 packages ahead of CRAN: metap, rlang, prettyunits, tidyr
Error: Failed to install 'MetaboAnalystR' from GitHub:07s51jtz6bm_y5880000gn/T/Rtmpq8MwPp/remotes31c2868aba8/xia-lab-MetaboAnalystR-c2af5a3/DESCRIPTION’ ...
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/knitr/R/knitr.rdb' is corrupt
In addition: Warning messages:
1: In get("is_latex_output", asNamespace("knitr")) :
  restarting interrupted promise evaluation
2: In get("is_latex_output", asNamespace("knitr")) :
  internal error -3 in R_decompress1

**Comment by jessica-ewald** [comment]
It looks like the problem is with the knitr R package. Try uninstall and reinstall.
