### ISSUE TITLE
Will not install from github on Windows

### ISSUE THREAD

**Issue by rpalli** [xia-lab/MetaboAnalystR#88]
Sorry to bother you. I have tried on two different computers and tried to update all required packages. Output is as follows:
* installing *source* package 'MetaboAnalystR' ...
** R
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'pls' was built under R version 3.5.3
ERROR: lazy loading failed for package 'MetaboAnalystR'
* removing 'C:/Users/rohit/Documents/R/win-library/3.5/MetaboAnalystR'
In R CMD INSTALL
Error: Failed to install 'MetaboAnalystR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/rohit/AppData/Local/Temp/RtmpMbqiRD/file18342c11b88/MetaboAnalystR_2.0.2.tar.gz’ had non-zero exit status'

**Comment by rpalli** [comment]
I was ultimately able to install the stable 2.0 version but only by copying and pasting the source into my R packages directory then using install.packages('MetaboAnalystR_2.0.0.tar.gz', repos = NULL, type="source").

**Comment by ManarRashad** [comment]
@rpalli 
Please what do you mean by "copying and pasting the source into my R packages directory"

**Comment by rpalli** [comment]
I downloaded 'MetaboAnalystR-2.0.0.zip' and unzipped it which yielded a folder titled 'MetaboAnalystR-2.0.0' with the contents of MetaboAnalystR. I copied this folder into'Documents\R\win-library\3.5' to make a new folder 'Documents\R\win-library\3.5\MetaboAnalystR' with all the MetaboAnalystR files. I then ran install.packages('MetaboAnalystR_2.0.0.tar.gz', repos = NULL, type="source") with the files already in place.

**Comment by rpalli** [comment]
For anyone still having trouble, I could get the newest version to install on R 3.6.2 but not 3.5.2.

**Comment by amcaraballor** [comment]
Hi @rpalli , I still have issues installing the 2.0.3 version either via github or any other options, including copying and pasting the unzipped folder into my win-library. The install.packages('MetaboAnalystR_2.0.3.tar.gz', repos = NULL, type="source") does not work either. Neither this option: devtools::install_github(("xia-lab/MetaboAnalystR")). Thoughts?

**Comment by rpalli** [comment]
Hi @amcaraballor,
I was ultimately able to install the newest (I think 2.0.3) version by upgrading from R 3.5.2 to R 3.6.2 and following all the installation instructions from the start again (with no need to copy and paste).
