### ISSUE TITLE
Please make a new release with 2.0.2

### ISSUE THREAD

**Issue by Slugger70** [xia-lab/MetaboAnalystR#89]
This way I can update the bioconda release.

**Comment by sukanka** [comment]
I also think so, please make a new release with 3.2.0, @Zhiqiang-PANG.

**Comment by jessica-ewald** [comment]
We are working on a new release now.

**Comment by sukanka** [comment]
> We are working on a new release now.

Could you please make a github  release or a tag for the new release?

**Comment by Zhiqiang-PANG** [comment]
We will make a release as soon as it is stable. Thanks!
