### ISSUE TITLE
could not find function "GetCandidateList"

### ISSUE THREAD

**Issue by ekopylova** [xia-lab/MetaboAnalystR#9]
Hello,

I followed your 2.1 Over representation analysis tutorial and all commands worked well until:

```r
> mSet <- GetCandidateList(mSet);
Error in GetCandidateList(mSet) : 
  could not find function "GetCandidateList"
> ?GetCandidateList
```

I'm able to see the help window for this function, however the function itself is not running as expected. Do you know why this can be?

Thanks!

**Comment by falafel19** [comment]
Hey I had the same Problem It worked when i call the function this way:
> mSet<-MetaboAnalystR:::GetCandidateList(mSet)
its strange though that you have to call it  like that

**Comment by ekopylova** [comment]
Thanks, this worked. However, I'm having an issue with the next command as well:

```r
> mSet<-MetaboAnalystR:::GetCandidateList(mSet);
> mSet<-SetCandidate(mSet, "L-Isolucine", "L-Isoleucine");
Error in if (ncol(csv.res) > 6) { : argument is of length zero
```

Appreciate any input,
Jenya

**Comment by falafel19** [comment]
Same here from looking at the code i realized that:
in the function SetCandidate(mSet)
        csv.res <- mSetObj$dataSet$map.table
since mSetObject is equal to mSet it seems that the mSet object does not have a $data$map.table entity.
but I have not figured out how to fix it. I hope it will e fixed soon

**Comment by jsychong** [comment]
Hi,

Thank you for your comments! I've fixed the issue with finding GetCandidateList(mSet), and will work on getting the SetCandidate command fixed soon.

**Comment by jsychong** [comment]
Hi,

There was a new function that was not being called (CreateMappingResultTable), the new workflow is as follows (and will be updated in the Vignette):

1. | mSet<-InitDataObjects("conc", "msetora", FALSE)
2. cmpd.vec<-c("Acetoacetic acid","Beta-Alanine","Creatine","Dimethylglycine","Fumaric acid","Glycine","Homocysteine","L-Cysteine","L-Isolucine","L-Phenylalanine","L-Serine","L-Threonine","L-Tyrosine","L-Valine","Phenylpyruvic acid","Propionic acid","Pyruvic acid","Sarcosine")
3. mSet<-Setup.MapData(mSet, cmpd.vec);
4. mSet<-CrossReferencing(mSet, "name");
5. mSet<-CreateMappingResultTable(mSet)
6. mSet<-PerformDetailMatch(mSet, "L-Isolucine");
7. mSet<-GetCandidateList(mSet);
8. mSet<-SetCandidate(mSet, "L-Isolucine", "L-Isoleucine");

Cheers!
