### ISSUE TITLE
tryCatch throw error in warning block in .read.metaboanalyst.lib

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#92]
Hi,

print() throws error. print() in the warning block turns a warning into error.

I discovered this because when compound_db.rds was loaded, it throws a warning regarding encoding, which was then turned into an error by print(). 

```
tryCatch({
        my.lib <- readRDS(lib.path) # throws warning regarding encoding
        print("Loaded files from MetaboAnalyst web-server.")
    }, warning = function(w) {
        print() # warning from readRDS comes here and becomes an error
    }, error = function(err) {
        print("Reading data unsuccessful, attempting to re-download file...")
        tryCatch({
            lib.url <- paste("https://www.metaboanalyst.ca/resources/libs/", 
                filenm, sep = "")
            download.file(lib.url, destfile = filenm, method = "curl")
            my.lib <- readRDS(lib.path)
            print("Loaded necessary files.")
        }, warning = function(w) {
            print()
        }, error = function(err) {
            print("Loading files from server unsuccessful. Ensure curl is downloaded on your computer.")
        })
    })
```

thank you for your time and great work!
Bowen

**Comment by bowenli37** [comment]
By the way, I did the following to mark the encoding of my.lib as UTF8, which is from compound_db.rds.

`
library(stringi)

# compound_db.rds downloaded
my.lib <- readRDS('compound_db.rds')
plyr::llply(my.lib, function(x) {all(stri_enc_isutf8(x), na.rm = T)})
## name is FALSE

## check if each name is utf8 encoded
name.isutf8 <- stri_enc_isutf8(my.lib$name)
my.lib$name[which(!name.isutf8)]

cmpd.name.notutf8 <- my.lib$name[which(!name.isutf8)]
cmpd.name.utf8 <- stri_encode(cmpd.name.notutf8, '', 'UTF-8')

my.lib[!name.isutf8, 'name'] <- cmpd.name.utf8
plyr::llply(my.lib, function(x) {all(stri_enc_isutf8(x), na.rm = T)})

saveRDS(my.lib, file = 'database/metaboanalyst/20200223/compound_db_utf8.rds')
`

**Comment by efratmuller** [comment]
Hi, I'm having a probably related issue: I'm getting an error when running CrossReference that seems like a downloading error, but I actually do have the file downloaded (and no curl problem) so I think this may be something else. It worked fine up to a week or two ago. Perhaps something changed in the URL?

Here is what I ran:
```
mSet <- InitDataObjects("NA", "utils", FALSE) 
mSet <- Setup.MapData(mSet, cmpds)
mSet <- CrossReferencing(mSet, "name")
```

Here is the error I got from the last command:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  497k  100  497k    0     0   497k      0  0:00:01  0:00:01 --:--:--  265k
[1] "Reading data unsuccessful, attempting to re-download file..."
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  497k  100  497k    0     0   497k      0  0:00:01  0:00:01 --:--:--  260k
[1] "Loading files from server unsuccessful. Ensure curl is downloaded on your computer."
Error in .read.metaboanalyst.lib("compound_db.rds") : 
  object 'my.lib' not found
```

Can you please help?

**Comment by bowenli37** [comment]
You may want to manually download compound_db.rds from http://www.metaboanalyst.ca/resources/libs/compound_db.rds and try again.
If you see warning about encoding, then it is the same problem. You can convert the encoding to UTF-8 and save it.

**Comment by Skourtis** [comment]
Same problem here. Has this been solved?

**Comment by CLZHANG96** [comment]
I have the same problem right now.

**Comment by Zhiqiang-PANG** [comment]
Please reinstall the package. currently MetaboAnalyst is not using .rds data any longer. Closed.
