### ISSUE TITLE
smpdb_pathway.rda and kegg_pathway.rda has empty member for hMSEA6257 | Nucleotide Excision Repair

### ISSUE THREAD

**Issue by bowenli37** [xia-lab/MetaboAnalystR#95]
> hMSEA6257 | Nucleotide Excision Repair

**Comment by junli-song** [comment]
opening smpdb_pathway.rda is normal，but kegg_pathway.rda is unnormal，why?

**Comment by jessica-ewald** [comment]
Files were rebuilt to .qs and updated previously. Closing.
