### ISSUE TITLE
installing error

### ISSUE THREAD

**Issue by saifsikdar** [xia-lab/MetaboAnalystR#97]
Hi, I am newly learning R and metabolomic analysis. I am trying to follow your tutorial. I run the following code, however, I see an error message. Can you please help?

`# Step 1: Install devtools
install.packages("devtools")
library(devtools)

### For users with devtools > v2.0.0 ###

# Step 2: Install MetaboAnalystR with documentation
devtools::install_github("xia-lab/MetaboAnalystR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"))`

![installing](https://user-images.githubusercontent.com/34520963/77485596-1ed55780-6df3-11ea-8727-4e9eedb1684f.JPG)

**Comment by junli-song** [comment]
I suggest you can directly download .zip file ,next install it in Rstuio window`build--install and restart`.I have tried it.
